import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Canvas Review System - Obsidian Plugin
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// ========== 输出路径决策 ==========
// 优先级: OBSIDIAN_VAULT 环境变量 > 默认 vault 路径 > 源码目录(CI/发布用)
const PLUGIN_ID = "canvas-review-system";

function resolveOutDir() {
	// 1. 环境变量 (其他开发者 / CI)
	if (process.env.OBSIDIAN_VAULT) {
		const dir = path.join(process.env.OBSIDIAN_VAULT, ".obsidian", "plugins", PLUGIN_ID);
		console.log(`[vault] Using OBSIDIAN_VAULT env: ${dir}`);
		return dir;
	}
	// 2. 默认 vault 路径 (本地开发)
	const defaultVault = path.resolve(__dirname, "../../笔记库/.obsidian/plugins", PLUGIN_ID);
	if (fs.existsSync(path.resolve(__dirname, "../../笔记库/.obsidian/plugins"))) {
		console.log(`[vault] Using default vault: ${defaultVault}`);
		return defaultVault;
	}
	// 3. 回退到源码目录 (CI 构建 / GitHub Release 打包)
	console.warn("⚠️  Vault not found, outputting to source directory (for CI/release only)");
	return __dirname;
}

const outDir = resolveOutDir();
const outfile = path.join(outDir, "main.js");

// 确保输出目录存在
if (!fs.existsSync(outDir)) {
	fs.mkdirSync(outDir, { recursive: true });
}

// ========== 同步 manifest.json + styles.css 到 vault ==========
function syncAssetsToVault() {
	if (outDir === __dirname) return; // 源码目录不需要同步
	const assets = ["manifest.json", "styles.css"];
	for (const asset of assets) {
		const src = path.join(__dirname, asset);
		const dest = path.join(outDir, asset);
		if (fs.existsSync(src)) {
			fs.copyFileSync(src, dest);
		}
	}
}

// ========== esbuild 配置 ==========
const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile,
});

if (prod) {
	await context.rebuild();
	syncAssetsToVault();
	// 生产模式: 同时在源码目录保留一份 (用于 GitHub Release 上传)
	if (outDir !== __dirname) {
		fs.copyFileSync(outfile, path.join(__dirname, "main.js"));
		console.log("📋 Copied main.js to source dir (for GitHub Release)");
	}
	console.log("✅ Production build complete");
	console.log(`   Output: ${outfile}`);
	process.exit(0);
} else {
	// 开发模式: 创建 .hotreload 标记文件
	if (outDir !== __dirname) {
		const hotreloadPath = path.join(outDir, ".hotreload");
		if (!fs.existsSync(hotreloadPath)) {
			fs.writeFileSync(hotreloadPath, "");
			console.log("🔥 Created .hotreload marker (hot-reload plugin will watch this dir)");
		}
	}
	syncAssetsToVault();
	await context.watch();
	console.log(`👀 Watching for changes... Output: ${outfile}`);
}
