// ✅ Verified from Context7: /obsidianmd/obsidian-sample-plugin (esbuild configuration)
// ✅ Verified from Story 13.1 Dev Notes: canvas-progress-tracker/docs/obsidian-plugin-architecture.md#构建脚本
import esbuild from "esbuild";
import process from "process";
import path from "path";
import { fileURLToPath } from "url";
import builtins from "builtin-modules";
import fs from "fs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Canvas Review System - Obsidian Plugin
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// 🔴 P0: outfile 必须指向 vault 插件目录
// 源码编译 → vault 部署 是一步完成的，不需要手动复制
// 血泪教训: outfile: 'main.js' 导致 vault 和源码长期不同步
//
// CI-safe: 在 GitHub Actions 中 vault 路径不存在，
// 通过 VAULT_PLUGIN_DIR 环境变量或 CI 检测自动回退到本地输出
//
// Vault 路径候选列表（按优先级），第一个存在的会被使用
import { homedir } from "os";
const vaultCandidates = [
  process.env.VAULT_PLUGIN_DIR,
  path.join(homedir(), 'Desktop', 'spring course 2026', 'CS188', '.obsidian', 'plugins', 'canvas-review-system'),
  path.join(__dirname, '..', '..', '笔记库', '.obsidian', 'plugins', 'canvas-review-system'),
].filter(Boolean);

const isCI = process.env.CI === 'true' || process.env.GITHUB_ACTIONS === 'true';
const vaultPluginDir = vaultCandidates.find(d => fs.existsSync(d));

const outfile = vaultPluginDir
  ? path.join(vaultPluginDir, 'main.js')
  : path.join(__dirname, 'main.js');

if (!vaultPluginDir && !isCI) {
  console.warn(`\n⚠️  No vault path found. Tried:\n${vaultCandidates.map(d => `    - ${d}`).join('\n')}`);
  console.warn(`    Output will go to: ${outfile}`);
  console.warn(`    Run 'npm run deploy:sync' after vault is available.\n`);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: outfile,
});

if (prod) {
	await context.rebuild();
	console.log(`\n✅ Built to vault: ${outfile}`);
	process.exit(0);
} else {
	await context.watch();
	console.log(`Canvas Review System: Watching for changes → ${outfile}`);
}
