mappings:
- pattern: Math 54/**
  subject: math54
  category: math
- pattern: Physics 7A/**
  subject: physics7a
  category: physics
- pattern: "\aI\U000181D2"
  subject: +Nh
  category: "}4#\U000A1CDF\\\U000E4790\x81\a[]æ%O\N¼"
- pattern: '2'
  subject: '`uß6Aú'
  category: "ÚÛ¯धsê\x15*f"
- pattern: "À\x0E\U000101FD"
  subject: 𴾖¼Â􏎇
  category: ''
- pattern: æœÆŒﬀʤʨß
  subject: Jê𜆤h
  category: "\x94\U000943B4Q"
- pattern: ¢
  subject: "Ù\U000B2F1F\x86"
  category: "U\x1Eº\U00096B32\U000D8495N"
category_rules:
  math:
  - math*
  - 数学*
  physics:
  - physics*
  - 物理*
defaults:
  category: general
  subject: general
skip_directories:
- .canvas-links
- .trash
- vault
- attachments
- .git
- .obsidian
- node_modules
- notes
- templates
- 笔记库
