# specs/behavior/obsidian-plugin-ui.feature
# Generated by: PM Agent *create-behavior-spec
# Date: 2025-11-25
# Related: Epic 13, Story 13.1-13.9

@epic-13 @priority-p0
Feature: Obsidian Plugin UI Integration
  As a learner
  I want all Canvas Learning features accessible within Obsidian
  So that I can learn without switching between applications

  # ══════════════════════════════════════════════════════════════════
  # BACKGROUND
  # ══════════════════════════════════════════════════════════════════

  Background:
    Given the Canvas Learning System Obsidian plugin is installed
    And plugin is enabled in Obsidian settings
    And FastAPI backend is running

  # ══════════════════════════════════════════════════════════════════
  # SECTION 1: PLUGIN INITIALIZATION
  # ══════════════════════════════════════════════════════════════════

  @story-13.1 @smoke
  Scenario: Plugin loads successfully on Obsidian start
    Given Obsidian is starting
    When plugin onload() is called
    Then plugin registers all ribbon icons
    And plugin registers all commands
    And plugin connects to FastAPI backend
    And status bar shows "Canvas Learning: 已连接"
    # Implementation: class CanvasLearningPlugin extends Plugin

  @story-13.1 @error-handling
  Scenario: Plugin handles backend unavailable
    Given FastAPI backend is not running
    When plugin attempts connection
    Then plugin retries 3 times with exponential backoff
    And after failures, shows Notice "后端服务不可用"
    And status bar shows "Canvas Learning: 离线模式"
    And limited offline features remain available

  @story-13.1
  Scenario: Plugin loads settings from storage
    Given user has custom settings saved
    When plugin initializes
    Then settings are loaded from plugin data
    And UI reflects saved preferences

  # ══════════════════════════════════════════════════════════════════
  # SECTION 2: RIBBON ICONS (TOOLBAR)
  # ══════════════════════════════════════════════════════════════════

  @story-13.2 @ui
  Scenario: Ribbon icons are registered
    When plugin loads
    Then ribbon bar contains icons:
      | icon    | tooltip              | action              |
      | brain   | 基础拆解             | basic_decompose     |
      | sparkles| 深度拆解             | deep_decompose      |
      | star    | 评分                 | score_nodes         |
      | message | 口语化解释           | oral_explain        |
      | zap     | 智能批量处理         | smart_parallel      |
      | calendar| 今日复习             | daily_review        |
      | link    | Canvas关联           | canvas_association  |
    # Implementation: this.addRibbonIcon('brain', '基础拆解', callback)

  @story-13.2 @ui
  Scenario: Click ribbon icon triggers agent operation
    Given Canvas "离散数学.canvas" is open
    And a yellow node "node-001" is selected
    When user clicks "基础拆解" ribbon icon
    Then basic_decomposition agent is invoked
    And progress indicator appears
    And question nodes are added to Canvas

  @story-13.2 @ui
  Scenario: Ribbon icon disabled when no Canvas open
    Given no Canvas file is open
    When user clicks any agent ribbon icon
    Then Notice shows "请先打开一个Canvas文件"
    And no operation is performed

  # ══════════════════════════════════════════════════════════════════
  # SECTION 3: COMMAND PALETTE
  # ══════════════════════════════════════════════════════════════════

  @story-13.3
  Scenario: Commands registered in palette
    When user opens command palette (Ctrl+P)
    Then commands are available:
      | command_id                    | name                    |
      | canvas-learning:decompose     | Canvas Learning: 基础拆解|
      | canvas-learning:deep-decompose| Canvas Learning: 深度拆解|
      | canvas-learning:score         | Canvas Learning: 评分    |
      | canvas-learning:oral-explain  | Canvas Learning: 口语化解释|
      | canvas-learning:smart-parallel| Canvas Learning: 智能批量处理|
      | canvas-learning:daily-review  | Canvas Learning: 今日复习|
      | canvas-learning:settings      | Canvas Learning: 设置    |

  @story-13.3
  Scenario: Execute command from palette
    Given Canvas "离散数学.canvas" is open
    When user executes "Canvas Learning: 评分" from palette
    Then scoring_agent is invoked for all yellow nodes
    And results are displayed

  # ══════════════════════════════════════════════════════════════════
  # SECTION 4: MODAL DIALOGS
  # ══════════════════════════════════════════════════════════════════

  @story-13.4 @ui
  Scenario: Operation progress modal
    Given agent operation is started
    When operation is in progress
    Then Modal shows:
      | element        | content                    |
      | title          | 正在处理...                |
      | progress_bar   | 动态更新的进度条           |
      | status         | 当前处理的节点名称         |
      | cancel_button  | 取消                       |
    # Implementation: class ProgressModal extends Modal

  @story-13.4 @ui
  Scenario: Operation result modal
    Given agent operation completed
    When results are ready
    Then Modal shows:
      | element        | content                    |
      | title          | 操作完成                   |
      | summary        | 处理了N个节点              |
      | details        | 各节点处理结果列表         |
      | close_button   | 关闭                       |

  @story-13.4 @ui
  Scenario: Agent selection modal
    Given user triggered operation on node
    And node type is ambiguous
    When agent selection is needed
    Then Modal shows agent options:
      | option | agent              | description        |
      | 1      | basic-decomposition| 基础拆解 - 生成问题|
      | 2      | oral-explanation   | 口语化解释         |
      | 3      | four-level-explanation | 四层次解释     |
    And user can select preferred agent

  # ══════════════════════════════════════════════════════════════════
  # SECTION 5: SETTINGS TAB
  # ══════════════════════════════════════════════════════════════════

  @story-13.5 @ui
  Scenario: Plugin settings tab
    When user opens Obsidian Settings > Canvas Learning
    Then settings tab displays:
      | setting          | type      | description              |
      | Backend URL      | text      | FastAPI服务地址          |
      | Auto-connect     | toggle    | 启动时自动连接           |
      | Parallel limit   | slider    | 最大并行数 (1-100)       |
      | Theme            | dropdown  | 深色/浅色主题            |
      | Language         | dropdown  | 中文/English             |
    # Implementation: class CanvasLearningSettingTab extends PluginSettingTab

  @story-13.5 @ui
  Scenario: Change backend URL setting
    Given user is in settings tab
    When user changes Backend URL to "http://localhost:9000"
    And clicks outside the text field
    Then setting is saved automatically
    And plugin reconnects to new URL

  @story-13.5 @ui
  Scenario: Reset settings to default
    Given user has custom settings
    When user clicks "重置为默认" button
    Then confirmation dialog appears
    And on confirm, all settings reset to defaults

  # ══════════════════════════════════════════════════════════════════
  # SECTION 6: STATUS BAR
  # ══════════════════════════════════════════════════════════════════

  @story-13.6 @ui
  Scenario: Status bar shows connection status
    Given plugin is loaded
    When backend is connected
    Then status bar item shows "Canvas Learning: 已连接"
    And status bar item is green
    # Implementation: this.addStatusBarItem().setText(...)

  @story-13.6 @ui
  Scenario: Status bar shows operation progress
    Given agent operation is running
    When status bar updates
    Then status bar shows "Canvas Learning: 处理中 (3/10)"
    And updates in real-time

  @story-13.6 @ui
  Scenario: Status bar click opens dashboard
    Given status bar item is visible
    When user clicks status bar item
    Then dashboard side panel opens
    And shows system status overview

  # ══════════════════════════════════════════════════════════════════
  # SECTION 7: CONTEXT MENU
  # ══════════════════════════════════════════════════════════════════

  @story-13.7 @ui
  Scenario: Canvas node context menu
    Given Canvas is open
    And user right-clicks on a yellow node
    When context menu appears
    Then menu includes Canvas Learning options:
      | menu_item       | action                |
      | 基础拆解        | basic_decompose       |
      | 深度拆解        | deep_decompose        |
      | 评分            | score_node            |
      | 口语化解释      | oral_explain          |
      | 关联到其他Canvas| cross_canvas_link     |

  @story-13.7 @ui
  Scenario: Context menu action executes on selected nodes
    Given 3 yellow nodes are selected
    When user right-clicks and selects "评分"
    Then scoring_agent processes all 3 nodes
    And results update all 3 nodes

  # ══════════════════════════════════════════════════════════════════
  # SECTION 8: DAILY REVIEW PANEL
  # ══════════════════════════════════════════════════════════════════

  @story-13.8 @ui @smoke
  Scenario: Open daily review panel
    Given today's review items exist
    When user clicks "今日复习" ribbon icon
    Then side panel opens showing:
      | element         | content                    |
      | title           | 今日复习                   |
      | due_count       | 今日到期: 15个概念         |
      | canvas_list     | 按Canvas分组的复习项       |
      | start_button    | 开始复习                   |
    # Implementation: Custom ItemView subclass

  @story-13.8 @ui
  Scenario: Start review session from panel
    Given daily review panel is open
    And 15 items are due today
    When user clicks "开始复习"
    Then first review Canvas is opened
    And review mode is activated
    And progress tracker starts

  @story-13.8 @ui
  Scenario: Review panel shows no items due
    Given no review items are due today
    When user opens daily review panel
    Then panel shows "今日无复习任务"
    And shows next review date

  # ══════════════════════════════════════════════════════════════════
  # SECTION 9: SINGLE NODE ANALYSIS UI
  # ══════════════════════════════════════════════════════════════════

  @story-13.9 @ui
  Scenario: Single node analysis popup
    Given user selects a single yellow node
    When user clicks "分析" button (or hotkey)
    Then popup shows node analysis:
      | section         | content                    |
      | 概念名称        | 逆否命题                   |
      | 当前状态        | 黄色 (待评分)              |
      | 推荐操作        | 基础拆解 / 评分            |
      | 历史记录        | 最近3次操作                |

  @story-13.9 @ui
  Scenario: Quick action buttons in analysis popup
    Given single node analysis popup is open
    When user clicks quick action button
    Then corresponding agent is invoked immediately
    And popup shows progress indicator

  # ══════════════════════════════════════════════════════════════════
  # SECTION 10: NOTIFICATIONS
  # ══════════════════════════════════════════════════════════════════

  @story-13.10 @ui
  Scenario: Success notification
    Given agent operation completed successfully
    When showing result
    Then Notice displays "操作完成: 已处理5个节点"
    And Notice auto-dismisses after 5 seconds
    # Implementation: new Notice('message', 5000)

  @story-13.10 @ui
  Scenario: Error notification
    Given agent operation failed
    When error occurs
    Then Notice displays "操作失败: {error_message}"
    And Notice persists until dismissed
    And Notice includes "查看详情" link

  @story-13.10 @ui
  Scenario: Review reminder notification
    Given it's 9:00 AM
    And user has 10 items due for review
    When reminder triggers
    Then Notice displays "今日有10个概念需要复习"
    And Notice includes "开始复习" action button

  # ══════════════════════════════════════════════════════════════════
  # SECTION 11: KEYBOARD SHORTCUTS
  # ══════════════════════════════════════════════════════════════════

  @story-13.11
  Scenario: Hotkey for common operations
    When plugin registers hotkeys
    Then default hotkeys are:
      | hotkey       | action              |
      | Ctrl+Shift+D | 基础拆解            |
      | Ctrl+Shift+S | 评分选中节点        |
      | Ctrl+Shift+R | 打开今日复习        |
      | Ctrl+Shift+P | 智能批量处理        |

  @story-13.11
  Scenario: Customizable hotkeys
    Given user opens Obsidian Hotkeys settings
    When searching for "Canvas Learning"
    Then all Canvas Learning commands are listed
    And user can customize any hotkey

  # ══════════════════════════════════════════════════════════════════
  # SECTION 12: THEME COMPATIBILITY
  # ══════════════════════════════════════════════════════════════════

  @story-13.12 @ui
  Scenario: Plugin respects Obsidian theme
    Given Obsidian is using dark theme
    When plugin UI renders
    Then all plugin UI elements use dark theme colors
    And contrast ratios meet accessibility standards

  @story-13.12 @ui
  Scenario: Plugin UI works with custom themes
    Given user has custom CSS theme installed
    When plugin UI renders
    Then plugin uses CSS variables from theme
    And no visual conflicts occur
