# specs/behavior/rollback-recovery.feature
# Generated by: PM Agent *create-behavior-spec
# Date: 2025-11-25
# Related: Epic 17, Epic 18, Section 5 Risk Assessment

@epic-17 @epic-18 @priority-p1
Feature: Rollback and Recovery System
  As a user
  I want to rollback failed operations and recover from errors
  So that I can safely experiment without fear of data loss

  # ══════════════════════════════════════════════════════════════════
  # BACKGROUND
  # ══════════════════════════════════════════════════════════════════

  Background:
    Given the Canvas Learning System is initialized
    And WriteHistory manager is active
    And backup system is configured

  # ══════════════════════════════════════════════════════════════════
  # SECTION 1: WRITE HISTORY MANAGEMENT
  # ══════════════════════════════════════════════════════════════════

  @story-17.1 @smoke
  Scenario: Record Canvas write operation
    Given Canvas "离散数学.canvas" is open
    When agent writes a new node to Canvas
    Then WriteHistory records the operation:
      | field       | value                    |
      | timestamp   | ISO 8601 format          |
      | operation   | add_node                 |
      | canvas_path | 离散数学.canvas          |
      | node_id     | generated UUID           |
    And Canvas snapshot is stored before the write

  @story-17.1
  Scenario: History records multiple operation types
    Given various agent operations are performed
    When operations complete
    Then WriteHistory contains entries for:
      | operation_type | description              |
      | add_node       | New node created         |
      | update_node    | Node content/color changed|
      | add_edge       | New edge created         |
      | create_file    | MD file created          |
      | delete_node    | Node removed             |

  @story-17.1
  Scenario: History auto-cleanup for old entries
    Given WriteHistory has 100+ operations
    And oldest operation is 7 days old
    When auto-cleanup runs
    Then operations older than 7 days are archived
    And active history limited to 50 most recent
    And archived operations are still recoverable

  # ══════════════════════════════════════════════════════════════════
  # SECTION 2: CANVAS SNAPSHOT SYSTEM
  # ══════════════════════════════════════════════════════════════════

  @story-17.2 @smoke
  Scenario: Create Canvas snapshot before operation
    Given Canvas has 10 nodes
    When new write operation is about to execute
    Then complete Canvas JSON is captured
    And snapshot is stored with timestamp key
    And snapshot includes all nodes and edges

  @story-17.2
  Scenario: Snapshot storage efficiency
    Given Canvas file is 50KB
    And 20 operations are performed
    When snapshots are stored
    Then incremental snapshots are used (delta compression)
    And total storage < 20 x 50KB (compression applied)
    And snapshot retrieval time < 100ms

  @story-17.2
  Scenario: Snapshot limit per session
    Given session has 60 snapshots
    And limit is 50 snapshots
    When 61st operation occurs
    Then oldest snapshot is removed
    And snapshot count stays at 50
    And removed snapshot is archived (if configured)

  # ══════════════════════════════════════════════════════════════════
  # SECTION 3: ROLLBACK BY STEPS
  # ══════════════════════════════════════════════════════════════════

  @story-17.3 @smoke
  Scenario: Rollback single step
    Given Canvas has nodes [A, B, C, D, E]
    And last operation added node E
    When user requests rollback 1 step
    Then Canvas is restored to [A, B, C, D]
    And node E is removed
    And rollback result confirms "已回滚1步"

  @story-17.3
  Scenario: Rollback multiple steps
    Given WriteHistory has 10 operations
    And Canvas has 10 added nodes
    When user requests rollback 5 steps via API:
      """
      POST /api/canvas/rollback
      {
        "canvas_path": "离散数学.canvas",
        "rollback_steps": 5
      }
      """
    Then Canvas is restored to state before step 6
    And 5 most recent nodes are removed
    And response includes:
      | field             | value              |
      | success           | true               |
      | rolled_back_steps | 5                  |
      | restored_timestamp| ISO 8601           |

  @story-17.3 @error-handling
  Scenario: Rollback more steps than available
    Given WriteHistory has only 3 operations
    When user requests rollback 10 steps
    Then error response is returned:
      | field   | value                          |
      | success | false                          |
      | error   | 无法回滚10步,总共只有3步操作   |
    And Canvas remains unchanged

  # ══════════════════════════════════════════════════════════════════
  # SECTION 4: ROLLBACK BY TIMESTAMP
  # ══════════════════════════════════════════════════════════════════

  @story-17.4
  Scenario: Rollback to specific timestamp
    Given WriteHistory spans from 10:00 to 10:30
    And user wants to restore state at 10:15
    When user requests rollback to timestamp:
      """
      POST /api/canvas/rollback
      {
        "canvas_path": "离散数学.canvas",
        "rollback_to_timestamp": "2025-11-25T10:15:00Z"
      }
      """
    Then Canvas is restored to snapshot at 10:15
    And all operations after 10:15 are undone
    And response includes restored timestamp

  @story-17.4 @error-handling
  Scenario: Rollback to timestamp before history
    Given earliest snapshot is at 10:00
    When user requests rollback to 09:30
    Then error response indicates:
      | error | 无法找到时间点09:30的快照 |
    And suggestion to use earliest available timestamp

  # ══════════════════════════════════════════════════════════════════
  # SECTION 5: ROLLBACK UI
  # ══════════════════════════════════════════════════════════════════

  @story-17.5 @ui
  Scenario: Error dialog with rollback option
    Given agent operation failed
    When error modal is displayed
    Then modal shows:
      | element       | content                    |
      | title         | Agent操作出错              |
      | message       | scoring-agent评分失败      |
      | button_1      | 重试                       |
      | button_2      | 回滚到错误前               |
      | button_3      | 取消                       |

  @story-17.5 @ui
  Scenario: Rollback history view
    Given user opens rollback panel from settings
    When panel loads
    Then displays recent 20 operations:
      | timestamp   | operation | node_id | status    |
      | 10:30:05    | add_node  | q-005   | completed |
      | 10:30:03    | add_node  | q-004   | completed |
      | 10:30:01    | add_node  | q-003   | completed |
    And user can select any operation to rollback to

  @story-17.5 @ui
  Scenario: Confirm rollback action
    Given user selected rollback to 5 steps ago
    When user clicks "回滚" button
    Then confirmation dialog appears:
      | message | 确定要回滚5步操作吗？此操作不可撤销。 |
    And user must confirm to proceed

  # ══════════════════════════════════════════════════════════════════
  # SECTION 6: DATA MIGRATION (EPIC 18)
  # ══════════════════════════════════════════════════════════════════

  @story-18.1 @smoke
  Scenario: Backup user data before migration
    Given user has existing Canvas files and data
    When migration process starts
    Then complete backup is created:
      | backup_item       | location                    |
      | Canvas files      | .canvas-backup/files/       |
      | Review data       | .canvas-backup/review.db    |
      | Knowledge graph   | .canvas-backup/graphiti/    |
    And backup is timestamped
    And backup integrity is verified

  @story-18.1
  Scenario: Verify backup integrity
    Given backup was created
    When integrity verification runs
    Then file checksums are validated
    And all files are readable
    And verification report is generated

  @story-18.2
  Scenario: Migrate from CLI to Plugin architecture
    Given CLI system has data in vault
    When migration wizard is started
    Then data is converted to new format:
      | source                | destination              |
      | canvas_utils data     | LangGraph state         |
      | review.db             | Neo4j + SQLite          |
      | Local embeddings      | LanceDB                 |
    And migration progress is displayed
    And rollback point is created

  @story-18.2 @error-handling
  Scenario: Migration failure with rollback
    Given migration is in progress
    And error occurs at step 3 of 5
    When migration fails
    Then automatic rollback is triggered
    And system is restored to pre-migration state
    And error report is generated
    And user is notified with next steps

  # ══════════════════════════════════════════════════════════════════
  # SECTION 7: SYSTEM-LEVEL ROLLBACK
  # ══════════════════════════════════════════════════════════════════

  @story-18.3
  Scenario: Rollback entire system to checkpoint
    Given system checkpoint was created 1 hour ago
    And severe data corruption detected
    When admin triggers system rollback
    Then all services are stopped
    And data is restored from checkpoint
    And services are restarted
    And system health is verified

  @story-18.3 @ui
  Scenario: System rollback confirmation
    Given admin requests system rollback
    When confirmation is required
    Then modal shows:
      | warning | 此操作将回滚所有用户数据到1小时前 |
      | impact  | 所有1小时内的更改将丢失          |
      | input   | 请输入 'CONFIRM' 确认            |

  # ══════════════════════════════════════════════════════════════════
  # SECTION 8: ROLLBACK TRIGGERS (AUTOMATIC)
  # ══════════════════════════════════════════════════════════════════

  @story-17.6
  Scenario: Auto-rollback on data corruption detection
    Given Canvas file has been modified
    And JSON validation fails (invalid structure)
    When corruption is detected on file read
    Then auto-rollback is triggered
    And most recent valid snapshot is restored
    And Notice warns "检测到数据损坏，已自动恢复"

  @story-17.6
  Scenario: Auto-rollback on performance degradation
    Given system monitors performance metrics
    And performance drops >50% after operation
    When degradation is detected
    Then investigation is triggered
    And if operation caused degradation, auto-rollback offered
    And performance is re-measured after rollback

  # ══════════════════════════════════════════════════════════════════
  # SECTION 9: RECOVERY FROM CRASHES
  # ══════════════════════════════════════════════════════════════════

  @story-17.7
  Scenario: Recover from Obsidian crash
    Given Obsidian crashed during agent operation
    And write was partially completed
    When Obsidian restarts and plugin loads
    Then plugin detects incomplete operation
    And offers recovery options:
      | option | action                     |
      | 1      | 完成未完成的操作           |
      | 2      | 回滚到操作前               |
      | 3      | 保持当前状态               |

  @story-17.7
  Scenario: Recover from Neo4j service crash
    Given Neo4j service crashed
    And Graphiti operations were pending
    When Neo4j service restarts
    Then pending operations are replayed
    And data consistency is verified
    And any conflicts are logged for review

  # ══════════════════════════════════════════════════════════════════
  # SECTION 10: AUDIT TRAIL
  # ══════════════════════════════════════════════════════════════════

  @story-17.8
  Scenario: Audit trail for rollback operations
    Given rollback was performed
    When checking audit log
    Then log contains:
      | field           | value                    |
      | action          | rollback                 |
      | user            | user_id                  |
      | timestamp       | ISO 8601                 |
      | steps_rolled    | 5                        |
      | canvas_affected | 离散数学.canvas          |
      | reason          | user_requested           |

  @story-17.8
  Scenario: Export rollback history
    Given user needs rollback history for debugging
    When user exports history
    Then JSON file is generated with:
      | content           |
      | All operations    |
      | All rollbacks     |
      | Timestamps        |
      | Canvas affected   |
