# specs/behavior/verification-canvas.feature
# Generated by: PM Agent *create-behavior-spec
# Date: 2025-11-25
# Related: Epic 4, Epic 15, Story 4.2

@epic-4 @epic-15 @priority-high
Feature: Verification Canvas - Paperless Review System
  As a learner
  I want to generate verification canvases for paperless review
  So that I can test my understanding and identify knowledge gaps

  # Common setup for all scenarios
  Background:
    Given the Canvas Learning System is initialized
    And the user has an original Canvas file loaded

  # ═══════════════════════════════════════════════════════════
  # HAPPY PATH SCENARIOS
  # ═══════════════════════════════════════════════════════════

  @story-4.1 @smoke
  Scenario: Successfully generate verification canvas
    Given the original Canvas "离散数学.canvas" has 5 red nodes and 3 purple nodes
    And the nodes contain learning content about "逆否命题" and "集合论"
    When the user requests to generate a verification canvas
    Then a new Canvas file "离散数学-检验白板-20251125.canvas" is created
    And the verification canvas contains 8 question nodes
    And each question node has a corresponding yellow answer node
    And the question nodes reference their source nodes via "sourceNodeId"

  @story-4.2 @smoke
  Scenario: Get verification canvas progress
    Given a verification canvas "离散数学-检验白板-20251125.canvas" exists
    And the canvas has 8 question nodes
    And 5 answer nodes have been scored (3 green, 2 purple)
    When the user requests the verification progress
    Then the system returns progress summary:
      | metric              | value |
      | total_questions     | 8     |
      | answered            | 5     |
      | passed_green        | 3     |
      | passed_purple       | 2     |
      | remaining           | 3     |
      | completion_rate     | 62.5% |

  @story-15.1 @smoke
  Scenario: Sync scores back to original canvas
    Given a verification canvas "离散数学-检验白板-20251125.canvas" has scored nodes
    And the original canvas "离散数学.canvas" exists
    And answer node "answer-001" (sourceNodeId: "node-red-001") scored 92 (green)
    And answer node "answer-002" (sourceNodeId: "node-purple-001") scored 75 (purple)
    When the user requests to sync scores to original canvas
    Then original node "node-red-001" color updates to green
    And original node "node-purple-001" remains purple
    And sync result shows "2 nodes synced, 0 conflicts"

  @story-4.2
  Scenario: Answer verification question and get scored
    Given a verification canvas with question node "q-001"
    And question node "q-001" has a yellow answer node "answer-001"
    And the user has written their response in "answer-001"
    When the user invokes scoring-agent on "answer-001"
    Then the system evaluates on 4 dimensions (accuracy, imagery, completeness, originality)
    And the total score is calculated
    And the answer node color updates based on score threshold
    And the score is recorded in review history

  # ═══════════════════════════════════════════════════════════
  # EDGE CASES AND ERROR HANDLING
  # ═══════════════════════════════════════════════════════════

  @story-4.1 @error
  Scenario: Generate verification canvas with no eligible nodes
    Given the original Canvas "已掌握.canvas" has only green nodes
    And there are no red or purple nodes requiring review
    When the user requests to generate a verification canvas
    Then the system returns message "无需复习的节点 - 所有概念已掌握"
    And no verification canvas is created

  @story-4.2 @error
  Scenario: Query progress for non-existent verification canvas
    Given no verification canvas named "不存在.canvas" exists
    When the user requests the verification progress for "不存在.canvas"
    Then the system returns HTTP 404 error
    And error message is "Verification canvas not found"

  @story-15.1 @boundary
  Scenario: Sync with mismatched nodes
    Given a verification canvas with answer node "answer-001" (sourceNodeId: "deleted-node")
    And the original canvas no longer contains "deleted-node"
    When the user requests to sync scores to original canvas
    Then the system returns partial sync result
    And warning shows "1 node could not be synced: source node deleted"
    And other valid nodes are synced successfully

  @story-14.5
  Scenario: Generate verification canvas with historical review data
    Given the original Canvas "离散数学.canvas" has previous review records
    And historical data shows node "node-001" scored 45 (weak), node "node-002" scored 88 (strong)
    And the user selects "针对性复习" (targeted review) mode
    When the user requests to generate a verification canvas
    Then the verification canvas prioritizes weak nodes
    And node "node-001" has 3 verification questions
    And node "node-002" has 1 verification question
    And the canvas includes "历史薄弱点优先" indicator

  # ═══════════════════════════════════════════════════════════
  # PARAMETERIZED SCENARIOS
  # ═══════════════════════════════════════════════════════════

  @story-4.2
  Scenario Outline: Answer score determines node color transition
    Given a yellow answer node with user response
    When the scoring-agent evaluates and returns total score <score>
    Then the answer node color should change to "<color>"
    And the review status should be "<status>"

    Examples:
      | score | color  | status     |
      | 95    | green  | passed     |
      | 85    | green  | passed     |
      | 80    | green  | passed     |
      | 75    | purple | needs_work |
      | 60    | purple | needs_work |
      | 50    | red    | failed     |
      | 30    | red    | failed     |

  @story-15.1
  Scenario Outline: Sync behavior based on score comparison
    Given original node has color "<original_color>"
    And verification answer scored "<new_score>" (new color: <new_color>)
    When sync is requested
    Then original node color should be "<result_color>"
    And sync action should be "<action>"

    Examples:
      | original_color | new_score | new_color | result_color | action              |
      | red            | 90        | green     | green        | upgraded            |
      | red            | 70        | purple    | purple       | partial_improvement |
      | purple         | 85        | green     | green        | upgraded            |
      | purple         | 65        | purple    | purple       | no_change           |
      | green          | 95        | green     | green        | confirmed           |
