#!/usr/bin/env python3
"""CARD-G5-6c 负控：八条回退变异，各须让**预先声明的那一组门**变红。

判据（逐条硬门，缺一即 FAIL）：
  1. 实际 FAILED 集合必须**逐个等于**预先声明的 `expected` 集合。
     ——「某处有失败」不算；多红一门（波及面比想的大）与少红一门（那条防线
     没被测到）同样是 FAIL。期望集合由修改前的推理写死在本文件里，不从输出
     反抄（自抄期望值等于让门给自己签字，见 reference_gate_design_pitfalls）。
  2. **必须 rc == 1**（pytest：跑完了且有测试失败）。rc=5（no tests collected）
     是没跑；rc=2/3/4（用法错误/内部异常）是 runner 自己坏了 —— 都不算「抓到了」。
     FAILED 与 ERROR 两类都计入失败集合。
  3. 每条变异串行执行，跑完立刻还原并**逐字节**比对 sha256
     （reference_mutation_script_serial_only + temp_file_swap_needs_exit_trap）。
  4. ⛔ 为什么不是「恰好一门红」：护栏是纵深的，一条防线常被多道门覆盖，
     反过来单层回退也可能被另一条防线兜住而**一门都不红**。后者是真正的危险
     （那条防线没有门在测），所以裁判必须是「集合相等」而不是「至少一门红」
     或「恰好一门红」。相应地，门必须断言 `uncertain_reason` **属于哪条信号**
     ——否则兜底接住材料后 verdict 断言照样绿，变异就测不到目标层。

⛔ 本脚本原地修改 checkout 源码，必须串行、必须独占运行。
"""

from __future__ import annotations

import hashlib
import pathlib
import signal
import subprocess
import sys

ROOT = pathlib.Path(sys.argv[1]).resolve()
SRC = ROOT / "canvas-vault/.claude/skills/clear-inbox/scripts/inbox_preview.py"
TESTFILE = "tests/skills/test_g5_6_clear_inbox.py"
BACKEND = ROOT / "backend"
PYTEST = [str(BACKEND / ".venv/bin/pytest"), TESTFILE, "-q", "-p", "no:cacheprovider"]

G_NBSP = "test_nbsp_after_hash_is_not_an_atx_heading"
G_NBSP_CONSUMERS = "test_nbsp_heading_narrowing_locks_each_consumer"
G_LONG = "test_long_model_name_and_punctuated_generation_claims_are_undigested"
G_GENKEY = "test_model_version_generation_claim_is_undigested_signal"
G_DOI = "test_doi_source_identifier_blocks_deletion"
G_DUPKEY = "test_duplicate_frontmatter_key_does_not_mask_source"
G_UNKNOWN = "test_any_nonempty_frontmatter_value_blocks_confident_deletion"
G_UNPARSED = "test_unparsed_source_with_duplicate_body_is_not_suggested_for_deletion"
G_COMMENT = "test_source_inside_closed_html_comment_blocks_deletion"
G_COMMENT2 = "test_unclosed_html_comment_never_suggested_for_deletion"
G_INVIS = "test_invisible_chars_are_detected_by_category_not_enumeration"
G_HEADCONTENT = "test_heading_with_text_counts_as_substantive_content"
G_R7 = "test_fence_info_string_and_semantic_operators_are_not_skeleton"
G_KEYNAME = "test_information_in_key_name_blocks_deletion"
G_ATX = "test_atx_heading_text_is_parsed_structurally"
G_SEMWS = "test_c4_comparison_keeps_semantic_whitespace"
G_FNAME = "test_source_identifier_in_filename_blocks_deletion"
G_ASCIIWS = "test_ascii_whitespace_semantics_are_not_unicode"
G_PREFIX = "test_prefixed_url_filename_is_a_source_signal"
G_ZW = "test_zero_width_split_marker_still_reads_as_ai_suspect"

# ── (名字, 期望 FAILED 集合, [(old, new), ...]) ──
MUTATIONS: list[tuple[str, set[str], list[tuple[str, str]]]] = [
    (
        "M-NBSP       井号后分隔回退到 Unicode \\s",
        {G_NBSP, G_NBSP_CONSUMERS},
        [
            (
                r'_HEADING_RE = re.compile(r"^ {0,3}#{1,6}(?:[ \t]|$)")',
                r'_HEADING_RE = re.compile(r"^ {0,3}#{1,6}(?:\s|$)")',
            )
        ],
    ),
    (
        "M-CLAIMBOUND 生成骨架加回长度上界 + 字面空格",
        {G_LONG},
        [
            (
                r'_GEN_CLAIM_CN_RE = re.compile(r"由[^。；！？\n]*?生成")',
                r'_GEN_CLAIM_CN_RE = re.compile(r"由[^。；！？\n]{1,40}?生成")',
            ),
            (
                r'_GEN_CLAIM_EN_RE = re.compile(r"generated by(?![^\W_])[\W_]*[^\W_]")',
                r'_GEN_CLAIM_EN_RE = re.compile(r"generated by \S")',
            ),
        ],
    ),
    (
        # ⚠️ 期望是 {G_ZW} 而不是 {G_LONG}：首轮把它写成 G_LONG，实跑「少红」——
        # 零宽在 `Generated by<ZWSP>GPT-4` 形态下已被骨架的非词字符段吃掉，
        # 这一层在那里**不承重**。真正承重的是零宽切断标记表项时的 raw_ai_marker。
        # 期望集合被实测证伪 → 改的是期望，也改了实现文档，不是把判据放宽。
        # ⚠️ 期望含 G_INVIS：新加的不可见字符门端到端半边断言 reason 归属
        # 「生成断言结构」，回退双变体后词内零宽不还原、骨架认不出，它同样红。
        # 这是本 runner 第二次抓到我把期望写窄 —— 记全真实覆盖面，判据不放宽。
        "M-ZEROWIDTH  护栏归一退回旧归一（不剥零宽）",
        {G_ZW, G_INVIS},
        [
            # ⛔ 两个调用点都退 —— 只退一个会被另一个兜住，变异测不出这一层
            # （reference_mutation_must_disable_all_layers）。
            # round-3 起零宽走 `_guard_variants` 双变体（换空格 + 直接删）。
            # 回退成只有换空格那一版 = round-2 行为，词内插入重新失效。
            (
                "    return (\n"
                '        _norm_ai_line(_strip_invisible(ln, " ")),\n'
                '        _norm_ai_line(_strip_invisible(ln, "")),\n'
                "    )\n",
                '    return (_norm_ai_line(_strip_invisible(ln, " ")),)\n',
            ),
        ],
    ),
    (
        "M-GENSIGNAL  生成断言结构 + 生成器键两层全回退",
        {G_LONG, G_GENKEY, G_INVIS},
        [
            ("    gen_claim = find_generation_claim(text)\n", "    gen_claim = None\n"),
            (
                "    generator_pairs = [\n"
                "        (k, v) for k, v in fm_pairs if _norm_fm_key(k) in _GENERATOR_DECL_KEYS\n"
                "    ]\n",
                "    generator_pairs = []\n",
            ),
        ],
    ),
    (
        "M-SRCALIAS   来源键名归一退回字面小写 source",
        {G_DOI},
        [
            (
                "    source_alias_pairs = [\n"
                "        (k, v) for k, v in fm_pairs if _norm_fm_key(k) in _SOURCE_DECL_KEYS\n"
                "    ]",
                '    source_alias_pairs = [(k, v) for k, v in fm_pairs if k == "source"]',
            )
        ],
    ),
    (
        "M-DOIVAL     DOI/ISBN 值形态信号回退",
        {G_DOI, G_DUPKEY},
        [
            (
                "    doi_bearing_pairs = [\n"
                "        (k, v)\n"
                "        for k, v in fm_pairs\n"
                "        if _looks_like_doi_value(v) or _looks_like_isbn_value(v)\n"
                "    ]\n",
                "    doi_bearing_pairs = []\n",
            )
        ],
    ),
    (
        "M-PAIRS      护栏扫描面退回折叠后的 map（重复键遮蔽复现）",
        {G_DUPKEY},
        [
            (
                "    fm_pairs = frontmatter_pairs(fm_lines)\n",
                "    fm_pairs = list(fm.items())\n",
            )
        ],
    ),
    (
        # round-3 起白名单整个取消（放行键名而信息在值里，被审查打穿），
        # 兜底改为「任何非空值」；变异锚点随之改变。
        # ⚠️ 期望里必须带上 G_UNPARSED：round-3 给那道门加了「带非空元数据的重复件
        # 落 C6」这条断言，它同样靠⑨承重。首跑把期望写成只有 G_UNKNOWN，实测**多红**
        # 一门 —— 说明我对波及面的理解不准。改的是期望（把真实覆盖面记全），
        # 不是放宽判据；判据仍是集合相等。
        "M-FALLBACK   兜底信号⑨回退（方向退回 fail-open）",
        {G_UNKNOWN, G_UNPARSED},
        [
            (
                "    unknown_value_pairs = [(k, v) for k, v in fm_pairs if v] + [\n",
                "    unknown_value_pairs = [] + [\n",
            )
        ],
    ),
    (
        # round-3 BLOCKER：不可见字符退回六码点有限表（U+2063 等 9 个同族重新穿透）
        "M-INVISENUM  不可见字符判定退回有限枚举",
        {G_INVIS},
        [
            (
                "            unicodedata.category(c) in _INVISIBLE_CATEGORIES\n"
                '            or (c.isspace() and c not in " \\t")\n',
                '            c in "\\u200b\\u200c\\u200d\\u2060\\ufeff\\u00ad"\n'
                "            or False\n",
            )
        ],
    ),
    (
        # round-3 HIGH：闭合注释信号⑩回退（唯一来源写在注释里的文件重新被删）
        # ⚠️ 期望含 G_R7：第七轮把围栏 info string 也并进了信号⑩，那道门的
        # info 反例同样靠它承重。这是本 runner 第四次抓到我把期望写窄 ——
        # 每次给信号扩覆盖面，都要回头问一遍「哪些门现在也依赖它了」。
        "M-COMMENT    闭合注释未消化信号⑩回退",
        {G_COMMENT, G_COMMENT2, G_R7},
        [
            (
                "    commented_out = [ln for ln in stripped_comments if ln.strip()] + fm_comment_lines\n",
                "    commented_out = []\n",
            )
        ],
    ),
    (
        # 用户裁决（2026-09-02）：标题里写了字算实质正文。回退后
        # 「只写了标题的笔记」与「隐形字符伪装的标题」重新被确定删除。
        "M-HEADING    标题不算实质正文（回退用户裁决）",
        # ⚠️ 期望含 G_ATX：第九轮新加的 ATX 门端到端半边同样依赖「标题里写了字算
        # 实质正文」这条裁决。这是 runner 第五次抓到我把期望写窄 —— 每次给判据扩
        # 覆盖面，都要回头问一遍「哪些门现在也依赖它了」。
        # ⚠️ 再加 G_ASCIIWS：第十轮的 ASCII 空白门端到端半边也依赖标题裁决。
        {G_HEADCONTENT, G_ATX, G_ASCIIWS},
        [
            (
                "            if _atx_heading_text(ln):\n                return True\n",
                "            if False:\n                return True\n",
            )
        ],
    ),
    (
        # 第七轮 HIGH：结构行判定退回「出现过结构字符就算结构」
        # ⚠️ 期望含 G_ATX：第九轮的 ATX 门里 `#######` 那条断言同样走结构行判定。
        # runner 第六次抓到期望写窄 —— 这条判据被两道门共同覆盖，是真实覆盖面。
        "M-STRUCT     结构行判定退回字符集匹配",
        {G_R7, G_ATX},
        [
            (
                '    if ch == "#":\n',
                "    if True:\n        return True\n    if False:\n",
            )
        ],
    ),
    (
        # 第八轮 HIGH：兜底只看值，信息写进键名就穿透
        "M-KEYNAME    兜底信号⑨ 退回只看值",
        {G_KEYNAME},
        [
            (
                '        (k, "（值为空，信息在键名里）")\n'
                "        for k, v in fm_pairs\n"
                "        if not v and _norm_fm_key(k) not in _KNOWN_FM_KEYS\n",
                '        (k, "x")\n        for k, v in fm_pairs\n        if False\n',
            )
        ],
    ),
    (
        # 第九轮 HIGH：ATX 标题文字改回字符集剥离
        "M-ATX        标题文字解析退回 lstrip 剥井号",
        {G_ATX},
        [
            (
                "            if _atx_heading_text(ln):\n",
                '            if ln.lstrip(" \\t#").strip():\n',
            )
        ],
    ),
    (
        # 第九轮 HIGH：C4 比较形态退回有损投影（抹掉硬换行/段落边界/围栏空白）
        "M-SEMWS      dup_body 退回无条件 rstrip + 丢空行",
        {G_SEMWS},
        [
            (
                "        if is_code:\n",
                "        if False:\n",
            ),
            (
                '            parts.append("")  # 段落边界是语义，不能丢\n',
                "            continue\n",
            ),
        ],
    ),
    (
        # 第九轮 HIGH：护栏不看文件名
        # ⚠️ 期望含 G_PREFIX：第十轮的带前缀 URL 文件名门同样靠这条信号。
        "M-FNAME      文件名来源信号回退",
        {G_FNAME, G_PREFIX},
        [("    name_signal = next(\n", "    name_signal = None\n    _unused = (\n")],
    ),
    (
        # 第十轮 HIGH：dup_body 的空白判定退回 Unicode 口径
        # ⚠️ 期望只有 G_ASCIIWS：承重断言（「NBSP 版会与无硬换行的正本相撞」）
        # 写在那道门里，G_SEMWS 门里的断言在变异后**两边仍然不等**，测不到这一层。
        # 首跑写成 {G_ASCIIWS, G_SEMWS} → 实测「少红」，手工复现证明红的是前者。
        # ⛔ 写断言时要问：**变异之后，这条断言的两边会不会仍然不等？**
        "M-ASCIIWS    dup_body 空白判定退回 Unicode",
        {G_ASCIIWS},
        [
            ('        t = ln.rstrip(" \\t")\n', "        t = ln.rstrip()\n"),
        ],
    ),
    (
        # 第十轮 HIGH：ATX closing 判定退回 Unicode 空白
        "M-ATXWS      ATX closing 分隔符退回 Unicode",
        {G_ASCIIWS},
        [
            (
                '    closing = re.search(r"(?:^|[ \\t])(#+)$", rest)\n',
                '    closing = re.search(r"(?:^|\\s)(#+)$", rest)\n',
            ),
        ],
    ),
    (
        # 第十轮 HIGH：文件名 URL 判定退回锚定正则
        "M-FNAMEURL   文件名 URL 判定退回锚定匹配",
        {G_PREFIX},
        [
            (
                '                "http://" in probe.casefold()\n'
                '                or "https://" in probe.casefold()\n',
                "                _URL_RE.match(probe)\n",
            ),
        ],
    ),
]


def sha(p: pathlib.Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def run_suite() -> tuple[int, set[str], str]:
    r = subprocess.run(
        PYTEST,
        cwd=BACKEND,
        capture_output=True,
        text=True,
        env={
            "PATH": "/usr/bin:/bin",
            "PYTHONDONTWRITEBYTECODE": "1",
            "HOME": str(pathlib.Path.home()),
            "LC_ALL": "C.UTF-8",
        },
    )
    out = r.stdout + r.stderr
    # ⛔ round-3 审查 MEDIUM：只认 `FAILED ` 会漏掉 `ERROR `（collection error /
    # fixture 抛异常都走 ERROR）。变异若把模块改到 import 失败，套件全是 ERROR、
    # 一条 FAILED 都没有，集合比对会判成「少红」还是「相等」全看运气 —— 两种都
    # 不是我们要判的东西。两类一起收，才谈得上「实际失败集合」。
    failed = {
        ln.split("::")[1].split(" ")[0].strip()
        for ln in out.splitlines()
        if (ln.startswith("FAILED ") or ln.startswith("ERROR ")) and "::" in ln
    }
    tail = [
        ln
        for ln in out.splitlines()
        if "passed" in ln or "failed" in ln or "error" in ln
    ]
    return r.returncode, failed, (tail[-1] if tail else "<no summary>")


original = SRC.read_bytes()
base_sha = sha(SRC)
print(f"源码基线 sha256 = {base_sha}\n", flush=True)


def _restore_on_signal(signum, _frame):
    """⛔ 真事故（2026-09-02）：本脚本被 2 分钟超时 SIGTERM 杀掉时，`finally`
    **没有执行** —— Python 默认信号处理器直接终止进程，不抛异常，源码被留在
    M-PAIRS 变异态。原地改源码的脚本必须显式注册处理器才谈得上「一定还原」。
    （能安全恢复靠的是上面那行基线 sha 已经打印出来 —— 有它，还原才有可验证
    判据；没有它只能凭记忆猜该改回什么。）"""
    SRC.write_bytes(original)
    print(f"\n⛔ 收到信号 {signum}，已还原源码 sha256={sha(SRC)}", flush=True)
    sys.exit(128 + signum)


for _sig in (signal.SIGTERM, signal.SIGINT, signal.SIGHUP):
    signal.signal(_sig, _restore_on_signal)

results: list[tuple[str, bool]] = []
try:
    for name, expected, layers in MUTATIONS:
        text = original.decode("utf-8")
        for old, new in layers:
            n = text.count(old)
            if n != 1:
                raise SystemExit(f"[{name}] 变异锚点出现 {n} 次（须 1）：{old!r}")
            text = text.replace(old, new)
        SRC.write_text(text, encoding="utf-8")
        if sha(SRC) == base_sha:
            raise SystemExit(f"[{name}] 变异没有真的改到字节")

        rc, failed, summary = run_suite()
        SRC.write_bytes(original)
        restored = sha(SRC)

        # ⛔ round-3 审查 MEDIUM：`rc not in (0, 5)` 太松 —— rc=2（内部错误/用法
        # 错误）、rc=3（内部异常）、rc=4（用法错误）都会被当成「红了」。真正表示
        # 「跑完了且有测试失败」的只有 rc=1。
        ok = failed == expected and rc == 1 and restored == base_sha
        results.append((name, ok))
        print(f"{'✅' if ok else '❌'} {name}")
        print(f"   期望红: {sorted(expected)}")
        print(f"   实际红: {sorted(failed)}")
        if failed - expected:
            print(f"   ⚠️ 多红（波及面比预期大）: {sorted(failed - expected)}")
        if expected - failed:
            print(f"   ⛔ 少红（该防线没有门在测）: {sorted(expected - failed)}")
        print(
            f"   rc={rc} | {summary} | 还原 sha "
            f"{'一致' if restored == base_sha else '⛔不一致'}\n"
        )
finally:
    SRC.write_bytes(original)
    final = sha(SRC)
    print(
        f"finally 还原后 sha256 = {final} "
        f"({'与基线逐字节相同' if final == base_sha else '⛔ 漂移'})"
    )

allok = (
    all(ok for _, ok in results)
    and sha(SRC) == base_sha
    and len(results) == len(MUTATIONS)
)
print("\n" + "=" * 70)
print(
    f"G56C_NEGATIVE_CONTROL: {'PASS' if allok else 'FAIL'} "
    f"（{sum(1 for _, ok in results if ok)}/{len(MUTATIONS)} 变异的实际失败集合等于预先声明集合）"
)
sys.exit(0 if allok else 1)
