#!/usr/bin/env python3
"""CARD-G5-6c 负控：八条回退变异，各须让**预先声明的那一组门**变红。

判据（逐条硬门，缺一即 FAIL）：
  1. 实际 FAILED 集合必须**逐个等于**预先声明的 `expected` 集合。
     ——「某处有失败」不算；多红一门（波及面比想的大）与少红一门（那条防线
     没被测到）同样是 FAIL。期望集合由修改前的推理写死在本文件里，不从输出
     反抄（自抄期望值等于让门给自己签字，见 reference_gate_design_pitfalls）。
  2. rc=5（no tests collected）不算红 —— 那是没跑，不是抓到了。
  3. 每条变异串行执行，跑完立刻还原并**逐字节**比对 sha256
     （reference_mutation_script_serial_only + temp_file_swap_needs_exit_trap）。
  4. ⛔ 为什么不是「恰好一门红」：护栏是纵深的，一条防线常被多道门覆盖，
     反过来单层回退也可能被另一条防线兜住而**一门都不红**。后者是真正的危险
     （那条防线没有门在测），所以裁判必须是「集合相等」而不是「至少一门红」
     或「恰好一门红」。相应地，门必须断言 `uncertain_reason` **属于哪条信号**
     ——否则兜底接住材料后 verdict 断言照样绿，变异就测不到目标层。

⛔ 本脚本原地修改 checkout 源码，必须串行、必须独占运行。
"""

from __future__ import annotations

import hashlib
import pathlib
import signal
import subprocess
import sys

ROOT = pathlib.Path(sys.argv[1]).resolve()
SRC = ROOT / "canvas-vault/.claude/skills/clear-inbox/scripts/inbox_preview.py"
TESTFILE = "tests/skills/test_g5_6_clear_inbox.py"
BACKEND = ROOT / "backend"
PYTEST = [str(BACKEND / ".venv/bin/pytest"), TESTFILE, "-q", "-p", "no:cacheprovider"]

G_NBSP = "test_nbsp_after_hash_is_not_an_atx_heading"
G_NBSP_CONSUMERS = "test_nbsp_heading_narrowing_locks_each_consumer"
G_LONG = "test_long_model_name_and_punctuated_generation_claims_are_undigested"
G_GENKEY = "test_model_version_generation_claim_is_undigested_signal"
G_DOI = "test_doi_source_identifier_blocks_deletion"
G_DUPKEY = "test_duplicate_frontmatter_key_does_not_mask_source"
G_UNKNOWN = "test_unknown_nonempty_frontmatter_value_blocks_c3"
G_ZW = "test_zero_width_split_marker_still_reads_as_ai_suspect"

# ── (名字, 期望 FAILED 集合, [(old, new), ...]) ──
MUTATIONS: list[tuple[str, set[str], list[tuple[str, str]]]] = [
    (
        "M-NBSP       井号后分隔回退到 Unicode \\s",
        {G_NBSP, G_NBSP_CONSUMERS},
        [
            (
                r'_HEADING_RE = re.compile(r"^ {0,3}#{1,6}(?:[ \t]|$)")',
                r'_HEADING_RE = re.compile(r"^ {0,3}#{1,6}(?:\s|$)")',
            )
        ],
    ),
    (
        "M-CLAIMBOUND 生成骨架加回长度上界 + 字面空格",
        {G_LONG},
        [
            (
                r'_GEN_CLAIM_CN_RE = re.compile(r"由[^。；！？\n]*?生成")',
                r'_GEN_CLAIM_CN_RE = re.compile(r"由[^。；！？\n]{1,40}?生成")',
            ),
            (
                r'_GEN_CLAIM_EN_RE = re.compile(r"generated by\b\W*\w")',
                r'_GEN_CLAIM_EN_RE = re.compile(r"generated by \S")',
            ),
        ],
    ),
    (
        # ⚠️ 期望是 {G_ZW} 而不是 {G_LONG}：首轮把它写成 G_LONG，实跑「少红」——
        # 零宽在 `Generated by<ZWSP>GPT-4` 形态下已被骨架的非词字符段吃掉，
        # 这一层在那里**不承重**。真正承重的是零宽切断标记表项时的 raw_ai_marker。
        # 期望集合被实测证伪 → 改的是期望，也改了实现文档，不是把判据放宽。
        "M-ZEROWIDTH  护栏归一退回旧归一（不剥零宽）",
        {G_ZW},
        [
            # ⛔ 两个调用点都退 —— 只退一个会被另一个兜住，变异测不出这一层
            # （reference_mutation_must_disable_all_layers）。
            (
                "        norm = _norm_guard_line(ln)\n"
                "        for rx in (_GEN_CLAIM_CN_RE, _GEN_CLAIM_EN_RE):\n",
                "        norm = _norm_ai_line(ln)\n"
                "        for rx in (_GEN_CLAIM_CN_RE, _GEN_CLAIM_EN_RE):\n",
            ),
            (
                "        norm = _norm_guard_line(ln)\n"
                "        for nm, orig in zip(_AI_MARKERS_NORM, AI_MARKERS):\n",
                "        norm = _norm_ai_line(ln)\n"
                "        for nm, orig in zip(_AI_MARKERS_NORM, AI_MARKERS):\n",
            ),
        ],
    ),
    (
        "M-GENSIGNAL  生成断言结构 + 生成器键两层全回退",
        {G_LONG, G_GENKEY},
        [
            ("    gen_claim = find_generation_claim(text)\n", "    gen_claim = None\n"),
            (
                "    generator_pairs = [\n"
                "        (k, v) for k, v in fm_pairs if _norm_fm_key(k) in _GENERATOR_DECL_KEYS\n"
                "    ]\n",
                "    generator_pairs = []\n",
            ),
        ],
    ),
    (
        "M-SRCALIAS   来源键名归一退回字面小写 source",
        {G_DOI},
        [
            (
                "    source_alias_pairs = [\n"
                "        (k, v) for k, v in fm_pairs if _norm_fm_key(k) in _SOURCE_DECL_KEYS\n"
                "    ]",
                '    source_alias_pairs = [(k, v) for k, v in fm_pairs if k == "source"]',
            )
        ],
    ),
    (
        "M-DOIVAL     DOI 值形态信号回退",
        {G_DOI, G_DUPKEY},
        [
            (
                "    doi_bearing_pairs = [(k, v) for k, v in fm_pairs if _looks_like_doi_value(v)]\n",
                "    doi_bearing_pairs = []\n",
            )
        ],
    ),
    (
        "M-PAIRS      护栏扫描面退回折叠后的 map（重复键遮蔽复现）",
        {G_DUPKEY},
        [
            (
                "    fm_pairs = frontmatter_pairs(fm_lines)\n",
                "    fm_pairs = list(fm.items())\n",
            )
        ],
    ),
    (
        "M-WHITELIST  白名单兜底信号回退（方向退回 fail-open）",
        {G_UNKNOWN},
        [
            (
                "    unknown_value_pairs = [\n"
                "        (k, v) for k, v in fm_pairs if v and _norm_fm_key(k) not in _HARMLESS_FM_KEYS\n"
                "    ]\n",
                "    unknown_value_pairs = []\n",
            )
        ],
    ),
]


def sha(p: pathlib.Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def run_suite() -> tuple[int, set[str], str]:
    r = subprocess.run(
        PYTEST,
        cwd=BACKEND,
        capture_output=True,
        text=True,
        env={
            "PATH": "/usr/bin:/bin",
            "PYTHONDONTWRITEBYTECODE": "1",
            "HOME": str(pathlib.Path.home()),
            "LC_ALL": "C.UTF-8",
        },
    )
    out = r.stdout + r.stderr
    failed = {
        ln.split("::")[1].split(" ")[0].strip()
        for ln in out.splitlines()
        if ln.startswith("FAILED ") and "::" in ln
    }
    tail = [
        ln
        for ln in out.splitlines()
        if "passed" in ln or "failed" in ln or "error" in ln
    ]
    return r.returncode, failed, (tail[-1] if tail else "<no summary>")


original = SRC.read_bytes()
base_sha = sha(SRC)
print(f"源码基线 sha256 = {base_sha}\n", flush=True)


def _restore_on_signal(signum, _frame):
    """⛔ 真事故（2026-09-02）：本脚本被 2 分钟超时 SIGTERM 杀掉时，`finally`
    **没有执行** —— Python 默认信号处理器直接终止进程，不抛异常，源码被留在
    M-PAIRS 变异态。原地改源码的脚本必须显式注册处理器才谈得上「一定还原」。
    （能安全恢复靠的是上面那行基线 sha 已经打印出来 —— 有它，还原才有可验证
    判据；没有它只能凭记忆猜该改回什么。）"""
    SRC.write_bytes(original)
    print(f"\n⛔ 收到信号 {signum}，已还原源码 sha256={sha(SRC)}", flush=True)
    sys.exit(128 + signum)


for _sig in (signal.SIGTERM, signal.SIGINT, signal.SIGHUP):
    signal.signal(_sig, _restore_on_signal)

results: list[tuple[str, bool]] = []
try:
    for name, expected, layers in MUTATIONS:
        text = original.decode("utf-8")
        for old, new in layers:
            n = text.count(old)
            if n != 1:
                raise SystemExit(f"[{name}] 变异锚点出现 {n} 次（须 1）：{old!r}")
            text = text.replace(old, new)
        SRC.write_text(text, encoding="utf-8")
        if sha(SRC) == base_sha:
            raise SystemExit(f"[{name}] 变异没有真的改到字节")

        rc, failed, summary = run_suite()
        SRC.write_bytes(original)
        restored = sha(SRC)

        ok = failed == expected and rc not in (0, 5) and restored == base_sha
        results.append((name, ok))
        print(f"{'✅' if ok else '❌'} {name}")
        print(f"   期望红: {sorted(expected)}")
        print(f"   实际红: {sorted(failed)}")
        if failed - expected:
            print(f"   ⚠️ 多红（波及面比预期大）: {sorted(failed - expected)}")
        if expected - failed:
            print(f"   ⛔ 少红（该防线没有门在测）: {sorted(expected - failed)}")
        print(
            f"   rc={rc} | {summary} | 还原 sha "
            f"{'一致' if restored == base_sha else '⛔不一致'}\n"
        )
finally:
    SRC.write_bytes(original)
    final = sha(SRC)
    print(
        f"finally 还原后 sha256 = {final} "
        f"({'与基线逐字节相同' if final == base_sha else '⛔ 漂移'})"
    )

allok = (
    all(ok for _, ok in results)
    and sha(SRC) == base_sha
    and len(results) == len(MUTATIONS)
)
print("\n" + "=" * 70)
print(
    f"G56C_NEGATIVE_CONTROL: {'PASS' if allok else 'FAIL'} "
    f"（{sum(1 for _, ok in results if ok)}/{len(MUTATIONS)} 变异的实际失败集合等于预先声明集合）"
)
sys.exit(0 if allok else 1)
