# Canvas Learning System - Tests for Story 38.4
# Story 38.4: Dual-Write Default Configuration Safety
# Generated by TEA ATDD Workflow, Refactored after Green Phase
"""
Tests for Story 38.4: Dual-Write Default Configuration Safety.

Verifies 3 Acceptance Criteria:
- AC-1: Fresh installation defaults ENABLE_GRAPHITI_JSON_DUAL_WRITE to True
- AC-2: Operator can explicitly disable with warning logs
- AC-3: Missing env var defaults to True

Story Context: docs/implementation-artifacts/story-38.4.md
[Source: docs/stories/EPIC-38-infrastructure-reliability-fixes.md#Story-38.4]
"""

import logging
import os
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

# ═══════════════════════════════════════════════════════════════════════════════
# AC-1: Safe Default (D4: Configuration)
# ═══════════════════════════════════════════════════════════════════════════════


class TestAC1SafeDefault:
    """AC-1: Fresh installation defaults to dual-write DISABLED.

    契约演进（daa9fd37, 2026-03-26）：Phase 2 用 GraphitiEpisodeWorker 取代 JSON
    dual-write 后，config.py 的 ENABLE_GRAPHITI_JSON_DUAL_WRITE 由 default=True 翻为
    ``default=False`` 并标 ``[DEPRECATED]``。因此「safe default」的语义已反转——现在的
    安全默认是**不写** legacy JSON（避免与 worker 双写打架），True 仅作显式 opt-in。
    类名保留 TestAC1SafeDefault 以免打断其它卡的 nodeid 清单。[CARD-RED-C1]
    """

    def test_settings_field_default_is_false(self):
        """
        [P0] Settings.ENABLE_GRAPHITI_JSON_DUAL_WRITE field default must be False.

        Verifies: config.py Field(default=False) at L477-480 ([DEPRECATED], daa9fd37)
        """
        from app.config import Settings

        field_info = Settings.model_fields["ENABLE_GRAPHITI_JSON_DUAL_WRITE"]
        assert field_info.default is False, (
            f"Expected default=False ([DEPRECATED] since daa9fd37), got default={field_info.default}. "
            f"若此处变红，说明生产默认被改回 True——请先确认是产品裁定而非回归"
        )

    def test_lowercase_alias_returns_false_by_default(self):
        """
        [P0] The lowercase property alias also reflects the False default.

        Verifies: config.py enable_graphiti_json_dual_write property
        """
        from app.config import Settings

        env_copy = os.environ.copy()
        env_copy.pop("ENABLE_GRAPHITI_JSON_DUAL_WRITE", None)

        with patch.dict(os.environ, env_copy, clear=True):
            settings = Settings(_env_file=None)
            assert settings.enable_graphiti_json_dual_write is False, (
                "Lowercase property alias should return False by default ([DEPRECATED])"
            )

    @pytest.mark.asyncio
    @pytest.mark.xfail(strict=True, reason="59586af1(2026-03-26 refactor(phase2): delete fake bridge/JSON dual-write code, replaced by GraphitiEpisodeWorker) 删掉了 main.py 里 JSON dual-write 的启动日志（现全文已无 Dual-write 字样），本用例断言的那条日志不再存在；836d0986(2026-03-31) 又删掉了 set_session_validator，使本用例在 patch 入口即 AttributeError。设置项 ENABLE_GRAPHITI_JSON_DUAL_WRITE 本身仍在（config.py:477，canvas_service.py:267/:360 仍消费），故不是整条能力消失，只是「启动期播报」这一面被撤。等价覆盖缺口（GraphitiEpisodeWorker 路径的开关可见性）交接 CARD-STORY-38-4-DUALWRITE-RETIREMENT（台账登记）")
    async def test_startup_log_dual_write_enabled_default(self, caplog):
        """
        [P1] Startup log shows "Dual-write: enabled (default)" when enabled
        via default (no env var set — fresh install scenario).

        Verifies: main.py lifespan() dual-write status log after MemoryService pre-warm
        """
        from app.main import lifespan

        # Remove env var to simulate fresh install (AC-1: no .env customization)
        env_without_dw = {
            k: v
            for k, v in os.environ.items()
            if k != "ENABLE_GRAPHITI_JSON_DUAL_WRITE"
        }

        with (
            patch("app.main.get_default_monitor") as mock_monitor,
            patch("app.main.load_alert_rules_from_yaml", return_value=[]),
            patch("app.main.create_default_dispatcher"),
            patch("app.main.AlertManager") as mock_alert_mgr,
            patch("app.main.get_memory_service", new_callable=AsyncMock),
            patch("app.main.cleanup_memory_service", new_callable=AsyncMock),
            patch("app.main.set_alert_manager"),
            # ⚠️ 本行 patch 的目标已不存在（836d0986 2026-03-31 Epic2 pruning 把
            #    set_session_validator 从 app/main.py 的 import 块删掉，符号现只在
            #    app/api/v1/endpoints/websocket.py:45）。**故意保留**：它在 with 入口就
            #    AttributeError，使本用例在真 lifespan 启动前停住。删掉它实测会让这条
            #    单测跑起整个生产启动流程——加载 BGE-M3、扫 live vault、连 7691
            #    （实测 30.6s / 每条 1 次现网端口连接尝试）。见下方 xfail reason。
            patch("app.main.set_session_validator"),
            patch("app.main.settings") as mock_settings,
            patch.dict(os.environ, env_without_dw, clear=True),
        ):
            mock_monitor.return_value = AsyncMock()
            mock_alert_mgr.return_value = AsyncMock()
            mock_settings.PROJECT_NAME = "test"
            mock_settings.VERSION = "0.0.0"
            mock_settings.DEBUG = False
            mock_settings.LOG_LEVEL = "INFO"
            mock_settings.cors_origins_list = []
            mock_settings.API_V1_PREFIX = "/api/v1"
            mock_settings.ENABLE_GRAPHITI_JSON_DUAL_WRITE = True

            app = MagicMock()
            app.state = MagicMock()

            with caplog.at_level(logging.INFO, logger="app.main"):
                async with lifespan(app):
                    pass

            log_messages = [r.message for r in caplog.records]
            assert any(
                "Dual-write: enabled (default)" in msg for msg in log_messages
            ), (
                f"Expected startup log 'Dual-write: enabled (default)' not found. "
                f"Got logs: {log_messages}"
            )


# ═══════════════════════════════════════════════════════════════════════════════
# AC-2: Explicit Disable (D4: Configuration)
# ═══════════════════════════════════════════════════════════════════════════════


class TestAC2ExplicitDisable:
    """AC-2: Operator can explicitly disable dual-write with warning."""

    def test_explicit_env_false_disables_dual_write(self):
        """
        [P0] Setting ENABLE_GRAPHITI_JSON_DUAL_WRITE=false in env disables it.

        Verifies: Pydantic BaseSettings env override mechanism
        """
        from app.config import Settings

        with patch.dict(os.environ, {"ENABLE_GRAPHITI_JSON_DUAL_WRITE": "false"}):
            settings = Settings(_env_file=None)
            assert settings.ENABLE_GRAPHITI_JSON_DUAL_WRITE is False

    @pytest.mark.asyncio
    @pytest.mark.xfail(strict=True, reason="59586af1(2026-03-26 refactor(phase2): delete fake bridge/JSON dual-write code, replaced by GraphitiEpisodeWorker) 删掉了 main.py 里 JSON dual-write 的启动日志（现全文已无 Dual-write 字样），本用例断言的那条日志不再存在；836d0986(2026-03-31) 又删掉了 set_session_validator，使本用例在 patch 入口即 AttributeError。设置项 ENABLE_GRAPHITI_JSON_DUAL_WRITE 本身仍在（config.py:477，canvas_service.py:267/:360 仍消费），故不是整条能力消失，只是「启动期播报」这一面被撤。等价覆盖缺口（GraphitiEpisodeWorker 路径的开关可见性）交接 CARD-STORY-38-4-DUALWRITE-RETIREMENT（台账登记）")
    async def test_startup_log_dual_write_disabled_explicit(self, caplog):
        """
        [P1] Startup log shows "Dual-write: disabled (explicit configuration)" when disabled.

        Verifies: main.py lifespan() dual-write disabled log
        """
        from app.main import lifespan

        with (
            patch("app.main.get_default_monitor") as mock_monitor,
            patch("app.main.load_alert_rules_from_yaml", return_value=[]),
            patch("app.main.create_default_dispatcher"),
            patch("app.main.AlertManager") as mock_alert_mgr,
            patch("app.main.get_memory_service", new_callable=AsyncMock),
            patch("app.main.cleanup_memory_service", new_callable=AsyncMock),
            patch("app.main.set_alert_manager"),
            # ⚠️ 本行 patch 的目标已不存在（836d0986 2026-03-31 Epic2 pruning 把
            #    set_session_validator 从 app/main.py 的 import 块删掉，符号现只在
            #    app/api/v1/endpoints/websocket.py:45）。**故意保留**：它在 with 入口就
            #    AttributeError，使本用例在真 lifespan 启动前停住。删掉它实测会让这条
            #    单测跑起整个生产启动流程——加载 BGE-M3、扫 live vault、连 7691
            #    （实测 30.6s / 每条 1 次现网端口连接尝试）。见下方 xfail reason。
            patch("app.main.set_session_validator"),
            patch("app.main.settings") as mock_settings,
            patch.dict(os.environ, {"ENABLE_GRAPHITI_JSON_DUAL_WRITE": "false"}),
        ):
            mock_monitor.return_value = AsyncMock()
            mock_alert_mgr.return_value = AsyncMock()
            mock_settings.PROJECT_NAME = "test"
            mock_settings.VERSION = "0.0.0"
            mock_settings.DEBUG = False
            mock_settings.LOG_LEVEL = "INFO"
            mock_settings.cors_origins_list = []
            mock_settings.API_V1_PREFIX = "/api/v1"
            mock_settings.ENABLE_GRAPHITI_JSON_DUAL_WRITE = False

            app = MagicMock()
            app.state = MagicMock()

            with caplog.at_level(logging.INFO, logger="app.main"):
                async with lifespan(app):
                    pass

            log_messages = [r.message for r in caplog.records]
            assert any(
                "Dual-write: disabled (explicit configuration)" in msg
                for msg in log_messages
            ), (
                f"Expected startup log 'Dual-write: disabled (explicit configuration)' not found. "
                f"Got logs: {log_messages}"
            )

    @pytest.mark.asyncio
    @pytest.mark.xfail(strict=True, reason="59586af1(2026-03-26 refactor(phase2): delete fake bridge/JSON dual-write code, replaced by GraphitiEpisodeWorker) 删掉了 main.py 里 JSON dual-write 的启动日志（现全文已无 Dual-write 字样），本用例断言的那条日志不再存在；836d0986(2026-03-31) 又删掉了 set_session_validator，使本用例在 patch 入口即 AttributeError。设置项 ENABLE_GRAPHITI_JSON_DUAL_WRITE 本身仍在（config.py:477，canvas_service.py:267/:360 仍消费），故不是整条能力消失，只是「启动期播报」这一面被撤。等价覆盖缺口（GraphitiEpisodeWorker 路径的开关可见性）交接 CARD-STORY-38-4-DUALWRITE-RETIREMENT（台账登记）")
    async def test_warning_log_data_loss_risk_when_disabled(self, caplog):
        """
        [P1] WARNING log emitted when dual-write is disabled.

        Expected: "JSON fallback is disabled. Neo4j outage will cause data loss."
        Verifies: main.py lifespan() WARNING log for disabled dual-write
        """
        from app.main import lifespan

        with (
            patch("app.main.get_default_monitor") as mock_monitor,
            patch("app.main.load_alert_rules_from_yaml", return_value=[]),
            patch("app.main.create_default_dispatcher"),
            patch("app.main.AlertManager") as mock_alert_mgr,
            patch("app.main.get_memory_service", new_callable=AsyncMock),
            patch("app.main.cleanup_memory_service", new_callable=AsyncMock),
            patch("app.main.set_alert_manager"),
            # ⚠️ 本行 patch 的目标已不存在（836d0986 2026-03-31 Epic2 pruning 把
            #    set_session_validator 从 app/main.py 的 import 块删掉，符号现只在
            #    app/api/v1/endpoints/websocket.py:45）。**故意保留**：它在 with 入口就
            #    AttributeError，使本用例在真 lifespan 启动前停住。删掉它实测会让这条
            #    单测跑起整个生产启动流程——加载 BGE-M3、扫 live vault、连 7691
            #    （实测 30.6s / 每条 1 次现网端口连接尝试）。见下方 xfail reason。
            patch("app.main.set_session_validator"),
            patch("app.main.settings") as mock_settings,
            patch.dict(os.environ, {"ENABLE_GRAPHITI_JSON_DUAL_WRITE": "false"}),
        ):
            mock_monitor.return_value = AsyncMock()
            mock_alert_mgr.return_value = AsyncMock()
            mock_settings.PROJECT_NAME = "test"
            mock_settings.VERSION = "0.0.0"
            mock_settings.DEBUG = False
            mock_settings.LOG_LEVEL = "INFO"
            mock_settings.cors_origins_list = []
            mock_settings.API_V1_PREFIX = "/api/v1"
            mock_settings.ENABLE_GRAPHITI_JSON_DUAL_WRITE = False

            app = MagicMock()
            app.state = MagicMock()

            with caplog.at_level(logging.WARNING, logger="app.main"):
                async with lifespan(app):
                    pass

            warning_messages = [
                r.message for r in caplog.records if r.levelno >= logging.WARNING
            ]
            assert any(
                "JSON fallback is disabled" in msg for msg in warning_messages
            ), (
                f"Expected WARNING 'JSON fallback is disabled. Neo4j outage will cause data loss.' "
                f"not found. Got warnings: {warning_messages}"
            )


# ═══════════════════════════════════════════════════════════════════════════════
# AC-3: Missing Env Var (D4: Configuration)
# ═══════════════════════════════════════════════════════════════════════════════


class TestAC3MissingEnvVar:
    """AC-3: Missing env var defaults to False (identical to AC-1, post-daa9fd37)."""

    def test_missing_env_var_defaults_to_false(self):
        """
        [P0] When ENABLE_GRAPHITI_JSON_DUAL_WRITE is not set, Settings defaults to False.

        Verifies: config.py Field(default=False) via Settings instantiation (daa9fd37)
        """
        from app.config import Settings

        env_copy = os.environ.copy()
        env_copy.pop("ENABLE_GRAPHITI_JSON_DUAL_WRITE", None)

        with patch.dict(os.environ, env_copy, clear=True):
            settings = Settings(_env_file=None)
            assert settings.ENABLE_GRAPHITI_JSON_DUAL_WRITE is False, (
                f"Expected False when env var missing, got {settings.ENABLE_GRAPHITI_JSON_DUAL_WRITE}. "
                f"daa9fd37 起该字段为 [DEPRECATED] default=False；legacy JSON dual-write 由 "
                f"GraphitiEpisodeWorker 取代"
            )
