# Canvas Learning System - QA Automation Tests for Story 38.4
# Generated by Quinn QA Workflow (补充覆盖)
"""
QA supplemental tests for Story 38.4: Dual-Write Default Configuration Safety.

Covers edge cases NOT in ATDD tests:
- Pydantic env var parsing variants ("true", "True", "1", "0")
- Runtime getattr defense-in-depth consistency
"""

import os
from unittest.mock import patch

import pytest


class TestQAEnvVarParsing:
    """QA: Pydantic parses various truthy/falsy env values correctly."""

    @pytest.mark.parametrize(
        "env_value,expected",
        [
            ("true", True),
            ("True", True),
            ("TRUE", True),
            ("1", True),
            ("false", False),
            ("False", False),
            ("FALSE", False),
            ("0", False),
        ],
    )
    def test_pydantic_bool_parsing_variants(self, env_value, expected):
        """Various truthy/falsy string values are parsed correctly by Pydantic."""
        from app.config import Settings

        with patch.dict(os.environ, {"ENABLE_GRAPHITI_JSON_DUAL_WRITE": env_value}):
            settings = Settings(_env_file=None)
            assert settings.ENABLE_GRAPHITI_JSON_DUAL_WRITE is expected, (
                f"Env value '{env_value}' should parse to {expected}"
            )


class TestQAGetAttrDefenseInDepth:
    """QA: getattr fallback pattern used in code matches safe default."""

    @pytest.mark.xfail(
        strict=True,
        reason=(
            "59586af1 (2026-03-26) 删除 memory_service.py 侧的 "
            'getattr(settings, "ENABLE_GRAPHITI_JSON_DUAL_WRITE", ...) 防御点'
            "（实测该文件 0 命中，唯一残留是模块 docstring 的历史 AC 罗列，非代码）；"
            "且 daa9fd37 起 config.py 该字段为 [DEPRECATED] default=False，本用例赖以成立的 "
            "True 默认已不存在。⚠️ 如实声明：同形 getattr 防御在 canvas_service.py "
            "(:267/:360/:440/:457/:986/:995) 仍有 6 处、且 fallback 默认值是 True 而非本用例名"
            "所称的 False——「memory_service 侧防御点」才是被删对象，不是整个防御模式。"
            "等价覆盖缺口归 CARD-EPW-COVERAGE（第十四批，登记）。[CARD-RED-C1]"
        ),
    )
    def test_memory_service_getattr_fallback_is_false(self):
        """
        memory_service.py uses getattr(settings, "ENABLE_GRAPHITI_JSON_DUAL_WRITE", False).
        This is intentional defense-in-depth: if settings attribute is somehow missing,
        default to False (don't write) rather than crash.

        Note: Uses Settings(_env_file=None) to test Field default without .env override.
        """
        from app.config import Settings

        with patch.dict(os.environ, {}, clear=False):
            # Remove env override to test pure Field default
            os.environ.pop("ENABLE_GRAPHITI_JSON_DUAL_WRITE", None)
            fresh_settings = Settings(_env_file=None)

        # The Field default should be True (safe default from Story 38.4)
        assert fresh_settings.ENABLE_GRAPHITI_JSON_DUAL_WRITE is True

        # getattr with False fallback is a valid defense pattern
        result = getattr(fresh_settings, "ENABLE_GRAPHITI_JSON_DUAL_WRITE", False)
        assert result is True, (
            "getattr should return the actual True value, not the False fallback"
        )

    def test_env_example_documents_true_default(self):
        """The .env.example file documents the safe default correctly."""
        from pathlib import Path

        env_example = Path(__file__).parent.parent.parent / ".env.example"
        if env_example.exists():
            content = env_example.read_text(encoding="utf-8")
            assert "ENABLE_GRAPHITI_JSON_DUAL_WRITE=true" in content, (
                ".env.example should document the safe default as true"
            )
