# Canvas Learning System - QA Automation Tests for Story 38.4
# Generated by Quinn QA Workflow (补充覆盖)
"""
QA supplemental tests for Story 38.4: Dual-Write Default Configuration Safety.

Covers edge cases NOT in ATDD tests:
- Pydantic env var parsing variants ("true", "True", "1", "0")
- Runtime getattr defense-in-depth consistency
"""

import os
from unittest.mock import patch

import pytest


class TestQAEnvVarParsing:
    """QA: Pydantic parses various truthy/falsy env values correctly."""

    @pytest.mark.parametrize("env_value,expected", [
        ("true", True),
        ("True", True),
        ("TRUE", True),
        ("1", True),
        ("false", False),
        ("False", False),
        ("FALSE", False),
        ("0", False),
    ])
    def test_pydantic_bool_parsing_variants(self, env_value, expected):
        """Various truthy/falsy string values are parsed correctly by Pydantic."""
        from app.config import Settings

        with patch.dict(os.environ, {"ENABLE_GRAPHITI_JSON_DUAL_WRITE": env_value}):
            settings = Settings(_env_file=None)
            assert settings.ENABLE_GRAPHITI_JSON_DUAL_WRITE is expected, (
                f"Env value '{env_value}' should parse to {expected}"
            )


class TestQAGetAttrDefenseInDepth:
    """QA: getattr fallback pattern used in code matches safe default."""

    def test_memory_service_getattr_fallback_is_false(self):
        """
        memory_service.py uses getattr(settings, "ENABLE_GRAPHITI_JSON_DUAL_WRITE", False).
        This is intentional defense-in-depth: if settings attribute is somehow missing,
        default to False (don't write) rather than crash.

        Note: Uses Settings(_env_file=None) to test Field default without .env override.
        """
        from app.config import Settings

        with patch.dict(os.environ, {}, clear=False):
            # Remove env override to test pure Field default
            os.environ.pop("ENABLE_GRAPHITI_JSON_DUAL_WRITE", None)
            fresh_settings = Settings(_env_file=None)

        # The Field default should be True (safe default from Story 38.4)
        assert fresh_settings.ENABLE_GRAPHITI_JSON_DUAL_WRITE is True

        # getattr with False fallback is a valid defense pattern
        result = getattr(fresh_settings, "ENABLE_GRAPHITI_JSON_DUAL_WRITE", False)
        assert result is True, "getattr should return the actual True value, not the False fallback"

    def test_env_example_documents_true_default(self):
        """The .env.example file documents the safe default correctly."""
        from pathlib import Path

        env_example = Path(__file__).parent.parent.parent / ".env.example"
        if env_example.exists():
            content = env_example.read_text(encoding="utf-8")
            assert "ENABLE_GRAPHITI_JSON_DUAL_WRITE=true" in content, (
                ".env.example should document the safe default as true"
            )
