"""
Minimal test for IntelligentParallelCommandHandler
绕过canvas_utils的复杂初始化，直接测试核心功能

Author: Canvas Learning System Team
Date: 2025-11-04
"""

import json
import os
import sys
from pathlib import Path
from datetime import datetime

# 测试配置
TEST_CANVAS = r"C:\Users\ROG\托福\笔记库\Canvas\Math53\Lecture5.canvas"
BACKUP_SUFFIX = ".backup_epic10_test"

def backup_canvas(canvas_path):
    """备份Canvas文件"""
    backup_path = canvas_path + BACKUP_SUFFIX
    if os.path.exists(canvas_path):
        with open(canvas_path, 'r', encoding='utf-8') as f:
            data = f.read()
        with open(backup_path, 'w', encoding='utf-8') as f:
            f.write(data)
        print(f"[Backup] Canvas backed up to: {backup_path}")
        return True
    return False

def restore_canvas(canvas_path):
    """恢复Canvas文件"""
    backup_path = canvas_path + BACKUP_SUFFIX
    if os.path.exists(backup_path):
        with open(backup_path, 'r', encoding='utf-8') as f:
            data = f.read()
        with open(canvas_path, 'w', encoding='utf-8') as f:
            f.write(data)
        print(f"[Restore] Canvas restored from backup")
        os.remove(backup_path)
        return True
    return False

def read_canvas_simple(canvas_path):
    """简单读取Canvas文件（不依赖canvas_utils）"""
    try:
        with open(canvas_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception as e:
        print(f"[Error] Failed to read canvas: {e}")
        return None

def write_canvas_simple(canvas_path, canvas_data):
    """简单写入Canvas文件（不依赖canvas_utils）"""
    try:
        with open(canvas_path, 'w', encoding='utf-8') as f:
            json.dump(canvas_data, f, indent=2, ensure_ascii=False)
        return True
    except Exception as e:
        print(f"[Error] Failed to write canvas: {e}")
        return False

def scan_yellow_nodes_simple(canvas_data):
    """扫描黄色节点（color="6"）"""
    yellow_nodes = []

    if not canvas_data or "nodes" not in canvas_data:
        return yellow_nodes

    for node in canvas_data["nodes"]:
        if node.get("color") == "6":  # 黄色
            # 提取内容
            content = ""
            if node.get("type") == "text":
                content = node.get("text", "")
            elif node.get("type") == "file":
                content = Path(node.get("file", "")).stem

            if content:
                yellow_nodes.append({
                    "id": node.get("id"),
                    "type": node.get("type"),
                    "content": content,
                    "x": node.get("x", 0),
                    "y": node.get("y", 0),
                    "width": node.get("width", 300),
                    "height": node.get("height", 150)
                })

    return yellow_nodes

def create_test_doc(node, agent_name, canvas_dir):
    """创建测试文档"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    doc_filename = f"{node['id']}-{agent_name}-{timestamp}.md"
    doc_path = Path(canvas_dir) / doc_filename

    doc_content = f"""# AI Explanation: {node['id']}

**Agent**: {agent_name}
**Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Node ID**: {node['id']}

---

## Original Content

{node['content']}

---

## AI Explanation (Phase 1 MVP Test)

This is a Phase 1 MVP test document generated by the Intelligent Parallel Handler.

[Phase 2 will generate real Agent explanations here]

---

**Generated by Canvas Learning System - Intelligent Parallel Processor (Test)**
"""

    try:
        with open(doc_path, 'w', encoding='utf-8') as f:
            f.write(doc_content)
        return str(doc_path)
    except Exception as e:
        print(f"[Error] Failed to create doc: {e}")
        return None

def add_blue_node_simple(canvas_data, yellow_node, doc_path, agent_name):
    """添加蓝色AI解释节点"""
    import uuid

    blue_node_id = f"ai-explanation-{yellow_node['id']}-{uuid.uuid4().hex[:8]}"

    # 计算蓝色节点位置（在黄色节点右侧400px）
    blue_x = yellow_node['x'] + 400
    blue_y = yellow_node['y']

    # 创建蓝色节点
    blue_node = {
        "id": blue_node_id,
        "type": "file",
        "file": Path(doc_path).name,
        "x": blue_x,
        "y": blue_y,
        "width": 350,
        "height": 200,
        "color": "5"  # 蓝色
    }

    canvas_data["nodes"].append(blue_node)

    # 创建边连接
    edge_id = f"edge-{yellow_node['id']}-to-{blue_node_id}"
    edge = {
        "id": edge_id,
        "fromNode": yellow_node['id'],
        "fromSide": "right",
        "toNode": blue_node_id,
        "toSide": "left",
        "color": "5",
        "label": f"AI Explanation ({agent_name})"
    }

    if "edges" not in canvas_data:
        canvas_data["edges"] = []

    canvas_data["edges"].append(edge)

    return blue_node_id

def test_minimal_handler():
    """最小化测试Handler功能"""
    print("="*60)
    print("Minimal Test: IntelligentParallelCommandHandler")
    print("="*60)

    # 检查Canvas文件
    if not os.path.exists(TEST_CANVAS):
        print(f"[Error] Test canvas not found: {TEST_CANVAS}")
        return False

    print(f"[Test Canvas] {TEST_CANVAS}")

    # 备份Canvas
    if not backup_canvas(TEST_CANVAS):
        print("[Error] Failed to backup canvas")
        return False

    try:
        # Step 1: 读取Canvas
        print("\n[Step 1] Reading Canvas...")
        canvas_data = read_canvas_simple(TEST_CANVAS)
        if not canvas_data:
            return False
        print(f"  - Total nodes: {len(canvas_data.get('nodes', []))}")

        # Step 2: 扫描黄色节点
        print("\n[Step 2] Scanning yellow nodes...")
        yellow_nodes = scan_yellow_nodes_simple(canvas_data)
        print(f"  - Found {len(yellow_nodes)} yellow nodes")

        if not yellow_nodes:
            print("[Warning] No yellow nodes found to process")
            return True  # 不算失败

        # 只处理前2个黄色节点进行测试
        test_nodes = yellow_nodes[:2]
        print(f"  - Testing with {len(test_nodes)} nodes")

        # Step 3: 生成文档
        print("\n[Step 3] Generating documents...")
        canvas_dir = Path(TEST_CANVAS).parent
        agents = ["clarification-path", "memory-anchor"]

        results = []
        for idx, node in enumerate(test_nodes):
            agent_name = agents[idx % len(agents)]
            print(f"  - Node {idx+1}/{len(test_nodes)}: {node['id']} -> {agent_name}")

            doc_path = create_test_doc(node, agent_name, canvas_dir)
            if doc_path:
                print(f"    [OK] Doc created: {Path(doc_path).name}")
                results.append({
                    "node": node,
                    "agent": agent_name,
                    "doc_path": doc_path
                })
            else:
                print(f"    [FAIL] Doc creation failed")

        # Step 4: 修改Canvas（添加蓝色节点）
        print("\n[Step 4] Modifying Canvas...")
        for result in results:
            blue_node_id = add_blue_node_simple(
                canvas_data,
                result["node"],
                result["doc_path"],
                result["agent"]
            )
            print(f"  - Added blue node: {blue_node_id}")

        # Step 5: 保存Canvas
        print("\n[Step 5] Saving Canvas...")
        if write_canvas_simple(TEST_CANVAS, canvas_data):
            print("  [OK] Canvas saved successfully")
        else:
            print("  [FAIL] Canvas save failed")
            return False

        # Step 6: 验证结果
        print("\n[Step 6] Verification...")
        canvas_data_after = read_canvas_simple(TEST_CANVAS)

        blue_nodes_count = sum(1 for n in canvas_data_after.get("nodes", [])
                               if n.get("color") == "5")
        print(f"  - Blue nodes in Canvas: {blue_nodes_count}")
        print(f"  - Documents generated: {len(results)}")

        # 验证文档文件存在
        docs_exist = all(os.path.exists(r["doc_path"]) for r in results)
        print(f"  - All docs exist: {docs_exist}")

        # Step 7: 显示结果统计
        print("\n" + "="*60)
        print("Test Results:")
        print("="*60)
        print(f"  Yellow nodes processed: {len(results)}")
        print(f"  Documents created: {len(results)}")
        print(f"  Blue nodes added: {blue_nodes_count}")
        print(f"  Canvas modified: YES")
        print("="*60)

        # 询问是否恢复
        print("\n[Restore Option]")
        print("Canvas has been modified. Backup available at:")
        print(f"  {TEST_CANVAS + BACKUP_SUFFIX}")
        print("\nTo restore original Canvas, run:")
        print(f"  python -c \"from test_intelligent_parallel_minimal import restore_canvas; restore_canvas(r'{TEST_CANVAS}')\"")

        return True

    except Exception as e:
        print(f"\n[Exception] {e}")
        import traceback
        traceback.print_exc()

        # 尝试恢复
        print("\n[Auto-Restore] Attempting to restore canvas...")
        restore_canvas(TEST_CANVAS)

        return False

if __name__ == "__main__":
    success = test_minimal_handler()
    sys.exit(0 if success else 1)
