#!/usr/bin/env python3
"""clear-inbox · inbox_preview.py — 待处理盘点提名 preview 引擎（CARD-G5-6 · 只读）v1

对 `_待处理/`（可 --inbox-dir 覆盖）做确定性盘点：逐份给出**建议去向 + 依据 +
冲突标记**，超额按最旧优先分批（≤10），附 Sleeping/ 台账与 30 天标记，输出
版本化 JSON（schema_version=1，冻结）+ 自渲染人读 MD。

规格来源 = `_bmad-output/研究/语料快照-G5-1/2026-08-16-批注回复-R8-清待处理skill详细使用流程.md`
的 **Step 0-2 只读半边**（守卫 / 盘点分批 / 逐份提名）。Step 3-5（用户拍板、
执行、写侧回执）不在本卡范围 —— 属 CARD-G5-7 执行侧与撤销链。

⛔ 红线（沿用 board-split G5-2/G5-3 先例）：
  - **零写侧**：只读 vault 与收件箱既有文件；唯一写入 = --out-dir（缺省
    `<vault>/outputs/`）下的两份 preview 产物。不移动、不删除、不改 frontmatter。
  - scripts-only：无 SKILL.md、无 LLM 叙述层 —— 故不触
    `backend/scripts/check_skill_routing_block.py::EXPECTED_SKILLS`（T3 只认
    `skills/*/SKILL.md`）。skill 化与登记留给下梯队。
  - 确定性：同输入二跑 JSON+MD 逐字节相等（零时间戳零随机；「现在」经 --now 注入）。

━━━━━━━━━━━━━━━ 判据次序（卡片钦定，落盘 criteria_order 逐字同序）━━━━━━━━━━━━━━━
  C1 source URL        frontmatter `source:` 为 http(s) URL → primary-record · 留原地
  C2 AI 自述           文头窗口出现字面量 AI 生成标记 → secondary-synthesis · 归档
                       （文件名带 R{n}_ 时归轮次目录，否则 `deep research 报告/`）
  C3 空 / 空骨架       0 字节，或剥离后实质正文 = 0（未消化信号护栏见偏差 15，
                       当前登记九类；数字随轮次增长，此处不再写死）→ 建议删
  C4 精确重复          归一化正文与库内某文件**逐字相等** → 建议删（库内仅一份时
                       附正本相对路径；多份时附全部候选并声明正本不可判）
  C5 R{n}_ 文件名      → 归档到 `R{n}/`（类型按子模式表判，判不出则类型留空并标注）
  C6 兜底              → **拿不准**：不给去向、不给类型，附一句具体提问

⛔ 「拿不准」0 硬猜 —— 三条可机械检验的不变式（裁判逐条钉死）：
  1. `verdict == "建议删"` ⟹ `criterion ∈ {C3, C4}`；且 C4 必须给出 `exact_duplicate_of`。
     **近似重复（difflib）永远不产出建议删** —— 它只标「疑似·拿不准」。
  2. `criterion == "C6"` ⟹ `target_hint is None` 且 `nomination_type is None`。
     兜底不许被降级成一个看起来确定的去向（例如「默认归档到某处」）。
  3. 「归入白板」「新建节点」需要判断材料主题与既有白板的归属关系 —— 本引擎
     **无机械判据，故恒不产出**（`verdict_vocabulary.human_only`）。这类材料一律
     落 C6 拿不准并把这两个选项写进提问里，交给人/LLM 层。

⛔ 显式偏差与已知边界（⚠️ 本清单是**已发现项的登记**，不是穷尽性证明。
round-8 §四判定原措辞「全部声明、无未声明项」为 FAIL，理由成立：round-4/5/6/7/8
每一轮都是在「已全部声明」之后又抓出新的破坏路径 —— round-8 一轮就抓出三条
（井号后 NBSP、带版本号的模型声明、大写 Source 的 DOI）。有限的门与定点变异
只能证明「登记在册的这些确实被拦住了」，证不出「没有别的」。故此处不再声称
无未声明项；请把它读作**当前已知边界的快照**，新形态以门与审查为准，
发现即入清单）：
  1. **近似重复不是第七条判据，是修饰符**。R8 原稿 #4 写的是「高相似 → 建议删」，
     卡片把它收紧为「精确重复才建议删」。于是 difflib 相似度在本引擎里**永远不决定
     任何事**：前面已有判据命中时它挂 conflict 留痕；走到 C6 时它把兜底理由具体化为
     「疑似重复」。verdict 不受相似度影响 —— 0.93 这个数只呈现，不裁决。
  2. **精确重复在 C1/C2/C5 命中时不夺 verdict**（次序铁律），但证据必须留痕：
     `exact_duplicate_of` 照常填、并挂 `exact_duplicate_under_other_verdict` 冲突。
     信息零丢失，次序仍然是真的次序而不是「谁先算完谁赢」。
  3. **批内互为逐字重复**（两件都在收件箱）→ 只挂 `duplicate_within_batch` 冲突，
     **不**产出建议删：谁是正本在只读侧不可判，判了就是硬猜。
  4. **AI 自述标记是字面量 + 右边界规则匹配，仍不做语义否定检测**：汉字收尾标记后
     须为行尾、空白或**有限标点表**（`_MARKER_BOUNDARY_PUNCT`，不含连字符/破折号
     等），ASCII 字母收尾标记（`Generated by AI`）后须为行尾或表中标点（空白不算
     —— `Generated by AI Lab` 是机构名不是自述）。故「由 AI 生成内容的版权问题」
     这类话题提及不再命中；但「这不是由 AI 生成」（行尾）仍会**命中并给出归档
     提名** —— 子串匹配的原理上限在这个方向上**不安全**，靠 basis 带行号与
     **命中的规范标记文本**供人否决来兜底。⚠️ 原措辞写的是「逐字片段」，
     round-8 §四证伪：匹配在归一化形态上做，basis 展示的是**表项原文**而非
     输入原文 —— 输入 `GENERATED BY AI` 时 basis 里是表项 `Generated by AI`。
     行号准确、标记可核对，但它不是输入的逐字拷贝，故不再这么写。
     漏判方向（该抓没抓）：无正文时由偏差 15 的 AI 族信号（⑤疑似自述、
     ⑥独立词 AI、⑦生成断言结构、⑧生成器声明键）拦住落 C6。⚠️ 这条承诺
     **曾被连续四轮证伪四次**：`Generated by AI on March` 无护栏（round-4）、
     `generated by an AI system` 双层全盲（round-6）、`由AI系统生成` 无词边界
     （round-7）、`由 GPT-4 生成` 三层全盲（round-8）—— 每一次都是补一条信号，
     没有一次证明了穷尽性。**它是一条尽力而为的护栏，不是不变式**；未登记的
     新形态漏判方向仍**不安全**（可能落 C3 建议删）。有正文时若文件名带 R{n}_
     仍按 C5 归轮次，否则落 C6。本引擎只提名，不执行。
  5. **裸 --now 按 Asia/Shanghai 解释**（不用 `datetime.astimezone()` 的宿主本地时区）：
     本卡有「二跑逐字节相等」硬门，宿主 TZ 会让同一份输入在不同机器产出不同产物。
     此处与 `scripts/daily_review_pick.py` 的裸时间语义有意分歧，理由如上。
  6. **年龄口径**：秒级四舍五入后按整日向下取整。不四舍五入的话，`os.utime` 的
     float→ns 转换抖动（|ts| > 2^53 ns 时约 ±128ns）会把「整 5 天」判成 4 天。
  7. **`last_cleanup`（R8 Step 0 的「上次清仓 3 天前」）恒为 null**：只读 preview
     不持有清仓台账，该台账属执行侧（G5-7）。如实留空并说明，不推测、不伪造。
  8. **近似比对有成本上界**：正文超 `NEAR_DUP_BODY_CHAR_CAP` 或长度比落在
     `[1/NEAR_DUP_LEN_RATIO, NEAR_DUP_LEN_RATIO]` 之外的对不比。跳过数落进
     `near_dup_scan` —— 「没比对」与「比对过没有」必须在产物里可区分。
  9. **语料库规模上界** `CORPUS_FILE_CAP`：超出即截断并置 `truncated=true`。
     截断状态下「无重复」只意味着「已扫的部分无重复」，产物如实这么写。
 10. **产物名取自收件箱目录 basename**：两个不同路径但同 basename 的收件箱
     （`a/_待处理` 与 `b/_待处理`）写同一个 --out-dir 会互相覆盖。不自动加路径
     哈希消歧 —— 那会让产物名不可预测；请给不同的 --out-dir。
 11. **正本选择在多份同正文时取相对路径字典序最小者**（其余落
     `exact_duplicate_others`）。没有更有依据的选法就选一个**可预测**的 ——
     取"最先扫到的"会让正本随目录遍历顺序变。⛔ 该代表**不主张更正本**：
     命中 C4 的分支里，JSON basis 与人读 MD §四一致声明「哪一份是正本不可判」，
     `exact_duplicate_of` 仅为字典序代表（MD 不再钦定「正本 `字典序首项`」）；
     C1/C2/C5 先命中时重复证据落在 `exact_duplicate_*` 字段与 conflict 里，
     basis 是先命中判据的依据。路径含 Markdown 元字符时人读 MD 做反引号转义，
     其余元字符（`*`/`_`）不在转义范围（LOW 存量，JSON 侧恒保真）。
 12. **frontmatter 解析是顶层 `key: value` 扫描，不引 YAML 依赖**：块标量
     （`source: |` 换行缩进）拿到的值是 `|` 而非 URL，于是 C1 不命中、材料落到
     后续判据。方向是安全的（不会误判成一手），但确实识别不了这种写法。
     ⛔ 键必须是 `key:` 后接**空白或行尾**（正文行 `http://…` 的 `http:` 不是键，
     整篇不再被吞成 frontmatter）；连带：`source:https://x`（冒号后无空格）
     不识别为键 —— ⚠️ 两种形态**走的不是同一条路**（round-8 §四实证，
     原措辞混为一谈）：
     · 该行是块内**首个有效行** → 整块降为正文 → 那一行**本身就是实质正文**，
       于是 C3 压根不成立，材料按普通次序走到 C6 —— **不经过**偏差 15 的护栏；
     · 该行排在**合法键之后** → 被 span 吞掉（既不进 map 也不进正文）→ 此时
       才由偏差 15 的 `unparsed_fm` 信号接住落 C6。
     两条路的落点都不是「空骨架建议删」，但依据不同，`uncertain_reason` 也不同。
     ⚠️ 「文件名带 R{n}_ 仍按 C5 归轮次」以 **C1/C2/C3/C4 均未先命中**为前提
     （判据次序铁律）；「合法 source 剪藏仍按 C1」以该行确实被解析成 source 键
     为前提。原措辞省掉了这两个前提。
 13. **身份键对文件名做 NFC 归一**：只差 NFC/NFD 形态的两个文件名会得到同一个
     stable_id（与 `split_preview` 的重名判定同口径）。macOS 上这两者本就不能共存；
     在允许共存的文件系统上，这是一个已知且有意的合并。
 14. **极值时刻一律降级不崩、也不伪造**：人话时刻不可表示时落 `unrepresentable`
     占位，绝不换算出一个看似正常的时间。两条来源的可达性**不同**，如实分列：
     - **mtime 侧不可能越界**。实测（macOS APFS，本卡取证）：`os.utime` 把
       mtime 设到 9999-12-31 时**静默钳位**到 int64 纳秒上界 = 2262-04-11T23:47:16Z，
       `st_mtime` 与 `st_mtime_ns` 回读到的都是钳位值，不抛异常。所以引擎能观测到的
       最大 mtime 就是 2262-04-11 —— 人话格式化不会从 mtime 溢出。⛔ 这里的诚实点是：
       那个 2262 **不是引擎编的**，是文件系统真实存着的值，引擎照实报。
     - **`--now` 侧可达**（不受文件系统约束）：`--now 9999-12-31T23:59:59+00:00` 换算到
       Asia/Shanghai 即 OverflowError，`--now …-11:00` 连 UTC 侧都 ValueError ——
       此时落占位。**不**在入口拒绝：拒绝会让「时刻太大」这件事看起来像输入非法，
       而它其实只是「这个时刻没法用人话写出来」，产物本身照常成立。
     `age_days` 由「秒差四舍五入到整秒后整除 86400」得出，不受格式化降级影响。
 15. **「建议删」有两个出口（C3/C4），共用一组「未消化信号」护栏**（round-3 自审、
     round-4 审查与 round-5 自审实证后加入）：在 C1/C2 都未命中的前提下，文件若
     带有引擎未能完全消化的结构信号 —— ① 以**未闭合 HTML 注释**结尾（B3-1：忘写
     `-->` 的粘贴件曾被判「标题 0 行」假依据建议删）；② frontmatter **含解析不成
     键的行**（H3-1：`source:https://x` 排在合法键后被 span 吞掉，一手书签被判
     建议删）；③ frontmatter **有来源声明**，三个半边：③a `source` 键在场
     （H1-1）——⚠️ 键名按 `_norm_fm_key` 归一（casefold + `-`→`_`），故
     `Source`/`SOURCE` 同判（round-8 HIGH：原实现字面小写查找，`Source:` 取不到，
     唯一来源标识被当作不存在并 confident 删除）；③b **任意键的值含 URL 形态**
     （substring 级，`url:`/`URL:` 等剪藏工具键名，round-5 自审 F2 + round-7
     BLOCKER-3）；③c **任意键的值含 DOI 形态**（`_DOI_RE`，round-8 HIGH：
     `Source: DOI:10.1000/xyz` 两个半边都漏）。⚠️ 三个半边**都只降 C6**：
     C1 仍只认字面小写 `source` 键 + http(s) URL，DOI 不冒充 URL、不升 C1。
     ⚠️ **扫描面是 `frontmatter_pairs` 的全量、不折叠键值对**，不是
     `frontmatter_map` 折叠后的字典（round-2 审查 BLOCKER：`doi:` 空值排在
     `doi: 10.1000/hidden` 前面时 `setdefault` 只留首值，③ 的三个半边全都扫不到
     那个 DOI，同形 `url:` 反例同时穿透 C3 与 C4 两个出口）。判据侧仍用首值
     语义，未动 —— 改判据取值是有后果的行为变更，不能作为护栏加宽的副作用；
     ④ frontmatter 带**睡眠台账键 slept_at**（round-5 自审 F3：引擎在 Sleeping
     台账认识这个键，删除会抹掉用户的起睡时间戳）；⑤ 文头有**疑似 AI 自述**
     （边界规则拒掉但裸子串在场，round-4 BLOCKER-1：`Generated by AI on March`
     × 无正文曾被建议删）；⑥ 文头或 frontmatter 值出现**独立词「AI」**
     （左右非 ASCII 字母，round-6 BLOCKER-1 `generated by an AI system` 不含任何
     表项 + round-7 BLOCKER-1 `由AI系统生成` CJK 邻接无词边界）；⑦ 文头出现
     **生成断言结构** `由 <某物> 生成` / `generated by <某物>`（round-8
     BLOCKER-2：`由 GPT-4 生成` 比表项多一个版本号，三层全盲）；⑧ frontmatter
     带**生成器声明键**（`generator`/`model`/`llm` 等，值里可以完全没有「生成」
     二字，如 `generator: claude-opus-4`）—— 则 C3 不判「空骨架」。信号与 C4 叠加时（round-4 BLOCKER-2：非标准 source ×
     正文重复），C4 也不建议删 —— C4 只证明「剥掉 frontmatter 后正文相等」，
     不证明「整个文件多余」，独有信号必须先摆到台面上。无信号但 frontmatter
     带元数据键时，C4 照常建议删但挂 `frontmatter_metadata_present` 冲突留痕。
     ⑨ frontmatter 里**任何非空值**（round-2 审查 HIGH：`citation: ISBN
     978-7-111-54742-6` 既不沾 URL 也不沾 DOI，①-⑧ 全盲被判 C3 确定删除 →
     先改成「白名单外的非空值」；round-3 审查 HIGH 又把白名单打穿 —— 放行的是
     键名而信息在值里，`title: ISBN 978-…` / `title: <这份材料唯一写下的那句话>`
     照样被确定删除，于是白名单整个取消）—— 则 C3 不判「空骨架」。
     ⛔ ⑨ 是这一族的**方向反转**：①-⑧ 都在枚举「危险的键名/值形态」，那是
     fail-open —— 漏一个就是一条确定删除的路径，而 round-4..round-2 六轮抓到的
     新反例全都是「又漏了一个」。⑨ 改成枚举「已知无害、删掉不丢独有信息」的键，
     默认拦住。两种漏判后果不对称：漏一个白名单项只是多落一次拿不准，漏一个
     来源键名是把用户材料确定删掉。
     ⚠️ ①-⑧ 因此**不再是安全底线，而是「给出更好理由」的机制** —— 它们让
     `uncertain_reason` 说得出「这是个 DOI」而不是笼统的「有个不认识的键」。
     统一原则：**「建议删」的两个出口都要拦；对结构没有把握的文件，宁可拿不准
     也不建议删**。⚠️ 这仍不是完备判据：⑨ 只覆盖 **frontmatter 里的非空值**，
     正文侧的未消化结构（①②）与文头侧的声明（⑤⑦）各有自己的边界；白名单本身
     也可能收窄得不对。⑤⑥⑦⑧ 是 round-4/6/7/8 四轮各补一条堆出来的，每一轮都是
     先被真实反例打穿再补 —— 没有任何一轮证明了「没有下一条」。
 16. **URL 合法性只查 scheme 与 hostname 非空，不校验 authority 其余部分**
     （round-8 §五 MEDIUM 实证）：`source: https://example.test:notaport/x` 实跑为
     `C1 / 留原地 / primary-record / confident=true`。根因是 `urlsplit` 只在
     **访问 `.port`** 时才对非法端口抛 ValueError，而 `_is_primary_source_url`
     只访问 `.hostname`，于是非法端口一路放行。⛔ 本卡**不修**（CARD-G5-6c §3
     默认裁决：保留为 M/L，不得写成已穷尽）：方向安全 —— 判成一手来源 =
     留原地，不删不动、不改文件；且「什么算合法 authority」属 URL 规范面，
     不属本引擎的盘点判据面。如实登记，待用户裁决。
 17. **生成声明与来源标识的护栏按「声明结构 / 字段名」判，不枚举具体名字**
     （round-8 BLOCKER-2 与 HIGH 的修法，CARD-G5-6c §3 默认裁决）。四条判据：
     生成断言结构 `_GEN_CLAIM_CN_RE`/`_GEN_CLAIM_EN_RE`、生成器声明键
     `_GENERATOR_DECL_KEYS`、来源键名别名 `_SOURCE_DECL_KEYS`、DOI 值形态
     `_DOI_RE`，外加⑨白名单兜底（见下）。⛔ 之所以不枚举模型名：模型名是
     **开放集合**（`GPT-4` 之后还有 `GPT-4o`/`Claude 3.5`/下个月发布的那个），
     而「由 X 生成」这个断言骨架不随模型名增长 —— round-8 BLOCKER-2 的教训正是
     「表里有 `由 GPT 生成`，差一个版本号就全盲」。
     ⚠️ **骨架自身的边界要说清**（round-2 审查 FAIL 的教训：上一版写「断言骨架
     是闭合的」，而当时中文骨架带着 `{1,40}` 长度上界，65 字符的模型名直接穿透
     —— **上界本身就是缝隙，却被措辞说成了闭合**）。上界已去掉；现在骨架的真实
     边界是：中文须 `由` 与 `生成` **在同一行、中间不跨句读**（`。；！？`）；
     英文须 `generated by` + 词边界 + 一个词字符。跨行写、换个动词（「撰写」
     「产出」）、或把断言拆到两句里，骨架都认不出来。
     ⚠️ 四条**只降 C6，不进任何判据**，DOI 尤其**不解析、不解引用、不联网**，
     只把「这里有一个出处标识」摆上台面。
     ⚠️ 键名集合仍是有限的：`authored_with: gpt-4`（键名不在表 + 值无断言结构）
     不会被①-⑧任何一条具体信号认出来 —— 它由⑨兜底接住（`authored_with` 不在
     白名单且值非空）。**兜底才是这一族的安全底线，具体信号只负责给出更好的
     理由**。本条不是穷尽性证明。
     ⚠️ 误命中方向如实声明：`由编译器生成`、`generated by hand` 这类非 AI 的
     生成断言也会命中 ⑦ —— 它们只降 C6（拿不准，不给去向），方向安全，
     代价是这类无正文文件不再被建议删。这是刻意选的偏向。

 18. **C4「精确重复」不看标题 —— 标题里的独有信息会随重复件一起被删**
     （第五轮终审实测；用户 2026-09-02 第二次裁决：**不改**）。
     `dup_body()` 丢标题是有理由的（同一段材料被粘两份时标题常不同），但代价是
     `# 只有这一份写了母本第37页` + 与库内相同的正文 = `C4 建议删 + confident=true`。
     让标题进比对会使「同稿不同标题」「一份有标题一份没有」都不再算重复
     （5 件取样只剩 1 件被识别），重复识别基本失效 —— 用户选择保住识别能力。
     ⚠️ 与偏差 15 的 C3 侧裁决**刻意不一致**，这个不一致是被明确选择的，不是遗漏。
 19. **本卡交付时的其余已知缺陷（第五轮终审登记，未修）**：
     · 多行闭合 HTML 注释、frontmatter 里的 YAML 注释 —— 来源写在其中仍会被删；
     · `splitlines()` 先于不可见归一执行，故 U+001D/001E/2028/2029 这类**行分隔**
       类字符能绕过护栏（问题在处理顺序，不在码点表）；
     · 空键名编码 DOI/ISBN 的对抗构造。
     ⚠️ 五轮独立审查每一轮都抓出新构造 —— 这份清单是**当轮快照**，不是穷尽。
━━━━━━━━━━━━━━━━━━━━━ 与 board-split 的复用关系（卡片 (c)）━━━━━━━━━━━━━━━━━━━━━
本模块以 importlib 从**兄弟 skill** `board-split/scripts/split_preview.py` 加载并复用：
`compute_stable_id`（身份键编码纪律）、`write_pair_atomically_checked` / `prepare_out_dir`
/ `assert_symlink_free`（写侧物理防御：先验祖先链无 symlink 再单级 mkdir、O_NOFOLLOW +
nlink 准入、两份产物先验完再落笔、失败只回滚本次新建的目录项）、`nfc`、`md_cell`、
`MAX_FILENAME_BYTES`。**不复制一份**：那套防御经多轮对抗审查加固，复制等于制造第二个
会漂移的安全实现。来源缺失时 fail-closed 报出确切路径，不做本地降级副本。

⛔ 身份空间不可互换（DD-13 名实一致，与 split_preview 对 board_manifest 的声明同型）：
  `compute_stable_id` 的命名空间段写死为 `split-anchor/v1`、前缀 `bsa1-`，指向
  「原板里的一段来源锚点」。本模块的 ID 指向「收件箱里的一个文件路径」，语义不同层。
  做法：把 `INBOX_ID_NAMESPACE = "inbox-item/v1"` 塞进 heading-path 槽位（该函数的载荷
  用长度前缀编码，对任意字节单射 → 与任何真实 split 候选的载荷必不相同），再把返回值的
  `bsa1-` 换成自有前缀 `inb1-`。于是编码纪律单一真相源，标签不冒充。
  身份键里**只有路径**：改内容、改 mtime、改 frontmatter 一律不换 ID；改名/移动才换。

用法:
    python3 inbox_preview.py --vault <vault> --now <ISO时刻> [--inbox-dir DIR]
                             [--out-dir DIR] [--batch-size N≤10]
退出码: 0 成功（含空仓）/ 1 输入非法、显式 inbox 不存在、写侧防御拒绝
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import importlib.util
import json
import os
import re
import sys
import unicodedata
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from urllib.parse import urlsplit, unquote

# ───────────────────── 复用来源装载（fail-closed，不做降级副本） ─────────────────────

#: 兄弟 skill 的只读 preview 引擎 —— 写侧物理防御与身份键编码的单一真相源。
_SP_PATH = (
    Path(__file__).resolve().parents[2] / "board-split" / "scripts" / "split_preview.py"
)


def _load_split_preview():
    """加载复用来源。⛔ 缺失即拒绝运行：本引擎的写侧防御全部来自它，
    退化成「自己简单写一下」等于在安全面上开一个没人审过的旁路。"""
    if not _SP_PATH.is_file():
        raise SystemExit(
            "✗ 复用来源缺失，拒绝以未加固的写侧运行。需要文件: "
            f"{_SP_PATH}\n"
            "  （本引擎的 out-dir symlink 守卫 / O_NOFOLLOW 准入 / 双产物原子发布"
            " 全部复用该模块，不做本地降级副本。）"
        )
    spec = importlib.util.spec_from_file_location("_g56_split_preview", _SP_PATH)
    mod = importlib.util.module_from_spec(spec)
    # ⛔ 零写侧的第一现场（Codex 审查实证抓出）：`exec_module` 默认会在被导入模块
    # 旁边写 `__pycache__/*.pyc` —— 那是往 **vault 里**、而且是**另一条车道的
    # board-split 目录里**落文件。零写侧不是"不改用户的 md"，是"除 out-dir 外
    # 一个字节都不落"。原先的零写快照抓不到它: fixture 树里根本没有真实 skills 目录，
    # 而 live 快照跑的时候 .pyc 早已存在且是最新的, 于是"没有变化"= 假绿。
    prev = sys.dont_write_bytecode
    sys.dont_write_bytecode = True
    try:
        spec.loader.exec_module(mod)
    finally:
        sys.dont_write_bytecode = prev
    return mod


_SP = _load_split_preview()

nfc = _SP.nfc
md_cell = _SP.md_cell
MAX_FILENAME_BYTES = _SP.MAX_FILENAME_BYTES

# ───────────────────────────────── 常量 ─────────────────────────────────

SCHEMA_VERSION = 1  # 冻结：本卡产物形状即 v1 契约
GENERATOR = "clear-inbox/inbox_preview.py v1.0 (CARD-G5-6 inbox preview, read-only)"

INBOX_ID_NAMESPACE = "inbox-item/v1"
INBOX_ID_PREFIX = "inb1-"
INBOX_ID_BASIS = "inbox-file"
ID_STABILITY = "inbox_path_v1"  # ≠ split_preview 的 split_anchor_v1

DEFAULT_INBOX_NAME = "_待处理"
SLEEPING_DIR_NAME = "Sleeping"

#: D15 确认预算：一次性 >20 项完成率趋近 0；每件 3-5 秒的勾选量才会被真正做完。
#: 上限硬编码为 10 —— --batch-size 只能在 [1,10] 内调小，不能突破。
BATCH_MAX = 10

#: 睡满即提醒的门槛（R8 Step 4「睡满 30 天后清仓时自动提醒」）。
SLEEP_ALERT_DAYS = 30

#: 近似重复：只用于标「疑似·拿不准」，**绝不**产出建议删。
NEAR_DUP_RATIO = 0.90
NEAR_DUP_BODY_CHAR_CAP = 200_000
NEAR_DUP_LEN_RATIO = 1.5  # 长度比超出 [1/1.5, 1.5] 的对直接跳过（并计数留痕）
NEAR_DUP_TOP_N = 3  # 每件最多呈现的疑似正本数（按 ratio 降序、路径升序）

#: 语料库扫描上界（防 --vault 误指到 home 之类的大树）。
CORPUS_FILE_CAP = 5000
#: 语料库排除的目录名：产物目录 + 一切隐藏目录（.obsidian/.git/.claude/.trash…）。
CORPUS_EXCLUDED_DIR_NAMES = frozenset({"outputs"})

#: C2 文头窗口：frontmatter 块 + 其后前 N 行。窗口之外的同款字样不算「文头自述」。
HEAD_SCAN_LINES = 20

#: C2 字面量标记表（确定性常量，非 LLM 判断）。命中时 basis 带行号与逐字片段。
#: ⛔ 每一条都必须是**生成断言**，不是话题提及（Codex HIGH 实证）：原先收了裸词
#: `Deep Research`，于是手写笔记 `# Deep Research 产品比较` 也被判成 AI 产物并给出
#: 确定的归档去向 —— 那是硬猜。收窄后 `…由 Deep Research 生成` 仍命中。
#: ⛔ round-2 H2 再收窄：删去裸词 `AI 生成`/`AI生成`（它们是 `由 AI 生成`/`由AI生成`
#: 的严格子串，删除不丢任何带断言锚的命中，只丢 `# AI 生成内容的版权问题` 这类
#: 话题误命中）；且匹配加右边界规则（见 `_find_marker_pos`）。
#: ⛔ round-3 自审 H2-1 再收窄：删去截断形态 `本文由 AI`/`本报告由 AI` —— 它们以
#: ASCII 字母收尾，右边界规则对它们退化成空操作（`本文由 AI 领域…` 的 `AI` 后是
#: 空格即命中）。真断言行 `本文由 AI 生成` 仍被 `由 AI 生成` 命中，删除只丢话题
#: 误命中。`Generated by AI` 保留，但其右边界禁用空白（见 `_find_marker_pos`）。
AI_MARKERS = (
    "由 Deep Research 生成",
    "Deep Research 生成",
    "deep research 生成",
    "由 DeepResearch 生成",
    "DeepResearch 生成",
    "Generated by Deep Research",
    "由 AI 生成",
    "由AI生成",
    "由 Claude 生成",
    "由 ChatGPT 生成",
    "由 GPT 生成",
    "Generated by AI",
    "generated by AI",
)

#: 标记命中的右边界字符集（汉字收尾标记）：行尾之外，标记后必须是空白或这些标点。
#: 仍是字面量匹配 —— 边界规则是字符检查，不是语义理解（原理上限见显式偏差 4）。
_MARKER_BOUNDARY_PUNCT = "。，、；：！？.,;:!?)）】」』\"'“”‘’《》~…%*_"
#: ASCII 字母收尾标记（`Generated by AI`）的额外收紧：空白**不算**边界 ——
#: `Generated by AI Lab researchers` 的 `AI` 后是空格，放行就是假阳性归档。
#: 只认行尾或标点；`Generated by AI on March` 这类漏判落 C6，方向安全。

#: C5 轮次目录的类型子模式表（判不出则类型留空并标 type_uncertain）。
ROUND_SUBPATTERNS = (
    ("批注回复", "annotation-reply"),
    ("研究", "secondary-synthesis"),
    ("调研", "secondary-synthesis"),
    ("report", "secondary-synthesis"),
)

DR_TARGET = "deep research 报告/"

CRITERIA_ORDER = (
    "C1_source_url",
    "C2_ai_self_declared",
    "C3_empty_or_skeleton",
    "C4_exact_duplicate",
    "C5_round_filename",
    "C6_undecided",
)

V_STAY = "留原地"
V_ARCHIVE = "归档"
V_DELETE = "建议删"
V_UNSURE = "拿不准"
V_TO_BOARD = "归入白板"
V_NEW_NODE = "新建节点"

VERDICT_VOCABULARY = {
    "all": [V_TO_BOARD, V_NEW_NODE, V_ARCHIVE, V_DELETE, V_STAY, V_UNSURE],
    "card_enumerated": [V_TO_BOARD, V_NEW_NODE, V_ARCHIVE, V_DELETE],
    "reachable_by_engine": [V_STAY, V_ARCHIVE, V_DELETE, V_UNSURE],
    "human_only": [V_TO_BOARD, V_NEW_NODE],
    "human_only_note": (
        "「归入白板」「新建节点」需要判断材料主题与既有白板/节点的归属关系，"
        "本引擎无机械判据 —— 恒不产出。这类材料一律落 C6 拿不准，并把这两个选项"
        "写进提问里交给人裁决。给不出机械依据还硬填一个去向，就是硬猜。"
    ),
}

UNDECIDED_ASK = "这份要归入哪块白板、还是新建节点、还是归档（二手综合 / 一手快照）？"

NOT_EXECUTED = (
    "本 preview 只读生成：未移动、未删除、未修改任何 vault 或收件箱既有文件"
    "（唯一写入 = out-dir 下两份 preview 产物，缺省落 <vault>/outputs/）；"
    "逐条拍板与执行属 CARD-G5-7，本引擎不提供任何写侧动作。"
)

LAST_CLEANUP_NOTE = (
    "只读 preview 不持有清仓台账（R8 Step 0 的「上次清仓 N 天前」需执行侧记录，"
    "属 CARD-G5-7）。此处如实留空，不推测、不伪造。"
)

#: 标签（= 收件箱目录 basename，进产物文件名）的非法字符类。
#: ⛔ 与 split_preview._BAD_NAME **逐字同源**：该常量为私有，故此处平行定义，
#: 由裁判 `test_reuses_split_preview_helpers_by_import` 断言两者 pattern 逐字相等，
#: 防「两套判据各自漂移」。
_BAD_LABEL = re.compile(r'[\\/`$"\']|\.\.|^\.|[\x00-\x1f]')

#: 人话时区：**固定 +08:00**，刻意不走 `ZoneInfo("Asia/Shanghai")`。
#: ⛔ 理由是本卡有「二跑逐字节相等」硬门，而该门必须**跨宿主**成立：ZoneInfo 在装了
#: tzdata 的机器上会给 1986-1991 年的日期套上夏令时（实测 1988-07-01 → +09:00），
#: 没装 tzdata 的机器退化成 +08:00 —— 同一份输入在两台机器产出不同字节。
#: 代价是那六年的历史时刻不带夏令时；收件箱材料不可能有 1980 年代的 mtime，
#: 拿一个不可能发生的历史精度去换一个每次都要成立的确定性，是划算的。
#: （与 `scripts/daily_review_pick.py` 优先 ZoneInfo 的口径有意分歧，理由如上。）
_TZ_SHANGHAI = timezone(timedelta(hours=8))

#: ATX 标题：**最多 3 个字面空格**缩进（⛔ 与 _FENCE_RE 同口径，\s 会放行
#: 制表符/NBSP —— `\t# keep` 是缩进代码、`\xa0# keep` 是普通正文，都曾被当
#: 标题剥掉 → 空骨架建议删，round-7 BLOCKER-2）。
#: ⛔ **井号后的分隔同样只认 ASCII 空格/制表符**（CommonMark §4.2：开头的 `#`
#: 序列后必须跟空格、制表符或行尾）：round-8 BLOCKER-1 实证前置缩进收窄后
#: 后边界仍写着 `(?:\s|$)`，而 Python `re` 的 `\s` 在 str 模式下是 Unicode
#: 语义 —— `#\xa0keep`（字节 23c2a06b6565700a）被当成标题剥掉 → 「标题 1 行、
#: 实质正文 0 字符」→ `建议删 + confident=true`。同一条规则的两半只修一半，
#: 等于没修。⚠️ 边界如实声明：本条只管**标题判定**；`#` 孤行（`# ` / `#\xa0`
#: 这类井号后无实质内容者）经 `_ONLY_STRUCT_RE` 归入「纯结构行」，与普通空格
#: 版本同桶 —— 那是既有的结构行口径，不是本条收窄出来的新差异。
_HEADING_RE = re.compile(r"^ {0,3}#{1,6}(?:[ \t]|$)")
#: ⛔ 第十一轮 HIGH（R11-H3）：列表/引用前缀是 **Markdown 结构**，判定只能用
#: ASCII 空格与制表符 —— `\s` 会把 NBSP 当缩进，把「NBSP 开头的正文」剥成空。
_LIST_PREFIX_RE = re.compile(r"^[ \t]*(?:[-*+][ \t]+|\d{1,3}[.)][ \t]+|>[ \t]?)+")
#: 纯结构行（分隔线 / 表格分隔 / 空列表符）。⛔ 不含 `~`：`~~~` 是代码围栏标记，
#: 由 `_classify_lines` 的状态机处理；把它当"结构"曾让整段围栏代码凭空消失。
#: ⛔ 第七轮终审 HIGH（R7-H2）：原表含 `=`/`|`/`:`，于是 `:=`、`=>`、`||` 这类
#: **有语义的运算符**被当纯结构忽略，3 字节文件被判空骨架确定删除。
#: 收窄口径：一行只有在**全部由同一种结构字符（加空白）构成**时才算结构行 ——
#: `---`/`***`/`|||`/`>>>` 是结构，`:=`/`=>`/`||=` 是内容。
#: ⛔ 第八轮 HIGH：上一版把线画在「同字符重复」上，于是 `||`（逻辑或）被判结构
#: 而删除。真正的分界是**这行是不是 Markdown 的结构记号**：分隔线要 ≥3 个
#: （CommonMark `---`/`***`/`___`），表格分隔要含 `-`，引用/标题记号是 `>`/`#`。
#: `||` 两个竖线既不是分隔线也不是表格分隔，它就是正文。
#: ⛔ 同上：纯结构行判定里的空白也只认 ASCII（`\s` 会让「只有 NBSP」的行
#: 被当成空结构行删掉）。
_ONLY_STRUCT_RE = re.compile(r"^[ \t\-=*_|:#>]*$")
_STRUCT_CHARS = "-=*_|:#>"


def _atx_heading_text(ln: str) -> str:
    """ATX 标题行里**真正的标题文字**（去掉 opening 与可选的 closing 序列）。

    ⛔ 第九轮审查 HIGH（R9-H3）：此前用 `ln.lstrip(" \t#")` 一把撸掉所有井号，
    于是 `# # #` 的**中间那个 `#`**（它是可见的标题内容）被当成 opening 的一部分
    剥掉，整行判成空标题 → 文件被确定删除。ATX 的结构是
    `opening(1-6 个 #) + 空白 + content + 可选 closing(全 # 且前有空白)`，
    分离得按这个结构走，不能靠字符集剥离。
    """
    m = re.match(r"^ {0,3}(#{1,6})(?:[ \t]+|$)", ln)
    if not m:
        return ""
    # ⛔ 第十轮 HIGH（R10-H3）：这里的空白**只能是 ASCII space/tab**。
    # Python 的 `.strip()` 与 `\s` 默认是 Unicode 语义，于是 `# <NBSP>#` 里那个
    # NBSP 被当成 closing 前的分隔符，末尾可见的 `#` 被当收尾序列剥掉 → 空标题
    # → 确定删除。CommonMark §4.2 的 closing 必须由 space/tab 与内容分开。
    # ⚠️ 这与本卡开篇那条 NBSP 是**同一个陷阱**：该用 ASCII 口径的地方用了
    # Unicode 口径。同一个坑在这张卡里踩了两次。
    rest = ln[m.end() :].strip(" \t")
    closing = re.search(r"(?:^|[ \t])(#+)$", rest)
    if closing:
        rest = rest[: closing.start()].strip(" \t")
    return rest


def _is_structural_line(t: str) -> bool:
    """纯结构行判定（分隔线 / 表格分隔 / 空列表符）。"""
    if not _ONLY_STRUCT_RE.match(t):
        return False
    kinds = {c for c in t if c in _STRUCT_CHARS}
    if len(kinds) > 1:
        return False
    core = t.strip(" \t")
    if not core:
        return True
    ch = core[0]
    # 分隔线（CommonMark 要求 ≥3 个）/ 引用与标题记号 / 表格分隔（含 `-`）
    if ch in "-=*_" and len(core) >= 3:
        return True
    if ch == "#":
        # ⛔ 第九轮 HIGH（R9-H3）：ATX 最多六级，`#######`（7 个）**不是**空标题
        # 模板而是普通文本。此前 `set(core) <= {ch}` 把任意个数都当结构。
        return len(core) <= 6
    return ch in ">:|" and set(core) <= {ch} and len(core) >= 3


#: 代码围栏（``` 或 ~~~，允许**最多 3 个空格**缩进 —— ⛔ 必须是字面空格：
#: `\s{0,3}` 会放行制表符，而 CommonMark 里制表符缩进 ≥4 列是缩进代码块，
#: `\t```` 既能开也能**关**围栏，会让围栏提前闭合、其后的标题被剥（round-3 自审 B3-4）。
_FENCE_RE = re.compile(r"^ {0,3}(`{3,}|~{3,})")
#: ⛔ YAML 映射键必须是 `key:` 后接**空白或行尾**：正文行 `http://example.com/path`
#: 里的 `http:` 曾被当成键，整篇被吞成 frontmatter → 空骨架 → 建议删（round-2 H3）。
#: 连带：`source:https://x`（冒号后无空格）此后不再识别为键 —— 若它是块内首个有效
#: 行则整块降为正文，否则被 span 吞掉；两种形态都由 C3 护栏（显式偏差 15）兜住落 C6。
#: 冒号前允许空白（`title : x` 与 `_FM_LOOKS_LIKE_KEY_RE` 同口径，pyyaml 亦认它是键；
#: round-3 自审 H3-3：两条正则曾对「什么算键」各说各话，span 认而 map 不认 → 空正文）。
_FM_KEY_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*)\s*:(?:\s+(.*))?\s*$")
#: frontmatter 首个有效行必须像 YAML 映射键 —— 否则那只是被两条 `---` 夹住的正文
_FM_LOOKS_LIKE_KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_-]*\s*:(?:\s|$)")
#: URL 形状初筛（`https?://\S+` 会把 `https://?` 也认成一手来源，Codex HIGH）。
#: ⛔ 但正则列不尽 authority 段的空 host 形态（`https://:443/x`、`https://user@/x`
#: 都能过它）——host 非空由 `_is_primary_source_url` 的 urlsplit 检查保证
#: （round-2 H1 实证），本正则只负责拦明显不是 URL 的值。
#: re.I：URI scheme 按 RFC 3986 §3.1 大小写不敏感，`HTTPS://example.com` 也是
#: 一手来源（round-3 自审 H1-2）；大小写归一后 scheme 检查在 `_is_primary_source_url`
#: 里仍保留作防御深度。
_URL_RE = re.compile(r"^https?://[^\s/?#]+\S*$", re.IGNORECASE)


def _is_primary_source_url(src: str) -> bool:
    """C1 的机械判据：`scheme ∈ {http, https}` **且 hostname 非空**才算一手来源。
    解析异常一律不算 URL —— 方向安全（不误判一手，材料落后续判据）。"""
    if not _URL_RE.match(src):
        return False
    try:
        parts = urlsplit(src)
    except ValueError:
        return False
    return parts.scheme in ("http", "https") and bool(parts.hostname)


_ROUND_RE = re.compile(r"(?:^|[^0-9A-Za-z])R(\d{1,4})_")


# ───────────────────────────── 身份键 ─────────────────────────────


def compute_inbox_stable_id(rel_path: str) -> str:
    """收件箱条目身份键 = f(路径)。改内容/改 mtime 不换 ID；改名/移动才换。

    编码纪律复用 `split_preview.compute_stable_id`（长度前缀载荷，对任意字节单射），
    命名空间经 heading-path 槽位注入，返回值改挂自有前缀 —— 见文件头「身份空间
    不可互换」。**不**把 mtime/size/内容进键：那样一改正文就换身份，diff 无意义。
    """
    raw = _SP.compute_stable_id(rel_path, [INBOX_ID_NAMESPACE], 1, INBOX_ID_BASIS)
    return INBOX_ID_PREFIX + raw[len(_SP.STABLE_ID_PREFIX) :]


# ───────────────────────────── 时间 ─────────────────────────────


def parse_now(raw: str) -> datetime:
    """--now → aware datetime。裸时间按 Asia/Shanghai 解释（显式偏差 5）。"""
    try:
        dt = datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError as e:
        raise SystemExit(
            f"✗ --now 不是合法 ISO-8601 时刻: {raw!r}（例: 2026-08-31T00:00:00+08:00）"
        ) from e
    return dt if dt.tzinfo else dt.replace(tzinfo=_TZ_SHANGHAI)


def _epoch_s(dt: datetime) -> float:
    return dt.timestamp()


def days_between(now_s: float, then_s: float) -> int:
    """整日年龄。⛔ 先把秒差取**最近整秒**再整除 86400 —— 见显式偏差 6。
    用的是 Python `round`（ties-to-even，不是"半数远离零"）；此处只用于吸收
    文件系统纳秒往返的亚微秒抖动，恰好落在 .5 的秒差在真实 mtime 上不会出现。"""
    return int(round(now_s - then_s)) // 86400


#: 时刻不可表示时的占位（不是"没有时间"，是"这个 mtime 超出日历可表示范围"）。
UNREPRESENTABLE = "unrepresentable"


def _fmt(sec: float, tz, pattern: str) -> str:
    """⛔ 极值 mtime（如被置成 9999 年末，+8h 后溢出到 10000 年）会让
    `datetime.fromtimestamp` 抛 OverflowError —— 一个畸形 mtime 不该炸掉整份 preview。
    与 `scripts/daily_review_pick.py::_sh_local` 同款诚实降级：返回占位串，
    **不**伪造一个看似正常的时间。"""
    try:
        return datetime.fromtimestamp(sec, tz=tz).strftime(pattern)
    except (OverflowError, OSError, ValueError):
        return UNREPRESENTABLE


def fmt_utc(sec: float) -> str:
    return _fmt(sec, timezone.utc, "%Y-%m-%dT%H:%M:%SZ")


def fmt_local(sec: float) -> str:
    return _fmt(sec, _TZ_SHANGHAI, "%Y-%m-%d %H:%M")


# ───────────────────────── 文本解析（确定性） ─────────────────────────


def frontmatter_span(lines: list[str]) -> int:
    """frontmatter 块**占用的行数**（含首尾两条分隔线）；无 / 缺闭合时为 0。

    ⛔ 单独抽出来是因为 `head_window` 需要的是「跳过几行」而不是「里面有几个键」。
    早先版本用 `len(fm) + 2` 反推，遇到**空 frontmatter**（`---` 紧接 `---`）时
    `fm == []` 被当成「没有 frontmatter」，报出的行号就整体偏 2 行 —— 依据里的
    行号是给人核对用的，偏了就等于没有。
    """
    if not lines or lines[0].strip() != "---":
        return 0
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() in ("---", "..."):
            end = i
            break
    if end is None:
        return 0  # 缺闭合 → 视为无 frontmatter
    # ⛔ 还要**真的像** frontmatter（Codex HIGH 实证）：`---\n这是唯一正文\n---`
    # 原先被整段当 frontmatter 吞掉 → 正文为空 → 输出「建议删」。把用户正文误判成
    # 空文件的删除提名，比不提名坏得多。
    for ln in lines[1:end]:
        t = ln.strip()
        if not t or t.startswith("#"):
            continue  # 空行与 YAML 注释不作数
        return end + 1 if _FM_LOOKS_LIKE_KEY_RE.match(ln) else 0
    return end + 1  # 空 frontmatter（`---` 紧接 `---`）


def split_frontmatter(text: str) -> tuple[list[str], list[str]]:
    """→ (frontmatter 行, 其余行)。只认文件头的 `---` 对；缺闭合视为无 frontmatter。"""
    lines = md_splitlines(text)
    n = frontmatter_span(lines)
    return (lines[1 : n - 1] if n else []), lines[n:]


def _clean_fm_value(raw: str) -> str:
    """frontmatter 值清洗：剥行尾 YAML 注释 → 剥成对引号。

    ⛔ 两步缺一不可，且顺序不能反：`source: "https://x" # 官方来源` 若先判引号，
    会因末字符是「源」而走错分支，值带着引号被 URL 判据拒掉，一手来源丢失
    （round-3 自审 H1-6）。
    """
    val = (raw or "").strip()
    val = re.sub(r"\s+#.*$", "", val).strip()
    if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
        val = val[1:-1]
    return val


def frontmatter_pairs(fm_lines: list[str]) -> list[tuple[str, str]]:
    """全部 `key: value` 对，**按出现顺序、不折叠重名键**。

    ⛔ round-2 审查 BLOCKER 的修法：`frontmatter_map` 用 `setdefault` 只留首值，
    于是

        ---
        doi:
        doi: 10.1000/hidden
        ---

    折叠后只剩一个**空**值，所有基于 `fm.items()` 的护栏信号全都扫不到那个 DOI，
    文件被判空骨架确定删除（同形 `url:` 反例同时穿透 C3 与 C4 两个出口）。
    护栏必须看**全部**写下来的行 —— 引擎丢弃了的信息，正是「未消化」的定义。
    ⚠️ 判据侧（C1 取 `fm["source"]`）仍走 `frontmatter_map` 的首值语义，不动：
    改判据取值是有后果的行为变更，不能作为一次护栏加宽的副作用。
    """
    out: list[tuple[str, str]] = []
    for ln in fm_lines:
        m = _FM_KEY_RE.match(ln)
        if m:
            out.append((m.group(1), _clean_fm_value(m.group(2) or "")))
    return out


def frontmatter_map(fm_lines: list[str]) -> dict:
    """顶层 `key: value` 扫描（不引 YAML 依赖；嵌套/列表值不解析，本卡不需要）。
    ⚠️ 重名键取**首值**（既有语义，判据侧依赖它）；护栏侧要看全量请用
    `frontmatter_pairs`。"""
    out: dict[str, str] = {}
    for k, v in frontmatter_pairs(fm_lines):
        out.setdefault(k, v)
    return out


#: ⛔ 第十一轮 HIGH（R11-H1）：`str.splitlines()` 把 U+001C-1E/U+0085/U+2028/
#: U+2029 也当行界，于是围栏内的 U+001D 被改写成换行，`a<U+001D>b` 与 `a\nb`
#: 的 dup_body 相等 → 确定删除。Markdown 的行界只有 \n / \r\n / \r。
#: ⚠️ 这是「按 Markdown 规范判结构却用了 Unicode 语义」的**第三处**，
#: 与开篇 NBSP、第十轮三条同源。分行是最底层的一步，漏了它上面全白做。
_MD_LINE_SPLIT_RE = re.compile(r"\r\n|\r|\n")


def md_splitlines(text: str) -> list[str]:
    """按 **Markdown 行界**分行（只认 \n / \r\n / \r），不用 `str.splitlines()`。"""
    parts = _MD_LINE_SPLIT_RE.split(text)
    if parts and parts[-1] == "":
        parts.pop()  # 末尾换行不产生空行，与 splitlines 语义一致
    return parts


def _classify_lines_typed(text: str) -> tuple[list[tuple[str, str]], bool, list[str]]:
    """→ [((行, 种类), …), 是否结束于未闭合的 HTML 注释, 被注释剥掉过的原文行]。

    种类三态：`"fence"`（围栏分隔行）/ `"code"`（围栏内容）/ `"text"`。
    三态化是因为二态布尔回答不了「围栏**内容**里长得像围栏的行」——
    Markdown 围栏语法速查（```` 里嵌 ``` 与 ~~~）曾被 `has_substantive_content`
    用 `_FENCE_RE` 整体剔除 → 判成空骨架 → 建议删（round-3 自审 B3-3）。
    分隔行由状态机精确标记，内容行一律是内容。

    第二返回值供 C3 护栏（显式偏差 15）使用：`<!--` 没等到 `-->` 就到了 EOF
    时，哪些内容被注释吞掉是引擎猜不了的 —— 这种文件不许被判「空骨架」。

    ⛔ 围栏状态机是 Codex 两条 BLOCKER 的正解。原先没有它：
      - `~~~` 被当成"纯结构行"删掉，围栏里的 `# comment` 又被当成 Markdown 标题删掉，
        于是一份只有一段 shell 代码的文件被判成空骨架 → **建议删**；
      - 而文件头明明声明着"代码块内容留在正文里"。声明与实现对不上就是掩饰。
    注释剥离只作用于围栏外：代码里的 `<!-- -->` 是代码，不是说明。
    """
    _, rest = split_frontmatter(text)
    rows: list[tuple[str, str]] = []
    stripped_comments: list[str] = []
    # ⛔ 第十一轮 HIGH（R11-H2）：分类器此前只有 fence/comment 状态，没有
    # **raw HTML block**。于是 `<pre>` 里的 `# source: https://…` 被当成 ATX
    # 标题丢弃，正文一撞库就确定删除、来源零留痕。CommonMark §4.6 的 HTML block
    # 里没有 Markdown 结构，那些行是字面内容。
    in_html = False
    in_fence = False
    fence_char = ""
    fence_len = 0
    in_comment = False
    for ln in rest:
        m = _FENCE_RE.match(ln)
        if m and not in_comment:
            tok = m.group(1)
            # ⛔ CommonMark 4.4：反引号围栏的 info string **不得含反引号** ——
            # ```foo`bar 不是合法开启行（round-6 BLOCKER-3：该行曾被当开启、
            # 下一行被当关闭、正文再被标题剥掉 → 空骨架建议删）。tilde 围栏
            # 的 info string 允许反引号，不受此限。
            if not in_fence and not (tok[0] == "`" and "`" in ln[m.end() :]):
                in_fence, fence_char, fence_len = True, tok[0], len(tok)
                # ⛔ 第七轮终审 HIGH（R7-H1）：围栏开启行的 **info string**
                # （`~~~ {source=https://…}`）整行被标成 "fence" 后不进正文，
                # 写在那儿的来源静默消失。这是「来源被引擎剥掉」的**第四种写法**
                # （前三种：跨行 HTML 注释 / fm 整行 YAML 注释 / fm 行尾注释）。
                info = ln[m.end() :].strip()
                if info:
                    stripped_comments.append(info)
                rows.append((ln, "fence"))
                continue
            # ⛔ 关闭围栏 = 同字符 **且长度 ≥ 开启长度、围栏后仅 ASCII 空白**
            # （CommonMark 4.5）。只比字符曾让 ```` 里的 ``` 被当关闭、``` 后带
            # info string 的行也被当关闭 —— 围栏内容 `# keep` 落到围栏外被剥，
            # 整份文件被误判成空骨架 → 建议删（round-2 B3 实证）。
            # ⛔ 「仅空白」必须逐字符限 ASCII 空格/制表符：`str.strip()` 接受一切
            # Unicode 空白，行尾一个 U+00A0（网页复制常见）曾让该行被当成合法
            # 关闭围栏 → 围栏提前闭合 → 建议删（round-3 Codex BLOCKER；NBSP 行
            # 在 CommonMark 里是围栏内容）。
            if (
                tok[0] == fence_char
                and len(tok) >= fence_len
                and all(c in " \t" for c in ln[m.end() :])
            ):
                in_fence, fence_char, fence_len = False, "", 0
                rows.append((ln, "fence"))
                continue
        if in_fence:
            rows.append((ln, "code"))
            continue
        # HTML block：`<pre|script|style|textarea>` 起、对应闭合标签止
        # （CommonMark §4.6 type 1 —— 最保守的一种，只认这四个标签）。
        if not in_html and re.match(
            r"^ {0,3}<(?:pre|script|style|textarea)(?:[ \t>]|$)", ln, re.IGNORECASE
        ):
            in_html = True
        if in_html:
            rows.append((ln, "code"))  # 与围栏同待遇：字面内容，不套 Markdown 结构
            if re.search(r"</(?:pre|script|style|textarea)>", ln, re.IGNORECASE):
                in_html = False
            continue
        kept, rem = "", ln
        while rem:
            if in_comment:
                i = rem.find("-->")
                if i < 0:
                    # ⛔ 第五轮终审 HIGH：跨行注释里**中间那些整行**此前没被收集
                    # （只收了闭合那一行的 `rem[:i]`），于是
                    #   <!--
                    #   source: https://…
                    #   -->
                    # 的来源整条丢掉，文件被判空骨架确定删除。单行注释反而受保护。
                    stripped_comments.append(rem)
                    break
                # ⛔ round-4 验证 MEDIUM：收集的必须是**注释内部的内容**。
                # 先前记的是「被剥掉的原文片段」，于是 `<!---->` 这种空注释也
                # 触发信号⑩，把安全方向的少删又扩大了一圈。
                stripped_comments.append(rem[:i])
                rem, in_comment = rem[i + 3 :], False
            else:
                i = rem.find("<!--")
                if i < 0:
                    kept += rem
                    break
                kept += rem[:i]
                rem, in_comment = rem[i + 4 :], True
        rows.append((kept, "text"))
        # ⛔ round-3 审查 HIGH：闭合注释被这里整段剥掉，而来源/生成信号只扫
        # frontmatter，⑨ 兜底也只覆盖 frontmatter —— 于是
        # `<!-- source: https://… -->`、`<!-- DOI:10.1000/… -->`、
        # `<!-- citation: ISBN … -->` 这类「唯一信息写在注释里」的文件
        # C3/C4 双出口全穿。只有**未闭合**注释受保护，闭合的反而不受。
        # 注释内容在上面的闭合分支里逐段收集，与「未闭合注释」对称地作信号。
    return rows, in_comment, stripped_comments


def _classify_lines(text: str) -> list[tuple[str, bool]]:
    """二态视图（该行是否属围栏区），供 `dup_body` 等逐字保真路径使用。
    三态细节见 `_classify_lines_typed`。"""
    return [(ln, kind != "text") for ln, kind in _classify_lines_typed(text)[0]]


def dup_body(text: str) -> str:
    """**逐字保真**的正文形态 —— C4「精确重复」的唯一比对依据。

    只做无语义的归一：丢标题行（围栏外）、行尾空白 rstrip、丢空行、NFC。
    ⛔ **不** `.strip()` 每行、**不**剥列表符号：那会抹掉代码缩进，让
    `if ok:` + 缩进 `run()` 与 `if ok:` + 顶格 `run()` 判成"逐字相等"，
    进而对一份语义完全不同的文件给出「建议删」（Codex BLOCKER 实证）。
    有后果的提名，依据必须逐字。
    ⛔ 标题不进比对：同一段材料被粘两份时标题常不同（R8 判据 4 说的是「正文高相似」）。
    """
    parts: list[str] = []
    for ln, is_code in _classify_lines(text):
        if not is_code and _HEADING_RE.match(ln):
            continue
        # ⛔ 第九轮 HIGH（R9-H1）：此前无条件 `rstrip()` + 丢空行，把**有语义的
        # 空白**一起抹了 —— Markdown 行尾双空格是硬换行、空行是段落边界、围栏
        # 里的空格与空行更是字面内容。于是 `alpha  \nbeta` 与 `alpha\nbeta`
        # 被判「逐字相等」并确定删除。⚠️ 判据名叫「精确重复」，比较形态却是
        # 有损投影 —— 名实不符本身就是缺陷。
        if is_code:
            # 围栏内一律逐字保真（含空行与行尾空格）
            parts.append(nfc(ln))
            continue
        # ⛔ 第十轮 HIGH（R10-H1）：`rstrip()` / `strip()` 是 Unicode 语义，
        # 会把 NBSP 等**有语义的**空白也剥掉，两个 U+00A0 还被改写成两个 ASCII
        # 空格 —— 判据仍在做有损投影。行尾空白只按 ASCII space/tab 处理。
        t = ln.rstrip(" \t")
        if not t.strip(" \t"):
            parts.append("")  # 段落边界是语义，不能丢
            continue
        if len(ln) - len(t) >= 2 and not ln[len(t) :].strip(" \t"):
            t += "  "  # 行尾 ≥2 个 ASCII 空格 = 硬换行，保留其语义
        parts.append(nfc(t))
    return "\n".join(parts)


def has_substantive_content(text: str) -> bool:
    """这份材料有没有**实质正文** —— C3「空 / 空骨架」的唯一依据。

    与 `dup_body` 刻意分家：这里回答「是不是只剩脚手架」，可以激进归一化
    （剥列表符、丢纯结构行）；那里回答「是不是逐字相同」，必须逐字保真。
    合用一个函数正是 Codex BLOCKER 的根因。
    ⛔ 用三态视图：围栏**内容**行（哪怕长得像围栏标记，如 Markdown 围栏语法
    速查里的 ``` 行）都算实质正文；只有状态机标记的分隔行不算
    （round-3 自审 B3-3）。
    """
    for ln, kind in _classify_lines_typed(text)[0]:
        if kind == "code":
            if ln.strip():
                return True  # 围栏内容 = 真实材料（含长得像围栏的行）
            continue
        if kind == "fence":
            continue
        if _HEADING_RE.match(ln):
            # ⛔ 用户裁决（2026-09-02）：**标题里写了字就算实质正文**。
            # 起因是量化取样时发现，`# 微积分基本定理的两种证法` 这种「只写了
            # 标题、正文还没动笔」的日常笔记，在旧口径下是 `建议删 +
            # confident=true` —— 那不是对抗构造，是真实使用场景。
            # 论证与本卡「取消 frontmatter 白名单」逐字同构：标题可能是随手一个
            # 字，也可能是这份材料唯一写下来的东西，引擎分不出，分不出就不该
            # 替用户决定。
            # ⛔ **声明收窄（第五轮终审实测证伪）**：本裁决只关闭 **C3 那一半**。
            # C4 侧 `dup_body()` 仍把标题整行丢掉再比对，所以
            # `# 只有这一份写了母本第37页` + 与库内相同的正文，照样是
            # `C4 建议删 + confident=true` —— 标题里的独有信息随重复件一起没了。
            # 我曾在 commit 里写「顺带关闭了 U+3164/U+2800 那条 BLOCKER」，
            # 那句话**过宽**：隐形字符伪装的标题在 C3 侧确实被接住了，
            # 但只要它带着一段与库内重复的正文，C4 侧照样确定删除。
            # 用户第二次裁决（2026-09-02）：**C4 不跟进** —— 让标题进重复比对会
            # 使「同一段正文粘两份、标题不同」不再算重复（5 件取样只剩 1 件被
            # 识别），而那正是清收件箱最常见的场景。保住重复识别，代价如实登记。
            # ⚠️ 代价如实：C3 的可确定删除面明显收窄（10 件取样从 10 → 5）。
            # ⛔ 第八轮 HIGH 收窄措辞：此前写「只剩五种」并逐一列举 —— 那是
            # **数出来的**，实测还有空围栏、空列表、全空值 frontmatter 同样落
            # C3。**数「剩几种」本身就是过宽的写法**：可达面由判据的性质决定，
            # 不由我列举的完整度决定，列举永远会漏。
            # 准确的说法是性质：`has_substantive_content` 找不到任何一个
            # 「剥掉结构记号后还剩字符」的行时，才判空骨架。
            if _atx_heading_text(ln):
                return True
            continue
        t = _LIST_PREFIX_RE.sub("", ln).strip(" \t")
        if t and not _is_structural_line(t):
            return True
    return False


def skeleton_note(text: str, size: int) -> str:
    """空/骨架的**逐项计数**依据 —— 不是「看起来是空的」而是数出来的。

    ⛔ fences 只数围栏**分隔行**（三态视图），围栏内的空行归入句尾的
    「其余皆空行」—— 原先 `sum(... if c)` 把围栏内空行也算进「代码围栏 N 行」，
    与同一句里的「其余皆空行」不构成划分（round-3 自审 B3-5）。
    """
    if size == 0:
        return "0 字节空文件"
    rows = _classify_lines_typed(text)[0]
    headings = sum(1 for ln, k in rows if k == "text" and _HEADING_RE.match(ln))
    struct = sum(
        1 for ln, k in rows if k == "text" and not _HEADING_RE.match(ln) and ln.strip()
    )
    fences = sum(1 for _, k in rows if k == "fence")
    return (
        f"剥离 frontmatter / HTML 注释后实质正文 0 字符"
        f"（{size} 字节文件：标题 {headings} 行、纯结构行 {struct} 行、"
        f"代码围栏 {fences} 行、其余皆空行或注释）"
    )


def head_window(text: str) -> list[tuple[int, str]]:
    """C2 扫描窗口：frontmatter 行 + 其后前 HEAD_SCAN_LINES 行；返回 (1-based 行号, 原文)。"""
    lines = md_splitlines(text)
    n = frontmatter_span(lines)
    win: list[tuple[int, str]] = [(i + 1, lines[i]) for i in range(min(n, len(lines)))]
    for j, ln in enumerate(lines[n : n + HEAD_SCAN_LINES]):
        win.append((n + j + 1, ln))
    return win


def _norm_ai_line(ln: str) -> str:
    """AI 标记匹配前的行归一：连续空白（含 NBSP 等一切 Unicode 空白）折叠为
    单空格 + casefold。⛔ 大小写/空白变体曾穿透字面量表与裸子串护栏的双层 ——
    `generated by ai`（全小写）、`GENERATED BY AI`、内部 NBSP 形态都曾在无正文
    时掉进 C3 建议删（round-5 审查 BLOCKER-1）。归一化是确定性的，二跑逐字节
    相等不受影响；basis 里的标记文本以归一化形态呈现，行号仍准确。"""
    return " ".join(ln.split()).casefold()


#: 不可见字符：**按 Unicode 类别判定，不枚举**。
#: ⛔ round-3 审查 BLOCKER：上一版写成六个码点的有限表
#: （ZWSP/ZWNJ/ZWJ/WORD JOINER/BOM/SOFT HYPHEN），于是 U+2063 INVISIBLE
#: SEPARATOR 以及 U+200E/200F/061C/034F/FE0F/2062/180E/202E 共 9 个同族**全部
#: 穿透**，C3 与 C4 两个出口都中。这与 round-2 的模型名教训是同一件事：
#: **不可见字符不是一张能数完的表**，判它得按类别而不是按名单。
#:   Cf = 格式字符（零宽空格/连接符/双向控制/不可见分隔符…）
#:   Mn = 非间距标记（VS16、CGJ 这类零宽度记号）
#:   Cc = 控制字符
#: ⚠️ 只用在**护栏匹配面**：剥掉组合记号会改变带重音文本的词形，但护栏只判
#: 「这行像不像生成声明」，方向是更容易命中；产物输出一律走原文，不受影响。
#: ⛔ **类别判定同样不完备，如实登记原理上限**（round-4 验证实测）：
#: `U+3164 HANGUL FILLER`（Lo，字母）与 `U+2800 BRAILLE PATTERN BLANK`（So，符号）
#: 在屏幕上是空白，但 Unicode 把它们归为字母/符号，`isspace()` 也是 False ——
#: 机械上它们就是普通字符。把 Lo/So 整类剥掉会连正常韩文与盲文一起剥，那是
#: 更坏的交易。**「视觉上不可见」需要字形宽度数据才判得了，不是字符属性能决定的**，
#: 因此 `# Genera<U+3164>ted by GPT-4` 这类构造仍会落 C3 建议删。
#: 结构化的兜底得改 C3 对**标题行**的处理（现在标题不算实质正文），那是判据面
#: 的语义变更，超出 CARD-G5-6c 范围 —— 登记待裁决，不在本卡内改。
_INVISIBLE_CATEGORIES = frozenset({"Cf", "Mn", "Cc"})


def _strip_invisible(s: str, repl: str) -> str:
    """把不可见字符替换成 `repl`（`" "` 还原词间分隔；`""` 还原词内断裂）。

    ⛔ round-4 验证 BLOCKER 的一半：**删版必须连空白类一起删**。
    `Genera<U+200A>ted`（HAIR SPACE，Zs）此前只被 `_norm_ai_line` 的 `split()`
    折叠成普通空格，词照样是拆开的 —— 删版不删它，两个变体就都还原不出
    `generated`。
    ⚠️ 但删版**保留 ASCII 空格与制表符**：把它们也删掉，`generated by GPT-4`
    在删版里就成了 `generatedbyGPT-4`，骨架永远认不出，删版等于自废。
    要删的是「看不见、又不是正常词间空格」的那一类 —— Cf/Mn/Cc 加上**非 ASCII**
    的空白（Zs/Zl/Zp，如 HAIR SPACE）。两个变体这才真正互补：
      `Genera<U+200A>ted by GPT-4` → 删版还原出 `Generated by GPT-4`；
      `Generated<U+200A>by GPT-4`  → 换空格版还原出 `Generated by GPT-4`。
    """
    return "".join(
        repl
        if (
            unicodedata.category(c) in _INVISIBLE_CATEGORIES
            or (c.isspace() and c not in " \t")
        )
        else c
        for c in s
    )


def _guard_variants(ln: str) -> tuple[str, str]:
    """护栏归一的**两种**零宽还原，都要试。

    ⛔ round-3 审查 BLOCKER：上一版只做「零宽→空格」，那只对**词间**插入成立
    （`by<ZWSP>GPT` → `by GPT`）。零宽插在**词内部**时（`genera<ZWSP>ted`），
    换空格反而把关键词拆成 `genera ted`，骨架与标记表一起失效 —— 比不处理更糟。
    两种还原互补，没有哪一种单独够用：
      · 换空格：还原词间分隔（`by<ZWSP>GPT` → `by gpt`）；
      · 直接删：还原词内断裂（`genera<ZWSP>ted` → `generated`）。
    调用方对两个变体分别匹配，任一命中即算 —— 护栏宁可宽。
    """
    return (
        _norm_ai_line(_strip_invisible(ln, " ")),
        _norm_ai_line(_strip_invisible(ln, "")),
    )


def _norm_guard_line(ln: str) -> str:
    """**护栏专用**归一：先把零宽字符换成空格，再走 `_norm_ai_line`。

    ⛔ 刻意与 C2 判据用的 `_norm_ai_line` 分家，不是图省事：C2 命中意味着
    「AI 自述 · 确定归档 · confident=true」，是**有后果的提名**，扩大它的命中面
    必须是明写的决定；护栏只降 C6，宽一点的代价仅是少几条「建议删」。
    两者混用等于让一次护栏加宽顺带扩大确定提名面。

    ⚠️ **承重面如实声明**（round-2 负控 M-ZEROWIDTH 实测，别高估这一层）：
    回退本函数后套件**一门都不红**，因为 `Generated by<ZWSP>GPT-4` 与
    `本文由<ZWSP>X<ZWSP>生成` 在 `_norm_ai_line` 下**已经**命中骨架 ——
    `_GEN_CLAIM_EN_RE` 的非词字符段会吃掉零宽（Cf 类不算词字符），
    `_GEN_CLAIM_CN_RE` 的非句读字符类同样吃它。一条修法顺手覆盖了另一条。
    本函数真正承重的只有 `raw_ai_marker`：零宽插在标记表项**中间**时
    （`Generated by<ZWSP>AI Lab`、`由<ZWSP>AI<ZWSP>生成`），不剥零宽就匹配不到
    表项，ai_suspect 信号哑火，材料改由靠后的 gen_claim 接住。
    ⚠️ 所以它是一层**理由质量**而非安全底线：两种情况下材料都不会被删，
    差别只在 `uncertain_reason` 说的是「疑似 AI 自述」还是「生成断言结构」。
    留着它是因为前者对人更有用；但不要把它写成安全防线。
    """
    return _norm_ai_line(_strip_invisible(ln, " "))


#: 归一化后的标记表（模块级算一次；全大写字母 ascii_ending 判定与原表一致）。
_AI_MARKERS_NORM = tuple(" ".join(m.split()).casefold() for m in AI_MARKERS)

#: ⛔ 护栏级 AI 信号（结构性，不依赖枚举表）：文本含独立「AI」字样即算嫌疑。
#: 「独立」= 左右都**不是 ASCII 字母**（`\bAI\b` 在 CJK 邻接时无词边界 ——
#: round-7 BLOCKER-1：`由AI系统生成` 曾穿透）。有限标记表无论怎么扩都追不上
#: 自然语言的肯定式声明（round-6 BLOCKER-1：`This report was generated by an
#: AI system` 不含任何表项，双层全盲，无正文时掉进 C3 建议删）。本信号只降
#: C6 不裁决 —— C2 确定命中仍走有限表 + 边界规则（宽匹配会给话题提及发确定
#: 归档，那是硬猜）。
_AI_WORD_RE = re.compile(r"(?<![A-Za-z])AI(?![A-Za-z])", re.IGNORECASE)

#: ⛔ 护栏级**生成断言结构**（round-8 BLOCKER-2）：`generator: 由 GPT-4 生成`
#: 里既没有表项（表只收到 `由 GPT 生成`，`GPT-4` 差一个版本号）也没有独立词
#: 「AI」，三层护栏全盲 → 无正文时掉进 C3 `建议删 + confident=true`。
#: 修法按**声明骨架**而不是**枚举模型名**（卡文 §3 默认裁决）：模型名是开放
#: 集合，`GPT-4` 之后还有 `GPT-4o`/`Claude 3.5`/`Gemini 2.5`/下个月发布的那个，
#: 枚举永远追不上；「由 <某物> 生成」这个断言骨架是闭合的。
#: ⚠️ 只作**未消化信号降 C6**，绝不进 C2：宽匹配给话题提及发确定归档就是硬猜
#: （`由编译器生成`、`generated by hand` 都会命中本条 —— 它们降 C6，方向安全）。
#: 中文：`由` 与 `生成` 之间任意个**非句读**字符（句读收尾防跨句吞成假断言）。
#: ⛔ round-2 审查 BLOCKER：原先写 `{1,40}?` 加了长度上界，于是
#: `本文由 openai-gpt-oss-120b-finetune-canvas-learning-system-v2026-09-01 生成`
#: （中间 65 字符）穿透 —— **上界本身就是缝隙**，而当初说「断言骨架是闭合的」
#: 正因为这个上界而不成立。去掉上界后骨架才真的闭合（同一行、中间不跨句读）。
#: 放宽的代价是 `由于…最终生成了报告` 这类也会命中，但那只降 C6（拿不准、不删），
#: 误命中方向安全 —— 用一点召回换掉一条确定删除的路径，是划算的。
_GEN_CLAIM_CN_RE = re.compile(r"由[^。；！？\n]*?生成")
#: 英文：在归一（连续空白折叠为单空格 + casefold）后的行上匹配，故只写单空格。
#: ⛔ round-2 审查 BLOCKER：原先写 `generated by \S`（字面空格 + 非空），于是
#: `Generated by: GPT-4` 穿透 —— `by` 后面是冒号不是空格。改为 `by` 词边界后
#: 允许任意非词字符（冒号/破折号/空格）再要求一个词字符：
#: ⛔ round-3 审查 HIGH：上一版写 `generated by\b\W*\w`，而 `_` 属于 `\w` ——
#: `Generated by_GPT-4` 的 `by` 与 `_` 之间**没有**词边界，整条穿透（C3 与 C4
#: 两个出口都中）。词边界这个概念在这里本来就不对：要判的是「by 是不是一个
#: 完整的词」，直接写成「后面不是字母数字」才准确，分隔符则连下划线一起吃。
#:   `generated by: gpt-4` ✅ / `generated by llama` ✅ / `generated by_gpt-4` ✅
#:   / `generated byte` ❌（by 后面是字母）/ 行尾 `generated by` ❌（没有主语）
_GEN_CLAIM_EN_RE = re.compile(r"generated by(?![^\W_])[\W_]*[^\W_]")

#: ⛔ 护栏级**生成器声明字段**（round-8 BLOCKER-2 的另一半）：键名本身就是声明。
#: `generator: gpt-4`（值里没有「生成」二字）只有本条能接住，`本文由 GPT-4 生成`
#: 写在正文里（无 frontmatter）只有 `_GEN_CLAIM_*` 能接住 —— 两条互补，都不冗余。
#: 键名归一口径见 `_norm_fm_key`。
_GENERATOR_DECL_KEYS = frozenset(
    {"generator", "generated_by", "ai_generated", "model", "llm", "ai"}
)

#: ⛔ 来源声明键别名（round-8 HIGH）：`Source: DOI:10.1000/xyz` 的唯一来源标识
#: 曾被当作不存在 —— `"source" in fm` 是**大小写敏感**的字面查找，取不到 `Source`；
#: 而值不含 `http(s)://`，`url_bearing_keys` 也接不住。⚠️ 本别名集合只用于
#: **护栏**：C1 仍只认字面小写 `source` 键（R8 稿约定），DOI 更不冒充 URL 或 C1
#: （卡文 §3 默认裁决）—— 信号只把来源摆上台面降 C6，不给出「留原地/一手」提名。
_SOURCE_DECL_KEYS = frozenset({"source", "sources"})

#: ⛔ C3「空骨架」的兜底口径**两轮才收敛到位**，过程记在这里以免后人重走：
#:
#: round-2 审查 HIGH 先逼出**方向反转**：此前所有来源护栏都在枚举「危险的键名和
#: 值形态」（source/url/doi…），那是 fail-open —— 漏一个就是一条确定删除的路径，
#: 而 `citation: ISBN 978-7-111-54742-6` 正好两样都不沾，被判 C3 确定删除。
#: 于是改成枚举「已知无害、删掉不丢信息」的键名白名单，默认拦住。
#:
#: round-3 审查 HIGH 又把那份白名单打穿：**放行的是键名，可信息在值里**。
#: `title: ISBN 978-…`、`aliases: <馆藏号>`、`title: <这份材料仅有的那句话>`
#: 全都因为键名在白名单而被判 C3 确定删除；C4 侧更直接 —— 引擎自己挂着
#: 「正文重复证据不覆盖这些元数据」的冲突，却仍然 confident=true。
#: **「这个键名无害」是个无法机械成立的断言**：`title` 可能是一句 t，也可能是
#: 这份材料唯一写下来的东西，引擎分不出来，分不出来就不能替用户决定。
#:
#: 现口径（信号⑨）：**frontmatter 里只要有任何非空值，C3/C4 就不确定删除**。
#: 白名单整个取消 —— 不是收窄，是这条路本身走不通。
#: ⚠️ 代价如实说：C3 的可达面明显变窄，只剩「0 字节」「没有 frontmatter 的纯
#: 骨架」「frontmatter 全是空值」三种。这是刻意选的偏向 —— 少删一份的代价是
#: 用户多看一眼，多删一份的代价是材料没了。
#: 依据是卡文 §3 默认裁决「未知结构或来源信号至少降级 C6」。

#: DOI 形态（ISO 26324：`10.<registrant>/<suffix>`）。左界排除字母数字与点，
#: 于是 `DOI:10.1000/xyz`、`doi: 10.1000/xyz`、裸 `10.1000/xyz` 都命中，而
#: 版本号 `v10.1000/x` 之类不命中。⚠️ 只作来源信号，不解析、不解引用、不联网。
_DOI_RE = re.compile(r"(?<![0-9A-Za-z.])10\.\d{4,9}/[^\s\"'<>]+")


def _norm_fm_key(k: str) -> str:
    """frontmatter 键名归一：casefold + `-`→`_`。

    ⛔ 仅供**护栏**的键名比对（`Source`/`SOURCE`/`generated-by` 与
    `source`/`generated_by` 同判）。判据侧（C1）刻意不走这里 —— 那会静默扩大
    C1 的命中面，而 C1 命中意味着「一手来源 · 留原地 · confident=true」，
    是有后果的提名，扩它必须是明写的决定而不是归一化的副作用。
    """
    return k.casefold().replace("-", "_")


#: ISBN-10 / ISBN-13：`ISBN` 前缀（可选）+ 9-13 位数字/连字符，末位可为 X。
#: ⛔ 与 DOI 同源的**正面形态**判定，不是枚举关键词：ISBN 有固定位数与校验位，
#: 这是它「像个标识符」的结构证据。用于文件名与值两处来源信号。
_ISBN_RE = re.compile(
    r"(?<![0-9A-Za-z])(?:ISBN[-\s_:]*)?(?=[\d-]{9,17}[\dXx](?![\d-]))[\d-]{9,17}[\dXx]",
    re.IGNORECASE,
)


def _looks_like_isbn_value(v: str) -> bool:
    """值/文件名里含 ISBN 形态的标识符（非空才算）。"""
    if not v:
        return False
    m = _ISBN_RE.search(v)
    if not m:
        return False
    digits = [c for c in m.group(0) if c.isdigit() or c in "Xx"]
    return len(digits) in (10, 13)


def _looks_like_doi_value(v: str) -> bool:
    """值里含 DOI 形态的来源标识（⛔ substring 级，与 `_looks_like_source_value`
    同口径）。非空才算 —— 卡文 (d) 要的是「**非空** DOI 来源阻止 C3 删除」。"""
    return bool(v) and bool(_DOI_RE.search(v))


def find_generation_claim(text: str) -> str | None:
    """文头窗口内的**生成断言结构**片段（归一化匹配），无则 None。

    ⛔ 只作 C3/C4 的「未消化信号」，不作 C2 判据 —— 见 `_GEN_CLAIM_CN_RE` 头注。
    返回归一化后的命中片段（casefold + 空白折叠），供 uncertain_reason 展示；
    ⚠️ 它是**归一形态**不是输入原文，措辞里如实这么说（round-8 §四对
    「basis 带逐字片段」的证伪同源教训：写「逐字」就必须真的逐字）。
    """
    for _, ln in head_window(text):
        for norm in _guard_variants(ln):
            for rx in (_GEN_CLAIM_CN_RE, _GEN_CLAIM_EN_RE):
                m = rx.search(norm)
                if not m:
                    continue
                # ⛔ round-2 审查 LOW：英文骨架以单个词字符收尾，直接 group(0) 只给到
                # `generated by l` —— 人工核对时看不出是哪个模型。补到该词结束。
                end = m.end()
                while end < len(norm) and (norm[end].isalnum() or norm[end] in "-_.:"):
                    end += 1
                return norm[m.start() : end]
    return None


def _find_marker_pos(ln: str, marker: str) -> int:
    """marker 在**已归一**的 ln 中第一个满足右边界规则的起点；无则 -1。

    ⛔ 右边界 = 行尾、空白或 `_MARKER_BOUNDARY_PUNCT` 标点（round-2 H2）：裸子串
    匹配曾把 `# 由 AI 生成内容的版权问题` 这类话题提及判成 AI 自述并给出确定的
    归档去向。同一行里前一处命中不满足边界时继续向后找 —— 不因首处被拒就漏掉
    行内更靠后的真命中。
    ⛔ 以 ASCII 字母收尾的标记（`Generated by AI`）右边界**不含空白**：中英混排里
    ASCII 词后天然是空格，放行空白等于边界规则对这些标记是空操作 ——
    `Generated by AI Lab researchers` 会被误判成 AI 自述（round-3 自审 H2-1）。
    只认行尾或标点；漏判方向落 C6，安全。"""
    ascii_ending = marker[-1].isascii() and marker[-1].isalpha()
    start = 0
    while (i := ln.find(marker, start)) >= 0:
        j = i + len(marker)
        if j >= len(ln) or ln[j] in _MARKER_BOUNDARY_PUNCT:
            return i
        if not ascii_ending and ln[j].isspace():
            return i
        start = i + 1
    return -1


def find_ai_marker(text: str) -> tuple[int, str] | None:
    """文头窗口内的 AI 标记（归一化匹配：大小写/空白变体不漏，round-5 BLOCKER-1；
    右边界规则见 `_find_marker_pos`）。同行多命中时取「最靠前、同位置取最长」。
    ⛔ 返回的 marker 是**原表原文**（供 basis 逐字展示），匹配在归一化形态上做
    —— 行号准确，文本保真。"""
    for lineno, ln in head_window(text):
        norm = _norm_ai_line(ln)
        hits = [
            (pos, -len(nm), orig)
            for nm, orig in zip(_AI_MARKERS_NORM, AI_MARKERS)
            if (pos := _find_marker_pos(norm, nm)) >= 0
        ]
        if hits:
            _, _, marker = min(hits)
            return lineno, marker
    return None


def raw_ai_marker(text: str) -> str | None:
    """文头窗口内的**裸子串** AI 字样（归一化匹配，不做边界检查）—— 只用作
    C3/C4 的「未消化信号」，不作 C2 判据。边界规则拒掉的命中（如 `Generated
    by AI on March`）说明这行有 AI 自述嫌疑但引擎不敢确定；这样的文件若又
    没有实质正文，判「空骨架建议删」就是把嫌疑当垃圾扔（round-4 BLOCKER-1）。
    返回原表原文（uncertain_reason 展示用）。
    ⛔ 走 `_norm_guard_line`（比 C2 判据多剥零宽）—— 护栏宽、判据不动。"""
    for _, ln in head_window(text):
        for norm in _guard_variants(ln):
            for nm, orig in zip(_AI_MARKERS_NORM, AI_MARKERS):
                if nm in norm:
                    return orig
    return None


def round_of(name: str) -> str | None:
    m = _ROUND_RE.search(name)
    return m.group(1) if m else None


def round_type(name: str) -> str | None:
    for pat, typ in ROUND_SUBPATTERNS:
        if pat in name:
            return typ
    return None


# ───────────────────────────── 扫描 ─────────────────────────────


def read_text_or_none(p: Path) -> str | None:
    try:
        return p.read_bytes().decode("utf-8")
    except (OSError, UnicodeDecodeError):
        return None


def scan_corpus(
    vault: Path, excluded_roots: list[str]
) -> tuple[dict[str, list[str]], list[tuple[str, str]], dict]:
    """库内 .md 语料：→ (归一化正文 → [相对路径…], [(路径, 正文)…], 统计)。

    排除：一切隐藏目录、`outputs/`、收件箱子树、产物目录子树。
    ⛔ **空正文不进重复索引** —— 否则库内任意两个空骨架互为「正本」，会撑出一条
    有后果的建议删，其证据是「两个都是空的」。C3 虽然先命中，但索引本身必须先干净：
    门要防的是未来次序调整时的静默失效，不只是当下这一次。
    """
    by_body: dict[str, list[str]] = {}
    bodies: list[tuple[str, str]] = []
    stats = {
        "files_scanned": 0,
        "files_indexed": 0,
        "skipped_empty_body": 0,
        "skipped_symlink": 0,
        "skipped_unreadable": 0,
        "truncated": False,
        "file_cap": CORPUS_FILE_CAP,
    }
    for dirpath, dirnames, filenames in os.walk(vault):
        dirnames[:] = sorted(
            d
            for d in dirnames
            if not d.startswith(".")
            and d not in CORPUS_EXCLUDED_DIR_NAMES
            and os.path.realpath(os.path.join(dirpath, d)) not in excluded_roots
        )
        for fn in sorted(filenames):
            if not fn.endswith(".md"):
                continue
            if stats["files_scanned"] >= CORPUS_FILE_CAP:
                # ⛔ 不在此处 return —— 早退会绕过下面的排序尾巴, 让"截断"与"未截断"
                # 两条路径产出形态不同的索引。置位后跳出全部循环, 走同一个出口。
                stats["truncated"] = True
                dirnames.clear()
                break
            p = Path(dirpath) / fn
            stats["files_scanned"] += 1
            if p.is_symlink():
                stats["skipped_symlink"] += 1
                continue
            text = read_text_or_none(p)
            if text is None:
                stats["skipped_unreadable"] += 1
                continue
            if not has_substantive_content(text):
                stats["skipped_empty_body"] += 1
                continue
            body = dup_body(text)
            if not body:
                stats["skipped_empty_body"] += 1
                continue
            rel = p.relative_to(vault).as_posix()
            by_body.setdefault(body, []).append(rel)
            bodies.append((rel, body))
            stats["files_indexed"] += 1
        if stats["truncated"]:
            break
    for v in by_body.values():
        v.sort()
    bodies.sort()
    return by_body, bodies, stats


def near_duplicates(
    body: str, corpus_bodies: list[tuple[str, str]], scan: dict
) -> list[dict]:
    """difflib 近似（按行比对）。⛔ 只标疑似，永不裁决 —— 见显式偏差 1。"""
    if not body:
        return []
    a_lines = body.split("\n")
    la = len(body)
    hits: list[tuple[float, str]] = []
    for rel, other in corpus_bodies:
        if other == body:
            continue  # 逐字相等归 C4，不重复计入疑似
        lb = len(other)
        if la > NEAR_DUP_BODY_CHAR_CAP or lb > NEAR_DUP_BODY_CHAR_CAP:
            scan["skipped_oversize"] += 1
            continue
        if not (1 / NEAR_DUP_LEN_RATIO <= (lb / la if la else 0) <= NEAR_DUP_LEN_RATIO):
            scan["skipped_length_prefilter"] += 1
            continue
        scan["compared_pairs"] += 1
        sm = difflib.SequenceMatcher(None, a_lines, other.split("\n"), autojunk=False)
        if sm.real_quick_ratio() < NEAR_DUP_RATIO or sm.quick_ratio() < NEAR_DUP_RATIO:
            continue
        r = sm.ratio()
        if r >= NEAR_DUP_RATIO:
            hits.append((r, rel))
    hits.sort(key=lambda x: (-x[0], x[1]))
    return [{"path": rel, "ratio": round(r, 4)} for r, rel in hits[:NEAR_DUP_TOP_N]]


# ───────────────────────── 逐份提名（判据次序即本函数结构） ─────────────────────────


def nominate(
    item: dict,
    text: str | None,
    dup_index: dict[str, list[str]],
    corpus_bodies: list[tuple[str, str]],
    scan: dict,
    batch_body_counts: dict[str, int],
) -> dict:
    """对一件材料出提名。**次序即 CRITERIA_ORDER**，先命中者定 verdict；
    后续判据的证据仍全量附上（conflicts / exact_duplicate_of / near_duplicates）。"""
    name = item["name"]
    conflicts: list[dict] = []

    if text is None:
        # 非 UTF-8（PDF/图片等）：除 0 字节外无任何可机械判读的信号 → 不猜。
        if item["size_bytes"] == 0:
            return _fill(
                item,
                "C3_empty_or_skeleton",
                V_DELETE,
                None,
                None,
                "0 字节空文件",
                True,
                conflicts=conflicts,
            )
        return _fill(
            item,
            "C6_undecided",
            V_UNSURE,
            None,
            None,
            "非 UTF-8 文本，本引擎不解析其正文",
            False,
            uncertain_reason="非 UTF-8 文本（如 PDF / 图片），六判据中除「0 字节」外无一可施加",
            ask=UNDECIDED_ASK,
            conflicts=conflicts,
        )

    fm_lines = split_frontmatter(text)[0]
    fm = frontmatter_map(fm_lines)
    # ⛔ 护栏一律扫**不折叠**的全量键值对（round-2 审查 BLOCKER：重复键遮蔽）。
    fm_pairs = frontmatter_pairs(fm_lines)
    typed_rows, unclosed_comment, stripped_comments = _classify_lines_typed(text)
    del typed_rows
    substantive = has_substantive_content(text)
    body = dup_body(text) if substantive else ""
    rnd = round_of(name)
    # C3 护栏信号（显式偏差 15）：frontmatter 里「看着像键但不被键正则认」的行。
    unparsed_fm = [
        ln.strip()
        for ln in fm_lines
        if ln.strip() and not ln.strip().startswith("#") and not _FM_KEY_RE.match(ln)
    ]
    # ⛔ 第五轮终审 HIGH：frontmatter 里的 YAML 注释行（`# source: https://…`）
    # 被上面的 `startswith("#")` 当注释跳过，既不进 unparsed_fm 也不进 map ——
    # 唯一来源写在那儿的文件照样被判空骨架确定删除。与信号⑩同源（引擎剥掉了
    # 内容就该说出来），故并入同一条信号，不新开一条。
    # ⛔ 第六轮终审 HIGH（R6-H1）：**行尾** YAML 注释同样被剥掉且没人收 ——
    # `title: "" # source: https://…` 的唯一来源静默消失，C3/C4 双出口全穿。
    # 与整行注释、跨行 HTML 注释是同一件事：**引擎剥掉了内容就该说出来**。
    # 剥注释的口径与 `_clean_fm_value` 逐字同源（`\s+#` —— 要求 `#` 前有空白，
    # 免得把值里的 `#` 当注释），两处不同判就会又出现一个「看写法决定保护」的缝。
    fm_comment_lines = [
        ln.strip() for ln in fm_lines if ln.strip().startswith("#") and ln.strip("# \t")
    ] + [
        m.group(1).strip()
        for ln in fm_lines
        if not ln.strip().startswith("#")
        and (m := re.search(r"\s+#\s*(.+?)\s*$", ln))
        and m.group(1).strip()
    ]
    # 未消化信号之四：边界规则拒掉的 AI 自述嫌疑（裸子串在场即算，见 raw_ai_marker）。
    ai_suspect = raw_ai_marker(text)
    # 未消化信号之六（round-6 BLOCKER-1）：独立词「AI」结构性信号 —— 不依赖
    # 枚举表，frontmatter 值或文头任一行含独立词 AI 即算嫌疑。
    ai_word_hit = next(
        (
            v
            for v in [*(v for _, v in fm_pairs), *[ln for _, ln in head_window(text)]]
            if _AI_WORD_RE.search(v)
        ),
        None,
    )
    # 未消化信号之七（round-8 BLOCKER-2）：生成断言结构「由 X 生成」/
    # 「generated by X」—— 不枚举模型名，见 `_GEN_CLAIM_CN_RE` 头注。
    gen_claim = find_generation_claim(text)
    # 未消化信号之八（round-8 BLOCKER-2 的另一半）：生成器声明键名本身。
    generator_pairs = [
        (k, v) for k, v in fm_pairs if _norm_fm_key(k) in _GENERATOR_DECL_KEYS
    ]

    # ── 后置证据（不参与次序，但必须全量呈现） ──
    exact_all = sorted(dup_index.get(body, [])) if body else []
    exact_of = exact_all[0] if exact_all else None
    exact_others = exact_all[1:]
    near = near_duplicates(body, corpus_bodies, scan)
    within_batch = bool(body) and batch_body_counts.get(body, 0) > 1
    if within_batch:
        conflicts.append(
            {
                "kind": "duplicate_within_batch",
                "detail": "本批内另有正文逐字相同的材料 —— 谁是正本在只读侧不可判，"
                "故不产出建议删，请你指定保留哪一份",
            }
        )

    def finish(criterion, verdict, ntype, target, basis, confident, **kw):
        if exact_of and criterion != "C4_exact_duplicate":
            conflicts.append(
                {
                    "kind": "exact_duplicate_under_other_verdict",
                    "detail": f"正文与 {exact_of} 逐字相同，但按判据次序本件归 {criterion}"
                    "（次序不因重复而改变，证据在此留痕）",
                }
            )
        if near and criterion != "C6_undecided":
            conflicts.append(
                {
                    "kind": "near_duplicate_suspected",
                    "detail": "疑似与 "
                    + "、".join(f"{n['path']}(ratio {n['ratio']})" for n in near)
                    + " 高相似 —— 疑似不改提名、更不建议删，需你一句话确认",
                }
            )
        return _fill(
            item,
            criterion,
            verdict,
            ntype,
            target,
            basis,
            confident,
            exact_of=exact_of,
            exact_others=exact_others,
            near=near,
            conflicts=conflicts,
            **kw,
        )

    # ── C1 source URL ──
    src = fm.get("source", "")
    if src and _is_primary_source_url(src):
        return finish(
            "C1_source_url",
            V_STAY,
            "primary-record",
            None,
            f"frontmatter source 为一手 URL：{src}",
            True,
        )

    # ── C2 AI 自述 ──
    hit = find_ai_marker(text)
    if hit:
        lineno, marker = hit
        target = f"R{rnd}/" if rnd else DR_TARGET
        return finish(
            "C2_ai_self_declared",
            V_ARCHIVE,
            "secondary-synthesis",
            target,
            f"文头第 {lineno} 行自述「{marker}」"
            + (f"；文件名带 R{rnd}_ 故归轮次目录" if rnd else ""),
            True,
        )

    def _looks_like_source_value(v: str) -> bool:
        """来源声明判定（⛔ substring 级，不要求可机判合法）：值内**任意位置**
        含 `http://` 或 `https://` 即算 —— 前缀判定曾连环穿透：损坏 URL
        （`https://:443/x`，round-5）、autolink 角括号（`<https://…>`，round-6）、
        YAML 标签（`!!str https://…`）与引号包 Markdown 链接（`"[来源](https://…)"`
        —— round-7 BLOCKER-3）。大小写不敏感。"""
        t = v.casefold()
        return "http://" in t or "https://" in t

    # 信号③b：非 source 键名但值是 URL 形态（url:/URL:/Source: 等剪藏工具
    # 常见键名 —— round-5 自审 F2 实证它们曾穿透全部信号被建议删且 URL 零留痕；
    # 值损坏的别名见 `_looks_like_source_value`）。
    # 合法 source 键在此不可能出现（C1 已先行返回）。⚠️ C1 仍只认字面 source 键
    # （R8 稿约定）；本信号只把这类来源摆上台面降 C6，不扩大 C1。
    url_bearing_pairs = [
        (k, v) for k, v in fm_pairs if v and _looks_like_source_value(v)
    ]
    # 信号③a'（round-8 HIGH）：`source` 键名的**大小写/连字符变体**。原实现只查
    # 字面小写 `source`，于是 `Source: DOI:10.1000/xyz` 的唯一来源标识被当作
    # 不存在并 confident 删除。⚠️ 归一只作用于护栏，C1 不动（见 `_norm_fm_key`）。
    source_alias_pairs = [
        (k, v) for k, v in fm_pairs if _norm_fm_key(k) in _SOURCE_DECL_KEYS
    ]
    # 信号③c（round-8 HIGH）：值是 DOI 形态的来源标识（`identifier:` 之类
    # 不在别名表的键名靠它接住）。DOI 不是 URL —— 文案分列，不冒充。
    doi_bearing_pairs = [
        (k, v)
        for k, v in fm_pairs
        if _looks_like_doi_value(v) or _looks_like_isbn_value(v)
    ]
    slept_pairs = [(k, v) for k, v in fm_pairs if _norm_fm_key(k) == "slept_at"]
    # 兜底信号⑨（round-2 方向反转 → round-3 取消白名单，见上方常量段的两轮记录）：
    # frontmatter 里**任何非空值**都算引擎没消化的独有信息。`citation: ISBN …`、
    # `title: <这份材料唯一写下来的那句话>`、长模型名、`Generated by:` 与零宽变体
    # 全部由它兜住 —— 具体信号只负责给出更好的理由，安全底线在这一条。
    # ⛔ 第八轮 HIGH：⑨ 只看**值**，于是把信息写进**键名**（`ISBN_978-…:` 空值）
    # 的形态整条穿透。信息在键名还是在值里，对「引擎没消费它」这件事毫无区别。
    # 判据：键名不在引擎已知集合里（不是它消费过的那些）且看着像编号/标识 ——
    # 直接判「键名非引擎已知」最简单也最不容易再漏。
    _KNOWN_FM_KEYS = frozenset(
        {
            "title",
            "tags",
            "tag",
            "aliases",
            "alias",
            "created",
            "updated",
            "modified",
            "date",
            "cssclass",
            "cssclasses",
            "publish",
            "draft",
            "source",
            "sources",
            "url",
            "doi",
            "slept_at",
            "generator",
            "model",
            "llm",
            "ai",
        }
    )
    unknown_value_pairs = [(k, v) for k, v in fm_pairs if v] + [
        (k, "（值为空，信息在键名里）")
        for k, v in fm_pairs
        if not v and _norm_fm_key(k) not in _KNOWN_FM_KEYS
    ]
    # 未消化信号⑩（round-3 审查 HIGH）：被**闭合** HTML 注释剥掉的原文行。
    # ⚠️ 与①（未闭合注释）对称：①保护的是「不知道被吞了什么」，⑩保护的是
    # 「知道被吞了什么，但引擎没消费它」。此前只有①有保护，于是把唯一来源
    # 写在闭合注释里的文件 C3/C4 双出口全穿。只收**注释里有非空内容**的行。
    commented_out = [ln for ln in stripped_comments if ln.strip()] + fm_comment_lines
    # ⛔ 第九轮 HIGH（R9-H2）：文件名进了 item，但护栏一条都不看它 —— 于是
    # `ISBN_978-7-111-54742-6.md`、`DOI_10.1000_xyz.md` 这类**唯一来源写在文件名
    # 里**的材料，正文一撞上库内某份就被确定删除，文件名里的标识零留痕。
    # 判据与既有来源信号同源（URL / DOI 形态），只是扫描面加上文件名。
    # ⚠️ 用模块级判据，不用 judge() 内那个同名闭包 —— 它定义在本行之后。
    # 文件名里的分隔符常被换成 `_`（`DOI_10.1000_xyz.md`、
    # `source_https_example.test_article.md`），故把 `_` 还原成 `:` 与 `/` 各试一遍。
    _stem = name[:-3] if name.endswith(".md") else name
    name_signal = next(
        (
            _stem
            for probe in (
                _stem,
                _stem.replace("_", ":"),
                _stem.replace("_", "/"),
                _stem.replace("_", ":", 1).replace("_", "/"),
                # ⛔ 第十轮 HIGH（R10-H2）：文件名里一个 `_` 常代表整个 `://`
                # （`source_https_example.test_article.md`）。上面几种还原都还不出
                # `https://`，故显式补一条 scheme 还原。
                # ⚠️ 不能写 `\b(https?)` —— `_` 是词字符，`source_https` 里
                # `https` 前后都没有词边界，那条正则一次也匹配不上（实测）。
                re.sub(r"(?i)(?<![a-z])(https?)[_:]+[/]*", r"\1://", _stem),
                # ⛔ 第十一轮 HIGH（R11-H4）：percent-encoded 的文件名
                # （`source_https%3A%2F%2Fexample.test_article.md`）此前全穿。
                # ⚠️ 用 unquote 而不是再加一条替换规则 —— percent 编码是**有标准**
                # 的，标准解码比枚举替换可靠，这是本卡「开放集合不能枚举、
                # 有结构的可以正面解」的又一次应用。
                unquote(_stem),
                unquote(_stem).replace("_", ":", 1),
            )
            # ⛔ 第十轮 HIGH（R10-H2）：此前用**锚定**的 `_URL_RE.match`，于是
            # `source_https_example.test_article.md` 这类带前缀的文件名，四个
            # probe 都不以 http 开头，整条穿透。文件名是自由拼出来的，判定必须
            # 是 substring 级 —— 与 `_looks_like_source_value` 同口径。
            if (
                "http://" in probe.casefold()
                or "https://" in probe.casefold()
                or _looks_like_doi_value(probe)
                or _looks_like_isbn_value(probe)
            )
        ),
        None,
    )

    def undigested_reason() -> str | None:
        """⛔ 「未消化信号」统一护栏（显式偏差 15）：C3/C4 是仅有的两个产出
        「建议删」的判据，命中时若文件带有引擎未能完全消化的结构信号 ——
        未闭合注释 / 解析不成的 frontmatter 行 / 来源声明（source 键或任意
        URL 形态键值）/ 睡眠台账键 / AI 自述嫌疑 —— 一律降 C6 拿不准。
        判据收窄漏掉的文件曾掉进这两个判据被建议删（round-3 自审 H1-1/H3-1 +
        round-4 BLOCKER-1/BLOCKER-2 + round-5 自审 F2/F3 实证）；
        「安全」是路径属性：必须拦在两个出口，而不是只拦 C3。"""
        if unclosed_comment:
            return "文件以未闭合的 HTML 注释结尾（`<!--` 没等到 `-->`），哪些内容被吞掉引擎猜不了"
        if unparsed_fm:
            return (
                f"frontmatter 含本引擎无法解析为键的行（如 {unparsed_fm[0]!r}），"
                "解析不完整"
            )
        if source_alias_pairs:
            k, v = source_alias_pairs[0]
            return (
                f"frontmatter 声明了 {k}（{v!r}）但不是可机判的"
                "一手 URL —— 来源声明还在，不能当它不存在"
            )
        # ⚠️ URL 在 DOI 之前（自审 S1）：`url: https://doi.org/10.1000/xyz` 两条都
        # 命中，但它**是个网址**（DOI 解析链接）；报成「DOI 来源标识」并附上
        # 「引擎不解引用 DOI」的免责就不准确。更具体的判定先说话。
        if url_bearing_pairs:
            k, v = url_bearing_pairs[0]
            return (
                f"frontmatter 的 {k} 键声明了一个来源 URL"
                f"（{v!r}）—— 来源声明还在，不能当它不存在"
            )
        if doi_bearing_pairs:
            k, v = doi_bearing_pairs[0]
            return (
                f"frontmatter 的 {k} 键声明了一个 DOI 来源标识"
                f"（{v!r}）—— 这是该材料唯一的出处线索，不能当它不存在"
                "（⚠️ 引擎不解析、不解引用 DOI，故只降拿不准，不判一手来源）"
            )
        if slept_pairs:
            return (
                f"frontmatter 带睡眠台账键 slept_at（{slept_pairs[0][1]!r}）—— "
                "它记录着这份材料的起睡时间（引擎在 Sleeping 台账里认识这个键），"
                "删除会把台账状态一起抹掉"
            )
        if ai_suspect:
            return (
                f"文头有疑似 AI 生成自述（「{ai_suspect}」）但按边界规则不构成"
                "确定命中 —— 是自述还是话题提及，引擎拿不准"
            )
        if ai_word_hit:
            return (
                f"文头或 frontmatter 出现独立词「AI」（如 {ai_word_hit!r}），"
                "可能与 AI 生成有关 —— 引擎不解读语义，宁可拿不准"
            )
        if gen_claim:
            return (
                f"文头出现生成断言结构（归一化后片段：{gen_claim!r}）—— 由谁生成"
                "引擎不解读（模型名是开放集合，枚举追不上），但「这是生成物」"
                "这句声明还在，不能当它不存在"
            )
        if generator_pairs:
            k, v = generator_pairs[0]
            return (
                f"frontmatter 带 {k} 键（{v!r}）—— 这类键名**常**用于标注材料的"
                "生成来源（`generator: gpt-4` 之类）。⚠️ 引擎不判断它在这份材料里"
                "到底是不是这个意思（`model: 线性回归` 这样的学习笔记同样会命中），"
                "所以不下结论、只降拿不准"
            )
        if name_signal:
            return (
                f"文件名本身像一条来源标识（{name_signal!r}）—— 引擎没有消费过"
                "文件名里的信息，删掉这份材料，那个标识就没有别的地方留着了"
            )
        if commented_out:
            return (
                f"文件里有被 HTML 注释包起来的内容（如 {commented_out[0].strip()!r}），"
                "引擎把注释整段剥掉了、没有消费它 —— 注释里可能写着这份材料的"
                "来源或说明，删掉就一起没了"
            )
        # ⛔ 兜底（必须排最后：前面每条都能说出更具体的理由）。
        if unknown_value_pairs:
            k, v = unknown_value_pairs[0]
            return (
                f"frontmatter 的 {k} 键有非空值（{v!r}），而引擎没有消费过它的"
                "内容 —— 那可能是这份材料仅存的信息（标题、出处、编号、批注…），"
                "删掉就没了。⚠️ 引擎不判断这个值重不重要：它分不出 `title: t` 与"
                "`title: <你唯一写下的那句话>` 的区别，分不出就不替你决定"
            )
        return None

    # ── C3 空 / 空骨架（⛔ 未消化信号护栏，见显式偏差 15）──
    if not substantive:
        signal = undigested_reason()
        if signal:
            return finish(
                "C6_undecided",
                V_UNSURE,
                None,
                None,
                "无机械判据可施加",
                False,
                uncertain_reason=(
                    f"{signal}，文件又没有实质正文 —— 是空骨架还是「信号还没被"
                    "读懂的文件」拿不准，不敢建议删"
                ),
                ask=UNDECIDED_ASK,
            )
        return finish(
            "C3_empty_or_skeleton",
            V_DELETE,
            None,
            None,
            skeleton_note(text, item["size_bytes"]),
            True,
        )

    # ── C4 精确重复（**逐字相等**才算；近似永不到这里） ──
    # ⛔ 批内也有同稿时**不再**否决 C4（Codex MEDIUM 实证）：只要库内已经有一份
    # 逐字相同的，收件箱这份就是多余的 —— 与批内还有几份同稿无关。
    # ⛔ 未消化信号护栏同样拦 C4（round-4 BLOCKER-2）：C4 只证明「剥掉
    # frontmatter 后正文相等」，不证明「整个文件多余」——带 source 声明等
    # 信号的文件被建议删时信号必须先摆到台面上，删不删由人定。
    if exact_of:
        signal = undigested_reason()
        if signal:
            return finish(
                "C6_undecided",
                V_UNSURE,
                None,
                None,
                "无机械判据可施加",
                False,
                uncertain_reason=(
                    f"{signal}；且正文与 {exact_of} 逐字相同 —— 但「整个文件"
                    "多余」只有正文证据支撑，上述信号未消化，删不删由你定"
                ),
                ask=UNDECIDED_ASK,
            )
        if fm:
            # ⛔ round-5 自审：C4 的正文证据不覆盖 frontmatter 元数据（tags/created
            # 等引擎不消费的键）。不降级（重复多余性成立），但元数据存在必须留痕
            # —— 删除是不可逆执行，痕迹是人的最后一道核对面。
            conflicts.append(
                {
                    "kind": "frontmatter_metadata_present",
                    "detail": "本件 frontmatter 还带有元数据键（"
                    + "、".join(sorted(fm))
                    + "），正文重复证据不覆盖它们 —— 执行删除前请过目",
                }
            )
        if exact_others:
            basis = (
                f"库内已有 {len(exact_all)} 份正文逐字相同的文件："
                + "、".join(exact_all)
                + "。⛔ 哪一份算「正本」不可判（无机械依据），"
                "但收件箱这份相对它们是多余的，故仍建议删"
            )
            conflicts.append(
                {
                    "kind": "multiple_canonical_candidates",
                    "detail": f"库内有 {len(exact_all)} 份同正文文件，"
                    f"`exact_duplicate_of` 取相对路径字典序最小者仅为**可预测的代表**，"
                    "不主张它比其余几份更正本",
                }
            )
        else:
            basis = f"归一化正文与 {exact_of} 逐字相等（sha256 相同）"
        return finish("C4_exact_duplicate", V_DELETE, None, None, basis, True)

    # ── C5 R{n}_ 文件名 ──
    if rnd:
        typ = round_type(name)
        return finish(
            "C5_round_filename",
            V_ARCHIVE,
            typ,
            f"R{rnd}/",
            f"文件名带 R{rnd}_ → 归轮次目录"
            + (
                f"；子模式命中 → 类型 {typ}"
                if typ
                else "；子模式未命中 → 类型留空（去向确定，类型拿不准，不硬填）"
            ),
            True,
            type_uncertain=typ is None,
        )

    # ── C6 兜底：拿不准（不给去向、不给类型） ──
    if within_batch:
        reason = "本批内有正文逐字相同的另一件，谁是正本不可判 —— 不硬猜"
    elif near:
        reason = (
            "疑似与 "
            + "、".join(f"{n['path']}(ratio {n['ratio']})" for n in near)
            + " 高相似，但**未逐字相等** —— 近似不等于重复，不硬猜"
        )
    else:
        reason = (
            "六判据全不命中：无 source URL、文头无可确定的 AI 自述、有实质正文、"
            "与库内无逐字相同正本、文件名无 R{n}_ 轮次标记"
        )
    if ai_suspect:
        # 嫌疑提示对 within_batch / near / 全不命中三个分支统一补挂 ——
        # round-5 自审 F6：只挂在 else 曾让「批内重复 + AI 嫌疑」件的理由缺嫌疑面。
        reason += f"；文头有「{ai_suspect}」字样但按边界规则不算确定自述，请你过目定夺"
    return finish(
        "C6_undecided",
        V_UNSURE,
        None,
        None,
        "无机械判据可施加",
        False,
        uncertain_reason=reason,
        ask=UNDECIDED_ASK,
    )


def _fill(
    item: dict,
    criterion: str,
    verdict: str,
    ntype: str | None,
    target: str | None,
    basis: str,
    confident: bool,
    *,
    uncertain_reason: str | None = None,
    ask: str | None = None,
    type_uncertain: bool = False,
    exact_of: str | None = None,
    exact_others: list[str] | None = None,
    near: list[dict] | None = None,
    conflicts: list[dict] | None = None,
) -> dict:
    out = dict(item)
    out.update(
        {
            "criterion": criterion,
            "verdict": verdict,
            "nomination_type": ntype,
            "target_hint": target,
            "basis": basis,
            "confident": confident,
            "type_uncertain": type_uncertain,
            "uncertain_reason": uncertain_reason,
            "ask": ask,
            "exact_duplicate_of": exact_of,
            "exact_duplicate_others": exact_others or [],
            "near_duplicates": near or [],
            "conflicts": conflicts or [],
        }
    )
    return out


# ───────────────────────────── 装配 ─────────────────────────────


def list_inbox(inbox: Path, now_s: float) -> tuple[list[dict], list[dict]]:
    """收件箱顶层盘点 → (条目, 跳过留痕)。Sleeping/ 另计台账，其余子目录声明跳过。"""
    items: list[dict] = []
    skipped: list[dict] = []
    with os.scandir(inbox) as it:
        entries = sorted(it, key=lambda e: e.name)
    for entry in entries:
        p = Path(entry.path)
        if entry.is_symlink():
            skipped.append(
                {
                    "name": entry.name,
                    "reason": "条目是 symlink，不跟随（可能指向 vault 外）",
                }
            )
            continue
        if entry.is_dir():
            if entry.name == SLEEPING_DIR_NAME:
                continue  # 走 Sleeping 台账
            skipped.append(
                {
                    "name": entry.name,
                    "reason": "子目录不在本卡盘点范围（只盘点顶层文件与 Sleeping/ 台账）",
                }
            )
            continue
        if not entry.is_file():
            # FIFO / 设备 / 套接字：read_bytes 可能直接阻塞，绝不碰
            skipped.append(
                {
                    "name": entry.name,
                    "reason": "不是普通文件（FIFO / 设备 / 套接字等），不读取",
                }
            )
            continue
        try:
            st = p.stat()
        except OSError as e:
            # 扫目录与取属性之间材料被移走 —— 跳过留痕, 不让一次竞态崩掉整份 preview
            skipped.append(
                {
                    "name": entry.name,
                    "reason": f"读取属性失败（可能已被移走）: {e.strerror}",
                }
            )
            continue
        items.append(
            {
                "stable_id": compute_inbox_stable_id(
                    f"{nfc(inbox.name)}/{nfc(entry.name)}"
                ),
                "name": entry.name,
                "rel_path": f"{inbox.name}/{entry.name}",
                "size_bytes": st.st_size,
                "mtime_utc": fmt_utc(st.st_mtime),
                "mtime_local": fmt_local(st.st_mtime),
                "age_days": days_between(now_s, st.st_mtime),
                # 排序用纳秒整数（float 秒会把相差 1ns 的两件折叠成相等，
                # 于是"最旧优先"退化成按文件名 —— Codex LOW 实证）
                "_mtime_ns": st.st_mtime_ns,
                "_path": str(p),
            }
        )
    # 最旧优先；同 mtime 按名字升序 —— 二跑同序的唯一保证
    items.sort(key=lambda d: (d["_mtime_ns"], d["name"]))
    return items, skipped


def build_sleeping(inbox: Path, now_s: float, exists: bool) -> dict:
    d = inbox / SLEEPING_DIR_NAME
    if not exists or not d.is_dir() or d.is_symlink():
        return {
            "dir": f"{inbox.name}/{SLEEPING_DIR_NAME}",
            "exists": False,
            "count": 0,
            "oldest_days": None,
            "over_30d_count": 0,
            "alert_threshold_days": SLEEP_ALERT_DAYS,
            "items": [],
            "skipped": [],
        }
    out: list[dict] = []
    skipped: list[dict] = []
    with os.scandir(d) as it:
        entries = sorted(it, key=lambda e: e.name)
    for entry in entries:
        # ⛔ 与收件箱同一条纪律：跳过必须留痕，不静默消失。
        if entry.is_symlink():
            skipped.append({"name": entry.name, "reason": "条目是 symlink，不跟随"})
            continue
        if entry.is_dir():
            skipped.append(
                {"name": entry.name, "reason": "Sleeping/ 下的子目录不计入台账"}
            )
            continue
        p = Path(entry.path)
        try:
            st = p.stat()
        except OSError as e:
            skipped.append(
                {
                    "name": entry.name,
                    "reason": f"读取属性失败（可能已被移走）: {e.strerror}",
                }
            )
            continue
        source, slept_at, days = (
            "mtime",
            fmt_utc(st.st_mtime),
            days_between(now_s, st.st_mtime),
        )
        text = read_text_or_none(p)
        if text is not None:
            raw = frontmatter_map(split_frontmatter(text)[0]).get("slept_at", "")
            parsed = _parse_slept_at(raw)
            if parsed is not None:
                source, slept_at = "frontmatter", raw
                days = days_between(now_s, _epoch_s(parsed))
            elif raw:
                source = "mtime(frontmatter slept_at 不可解析，如实退回文件 mtime)"
        out.append(
            {
                "name": entry.name,
                "slept_at": slept_at,
                "slept_at_source": source,
                "slept_days": days,
                "over_30d": days >= SLEEP_ALERT_DAYS,
            }
        )
    out.sort(key=lambda x: (-x["slept_days"], x["name"]))
    return {
        "dir": f"{inbox.name}/{SLEEPING_DIR_NAME}",
        "exists": True,
        "count": len(out),
        "oldest_days": max((x["slept_days"] for x in out), default=None),
        "over_30d_count": sum(1 for x in out if x["over_30d"]),
        "alert_threshold_days": SLEEP_ALERT_DAYS,
        "items": out,
        "skipped": skipped,
    }


def _parse_slept_at(raw: str) -> datetime | None:
    if not raw:
        return None
    try:
        dt = datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError:
        try:
            d = date.fromisoformat(raw)
        except ValueError:
            return None
        dt = datetime(d.year, d.month, d.day)
    return dt if dt.tzinfo else dt.replace(tzinfo=_TZ_SHANGHAI)


def build_receipt(data: dict) -> str:
    inv, sl = data["inventory"], data["sleeping"]
    if not data["inbox_exists"]:
        head = f"{data['inbox_dir']} 尚未创建（等同空仓，该 vault 还没开始用收件箱）。"
    elif inv["total"] == 0:
        head = f"{data['inbox_dir']} 已空，没有待处理材料。"
    else:
        head = f"{data['inbox_dir']} 共 {inv['total']} 件" + (
            f"，本批取最旧的 {len(data['items'])} 件（其余 {len(inv['deferred'])} 件留待下次）。"
            if inv["over_budget"]
            else f"，本批全取（{len(data['items'])} 件）。"
        )
    if not sl["exists"]:
        tail = "Sleeping/ 未建立，无睡眠台账。"
    elif sl["count"] == 0:
        tail = "Sleeping/ 是空的。"
    else:
        tail = f"Sleeping 睡着 {sl['count']} 件（最久 {sl['oldest_days']} 天"
        tail += (
            f"，其中 {sl['over_30d_count']} 件已睡满 {SLEEP_ALERT_DAYS} 天 ⚠️）。"
            if sl["over_30d_count"]
            else "）。"
        )
    return head + " " + tail


def build_preview(
    vault: Path,
    inbox: Path,
    inbox_exists: bool,
    now: datetime,
    batch_size: int,
    excluded_roots: list[str],
) -> dict:
    now_s = _epoch_s(now)
    items_raw, skipped = list_inbox(inbox, now_s) if inbox_exists else ([], [])
    total = len(items_raw)
    batch_raw = items_raw[:batch_size]
    deferred = [
        {
            "name": it["name"],
            "age_days": it["age_days"],
            "mtime_local": it["mtime_local"],
        }
        for it in items_raw[batch_size:]
    ]

    dup_index, corpus_bodies, corpus_stats = scan_corpus(vault, excluded_roots)
    scan = {
        "ratio_threshold": NEAR_DUP_RATIO,
        "body_char_cap": NEAR_DUP_BODY_CHAR_CAP,
        "length_prefilter_ratio": NEAR_DUP_LEN_RATIO,
        "top_n_reported": NEAR_DUP_TOP_N,
        "compared_pairs": 0,
        "skipped_oversize": 0,
        "skipped_length_prefilter": 0,
        "note": "「跳过」≠「无重复」：跳过的对从未比对过，产物如实分列两个计数。",
    }

    texts = {it["rel_path"]: read_text_or_none(Path(it["_path"])) for it in batch_raw}
    batch_body_counts: dict[str, int] = {}
    for it in batch_raw:
        t = texts[it["rel_path"]]
        if t is None:
            continue
        b = dup_body(t) if has_substantive_content(t) else ""
        if b:
            batch_body_counts[b] = batch_body_counts.get(b, 0) + 1

    items: list[dict] = []
    for idx, it in enumerate(batch_raw, start=1):
        text = texts[it["rel_path"]]
        base = {k: v for k, v in it.items() if not k.startswith("_")}
        base["index"] = idx
        base["text_readable"] = text is not None
        items.append(
            nominate(base, text, dup_index, corpus_bodies, scan, batch_body_counts)
        )

    data = {
        "schema_version": SCHEMA_VERSION,
        "generator": GENERATOR,
        "id_namespace": INBOX_ID_NAMESPACE,
        "id_stability": ID_STABILITY,
        "vault_fingerprint": "vf1-"
        + hashlib.sha256(os.path.realpath(vault).encode("utf-8")).hexdigest()[:16],
        "now": now.isoformat(),
        "now_utc": fmt_utc(now_s),
        "now_local": fmt_local(now_s),
        "inbox_dir": f"{inbox.name}/",
        "inbox_exists": inbox_exists,
        "label": inbox.name,
        "criteria_order": list(CRITERIA_ORDER),
        "verdict_vocabulary": VERDICT_VOCABULARY,
        "corpus": corpus_stats,
        "inventory": {
            "total": total,
            "batch_size": batch_size,
            "batch_max": BATCH_MAX,
            "batch_rule": "最旧优先（mtime 升序，同 mtime 按文件名升序），"
            f"单批上限 {BATCH_MAX} 件（D15 确认预算：一次性 >20 项完成率趋近 0）",
            "over_budget": total > batch_size,
            "deferred": deferred,
            "skipped": skipped,
        },
        "items": items,
        "sleeping": build_sleeping(inbox, now_s, inbox_exists),
        "near_dup_scan": scan,
        "last_cleanup": None,
        "last_cleanup_note": LAST_CLEANUP_NOTE,
        "not_executed_disclaimer": NOT_EXECUTED,
    }
    data["receipt"] = build_receipt(data)
    return data


# ───────────────────────── 人读 MD（纯自渲染，只消费 JSON dict） ─────────────────────────


def render_md(d: dict) -> str:
    L: list[str] = []
    L.append(f"# 待处理盘点 preview · {d['label']}")
    L.append("")
    L.append(f"> {d['not_executed_disclaimer']}")
    L.append(
        f"> 基准时刻 `--now`：{d['now_local']}（Asia/Shanghai）· schema v{d['schema_version']}"
    )
    L.append("")
    L.append("## 一、回执")
    L.append("")
    L.append(d["receipt"])
    L.append("")
    L.append(f"- 上次清仓：**不可得** —— {d['last_cleanup_note']}")
    c = d["corpus"]
    L.append(
        f"- 语料库：扫描 {c['files_scanned']} 份 .md，进重复索引 {c['files_indexed']} 份"
        f"（空正文 {c['skipped_empty_body']} 份不进索引 · symlink {c['skipped_symlink']} · "
        f"不可读 {c['skipped_unreadable']}）"
        + (
            "　⚠️ **已达扫描上限被截断**，「无重复」仅代表已扫部分"
            if c["truncated"]
            else ""
        )
    )
    L.append("")

    L.append(f"## 二、本批提名（{len(d['items'])} 件，最旧优先）")
    L.append("")
    if not d["items"]:
        L.append("_（本批无材料）_")
    else:
        L.append("| # | 文件 | 年龄 | 建议去向 | 提名类型 | 判据 | 依据 | 冲突 |")
        L.append("|---|---|---|---|---|---|---|---|")
        for it in d["items"]:
            conflict = (
                "；".join(f"{x['kind']}" for x in it["conflicts"])
                if it["conflicts"]
                else "—"
            )
            target = f"（→ {it['target_hint']}）" if it["target_hint"] else ""
            L.append(
                "| {i} | {n} | {a} 天 | {v}{t} | {ty} | {c} | {b} | {cf} |".format(
                    i=it["index"],
                    n=md_cell(it["name"]),
                    a=it["age_days"],
                    v=md_cell(it["verdict"]),
                    t=md_cell(target),
                    ty=md_cell(it["nomination_type"] or "—"),
                    c=md_cell(it["criterion"]),
                    b=md_cell(it["basis"]),
                    cf=md_cell(conflict),
                )
            )
    L.append("")

    unsure = [it for it in d["items"] if not it["confident"]]
    L.append(f"## 三、拿不准（{len(unsure)} 件 · 需你一句话）")
    L.append("")
    if not unsure:
        L.append("_（本批无拿不准条目）_")
    else:
        for it in unsure:
            L.append(f"- **{it['index']}. {it['name']}** —— {it['uncertain_reason']}")
            L.append(f"  - 请回一句：{it['ask']}")
    L.append("")

    dups = [
        it for it in d["items"] if it["exact_duplicate_of"] or it["near_duplicates"]
    ]
    L.append("## 四、重复线索")
    L.append("")
    if not dups:
        L.append("_（本批未发现逐字重复或疑似高相似）_")
    else:
        for it in dups:
            if it["exact_duplicate_of"]:
                if it["exact_duplicate_others"]:
                    # ⛔ basis 已声明「哪一份算正本不可判」—— 人读 MD 不得再钦定
                    # 「正本 `字典序首项`」（round-2 H4：JSON 与 MD 自相矛盾）。
                    # 路径**不加反引号**：路径本身含反引号时 code span 会错配吃掉
                    # 字符，渲染出一个不存在的文件名（round-3 自审 H4-1）。
                    all_dups = [
                        it["exact_duplicate_of"],
                        *it["exact_duplicate_others"],
                    ]
                    L.append(
                        f"- **{it['name']}** · 与库内 {len(all_dups)} 份文件"
                        "逐字相同："
                        + "、".join(p.replace("`", "\\`") for p in all_dups)
                        + " —— 哪一份是正本不可判"
                        "（exact_duplicate_of 仅为字典序代表）"
                    )
                else:
                    L.append(
                        f"- **{it['name']}** · 逐字相同 → 正本 "
                        f"`{it['exact_duplicate_of'].replace(chr(96), chr(92) + chr(96))}`"
                    )
            for n in it["near_duplicates"]:
                L.append(
                    f"- **{it['name']}** · 疑似（ratio {n['ratio']}）→ `{n['path']}`"
                    "　— 疑似不等于重复，**不建议删**，需你确认"
                )
    s = d["near_dup_scan"]
    L.append("")
    L.append(
        f"> 近似比对：阈值 {s['ratio_threshold']}，实比 {s['compared_pairs']} 对；"
        f"因体积跳过 {s['skipped_oversize']} 对、因长度差跳过 {s['skipped_length_prefilter']} 对。"
        f"{s['note']}"
    )
    L.append("")

    sl = d["sleeping"]
    L.append(f"## 五、Sleeping 台账（{sl['count']} 件）")
    L.append("")
    if not sl["items"]:
        L.append("_（Sleeping/ 未建立或为空）_")
    else:
        L.append("| 文件 | 睡了几天 | 起算依据 | 满 30 天 |")
        L.append("|---|---|---|---|")
        for x in sl["items"]:
            L.append(
                f"| {md_cell(x['name'])} | {x['slept_days']} | {md_cell(x['slept_at_source'])} "
                f"| {'⚠️ 是' if x['over_30d'] else '否'} |"
            )
    L.append("")

    dfr = d["inventory"]["deferred"]
    L.append(f"## 六、本批之外（{len(dfr)} 件，本次不提名）")
    L.append("")
    if not dfr:
        L.append("_（无积压）_")
    else:
        for x in dfr:
            L.append(f"- {x['name']}（{x['age_days']} 天 · {x['mtime_local']}）")
    skp = d["inventory"]["skipped"]
    if skp:
        L.append("")
        L.append("**跳过留痕**（不静默消失）：")
        for x in skp:
            L.append(f"- {x['name']} —— {x['reason']}")
    L.append("")

    L.append("## 七、引擎边界（如实声明）")
    L.append("")
    v = d["verdict_vocabulary"]
    L.append(f"- 引擎可达去向：{'、'.join(v['reachable_by_engine'])}")
    L.append(f"- **恒不产出**：{'、'.join(v['human_only'])} —— {v['human_only_note']}")
    L.append(
        "- 近似重复（difflib）**永不**产出建议删：**在重复这条判据里**，只有"
        "归一化正文逐字相等才建议删（另一个建议删的出口是「空/空骨架」，"
        "它跟像不像别的文件无关）；库内只有一份同正文时给正本路径，多份同正文时"
        "给出全部候选并声明「哪一份是正本不可判」。"
    )
    L.append(
        "- 建议删有两个出口（空骨架 / 正文重复），共用一组护栏（如实声明）："
        "在来源链接与 AI 自述都未确定命中时，文件若带下列任一信号 —— "
        "① 以未闭合的 HTML 注释结尾；② frontmatter 含解析不了的行；"
        "③ frontmatter 有来源声明（source 键，键名大小写不敏感；或任意键的值里"
        "含网址、含 DOI 编号）；④ 带睡眠台账键 slept_at；⑤ 文头有疑似 AI 自述；"
        "⑥ 文头或 frontmatter 出现独立的「AI」字样；⑦ 文头出现「由 X 生成」/"
        "「generated by X」这类生成声明；⑧ frontmatter 带 generator/model 之类的"
        "生成器声明键 —— 空骨架不判、重复也不建议删，一律落「拿不准」把证据摆给你。"
        "⚠️ 这八条是**已知形态的登记表**，不是完备判据：它们是被真实反例逐轮"
        "打穿后一条条补上的，没有哪一轮证明了「没有下一条」。"
    )
    L.append(
        "- AI 自述标记为字面量 + 右边界规则（汉字收尾标记后须为行尾/空白/有限标点"
        "表，英文收尾标记后须为行尾/表中标点），仍不做语义否定检测：语义否定"
        "（「这不是由 AI 生成」）与满足边界的话题提及仍可能给出归档提名 —— 依据"
        "带行号与**命中的标记文本**（⚠️ 那是标记表里的规范写法，不是你文件里的"
        "原字，匹配在大小写/空白归一后做；行号是准的），请按行号回看原文再拍板。"
        "⚠️ 漏判方向（该认出是 AI 写的却没认出）：**已登记的**形态由上面 ⑤⑥⑦⑧"
        "四条信号接住落「拿不准」；**未登记的**新写法仍可能被判成空骨架建议删 —— "
        "这条护栏是尽力而为，不是保证。"
    )
    L.append(f"- 判据次序（先命中者定去向）：{' → '.join(d['criteria_order'])}")
    L.append("")
    return "\n".join(L) + "\n"


# ───────────────────────────── 入口 ─────────────────────────────


def validate_label(label: str) -> None:
    if not label or _BAD_LABEL.search(label):
        raise SystemExit(
            f"✗ 收件箱目录名含非法字符或路径逃逸，拒绝用作产物名: {label!r}"
        )


def validate_product_filename(label: str) -> None:
    """产物文件名长度预检 —— ⛔ 必须在 prepare_out_dir **之前**调用，
    否则会「先建好 out-dir、再在写入时 ENAMETOOLONG」：拒绝但已留空目录。"""
    for suffix in (".json", ".md"):
        n = len(f"inbox-preview-{label}{suffix}".encode("utf-8"))
        if n > MAX_FILENAME_BYTES:
            raise SystemExit(
                f"✗ 收件箱目录名过长，产物文件名 {n} 字节超出上限 {MAX_FILENAME_BYTES}: "
                f"inbox-preview-{label}{suffix}"
            )


def main() -> int:
    ap = argparse.ArgumentParser(
        description="待处理盘点提名 preview（只读, CARD-G5-6）"
    )
    ap.add_argument("--vault", required=True, help="vault 根目录")
    ap.add_argument(
        "--now", required=True, help="基准时刻 ISO-8601（裸时间按 Asia/Shanghai 解释）"
    )
    ap.add_argument(
        "--inbox-dir",
        default=None,
        help=f"收件箱目录（缺省 <vault>/{DEFAULT_INBOX_NAME}）。"
        "显式给定却不存在 = 拒绝；缺省路径不存在 = 空仓回执",
    )
    ap.add_argument(
        "--out-dir",
        default=None,
        help="产物目录（缺省 <vault>/outputs；父目录必须已存在）",
    )
    ap.add_argument(
        "--batch-size", type=int, default=BATCH_MAX, help=f"单批件数（1..{BATCH_MAX}）"
    )
    args = ap.parse_args()

    # ⛔ 次序铁律：全部输入守卫跑完**再**碰 out-dir —— 拒绝路径必须零产物。
    if not (1 <= args.batch_size <= BATCH_MAX):
        raise SystemExit(
            f"✗ --batch-size 必须在 1..{BATCH_MAX}（D15 确认预算上限，不得突破）, 实得 {args.batch_size}"
        )
    now = parse_now(args.now)

    vault = Path(args.vault)
    if vault.is_symlink():
        raise SystemExit(f"✗ vault 路径本身是 symlink, 拒绝越界读取: {vault}")
    if not vault.is_dir():
        raise SystemExit(f"✗ vault 不存在或不是目录: {vault}")
    vault = vault.resolve()

    explicit = args.inbox_dir is not None
    inbox = Path(args.inbox_dir) if explicit else vault / DEFAULT_INBOX_NAME
    if inbox.is_symlink():
        raise SystemExit(f"✗ 收件箱目录本身是 symlink, 拒绝越界读取: {inbox}")
    inbox_exists = inbox.is_dir()
    if explicit and not inbox_exists:
        # 用户明确指了路径却找不到 = 写错了。绝不能报成「空仓」把 typo 掩盖掉。
        raise SystemExit(f"✗ --inbox-dir 指定的目录不存在: {inbox}")

    validate_label(inbox.name)
    validate_product_filename(inbox.name)

    out_dir_arg = Path(args.out_dir) if args.out_dir else vault / "outputs"
    inbox_real, out_real = os.path.realpath(inbox), os.path.realpath(out_dir_arg)
    if out_real == inbox_real or out_real.startswith(inbox_real + os.sep):
        # ⛔ 否则第一次跑落下的两份产物，第二次跑会被当成待处理材料盘点进来 ——
        # 「同输入二跑逐字节相等」当场不成立，而且是那种跑两次才看得见的不成立。
        raise SystemExit(
            f"✗ 产物目录不能位于收件箱内, 拒绝运行（二跑会把上一次的产物当成待处理材料）: {out_dir_arg}"
        )
    excluded = [inbox_real, out_real]

    data = build_preview(vault, inbox, inbox_exists, now, args.batch_size, excluded)
    payload_json = json.dumps(data, ensure_ascii=False, indent=2) + "\n"
    payload_md = render_md(data)

    out_dir = _SP.prepare_out_dir(out_dir_arg)
    json_path = out_dir / f"inbox-preview-{inbox.name}.json"
    md_path = out_dir / f"inbox-preview-{inbox.name}.md"
    _SP.write_pair_atomically_checked(
        [(json_path, payload_json), (md_path, payload_md)]
    )

    print(
        f"✓ preview 已生成（只读引擎, 未动 vault 任何既有文件）: {json_path} / {md_path}"
    )
    print(f"  {data['receipt']}")
    unsure = sum(1 for i in data["items"] if not i["confident"])
    print(
        f"  本批 {len(data['items'])} 件 · 拿不准 {unsure} 件 · "
        f"建议删 {sum(1 for i in data['items'] if i['verdict'] == V_DELETE)} 件"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
