"""RAG-S2.6 T2 — 原白板 `## Concepts` 自动重算 (只读派生物, 非第二真相源)。

背景 (用户 2026-08-11 裁定「方案 B: 自动重算成文本」, 而非 Dataview 实时视图):
  - 保 Graph View 正向边: 生成的仍是明文 `- [[节点/x]]` wikilink 行
  - 保离线可读: 关掉 Dataview 插件后 Concepts 仍是人可读清单
  - 保 doc_count 有源: plugin 的 recountBoardConcepts 从 Concepts 段反查计数,
    纯视图化会让它全部归零 (这是选方案 B 而非视图化的硬理由)
  - 「废除第二真相源」以「Concepts 降级为只读派生物」达成

真相源 = `节点/*.md` frontmatter 的 `source_board` (与 backend board_manifest
同款归一逻辑)。本脚本与服务端 dual_source_gap 是**两把独立实现的锁**:
脚本 --check 幂等 + 服务端差集告警全空, 双绿才算迁移成功。

⛔ 只重写 sentinel 之间的行, 段外 (空行 / `---` / 散文) 原样保留;
⛔ tmp + os.replace 原子写, 半成品永不可见;
⛔ 零外部依赖 (stdlib + 同目录 decay_beta), 零动态拼接, 路径只从 argv 来 ——
   与 vault 现有静态 python 范式一致 (skill 里 `python3` 落到哪个解释器
   取决于 PATH, 依赖 PyYAML 会让脚本在系统 python 下直接炸)。

用法:
    python3 sync_board_concepts.py --check              # 全板校验 (有漂移 exit 1)
    python3 sync_board_concepts.py --board 特征值与特征向量
    python3 sync_board_concepts.py --all --backup       # 迁移用 (先落 .bak)
"""

from __future__ import annotations

import argparse
import difflib
import os
import re
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from decay_beta import mu as _beta_mu  # noqa: E402  掌握度点估计单一真相源

NODE_DIR = "节点"
BOARD_DIR = "原白板"

#: 与 backend board_manifest_service.PLACEHOLDER / start-exam-board 同一条占位规则
PLACEHOLDER = "你的 1-2 句精准定义"

_CONCEPTS_HEADING = re.compile(r"^##\s+Concepts\s*$")
_NEXT_HEADING = re.compile(r"^##[^#]")
_CONCEPT_LINE = re.compile(r"^\s*-\s*\[\[([^\]]+)\]\]")
_WIKILINK = re.compile(r"\[\[([^\]]+)\]\]")
_FRONTMATTER = re.compile(r"^﻿?---\r?\n(.*?)\r?\n---[ \t]*\r?\n?(.*)$", re.S)

_SENTINEL_BEGIN = "<!-- AUTO-GENERATED by .claude/scripts/sync_board_concepts.py · 真相源 = 节点 frontmatter source_board"
_SENTINEL_NOTE = "     ⛔ 请勿手改：手改会在下次同步时被覆盖。增删成员请改节点的 source_board（或 Cmd+Shift+D 派生） -->"
_BEGIN_RE = re.compile(r"^<!--\s*AUTO-GENERATED by \.claude/scripts/sync_board_concepts\.py")
_END_RE = re.compile(r"^<!--\s*/AUTO-GENERATED")


# ── frontmatter 窄解析 (只取本脚本需要的字段, 不做通用 YAML) ──


def split_frontmatter(text: str) -> tuple[str, str]:
    m = _FRONTMATTER.match(text)
    return (m.group(1), m.group(2)) if m else ("", text)


def fm_scalar(fm: str, key: str) -> str | None:
    """顶层标量取值。`^key:` 不容前导空白 → 天然排除嵌套同名键。"""
    m = re.search(rf"^{re.escape(key)}:[ \t]*(.*)$", fm, re.M)
    if not m:
        return None
    v = m.group(1).strip().strip('"').strip("'")
    return v or None


def fm_num(fm: str, key: str) -> float | None:
    raw = fm_scalar(fm, key)
    if raw is None:
        return None
    try:
        return float(raw)
    except ValueError:
        return None


def first_relationship_target(fm: str) -> str | None:
    """relationships[] 首项的 target (只认第一项, 与 manifest _node_relation 同规则)。"""
    lines = fm.splitlines()
    start = next((i for i, ln in enumerate(lines) if re.match(r"^relationships:\s*$", ln)), None)
    if start is None:
        return None
    seen_item = False
    for ln in lines[start + 1 :]:
        if ln.strip() and not ln[0].isspace():
            break  # 回到顶层缩进 → relationships 块结束
        if re.match(r"^\s*-\s", ln):
            if seen_item:
                break  # 第二项开始 → 只认首项
            seen_item = True
        m = re.search(r"(?:^|\s)target:\s*(.+)$", ln)
        if m:
            return m.group(1).strip()
    return None


def basename(raw: str | None) -> str:
    """'[[节点/x|别名]]' / '[[x#小节]]' / 'x.md' → basename (对齐 resolve_node_id)。"""
    text = str(raw or "")
    m = _WIKILINK.search(text)
    inner = m.group(1) if m else text
    return inner.split("|", 1)[0].split("#", 1)[0].split("/")[-1].strip().removesuffix(".md")


# ── 成员建模 ──


class Member:
    __slots__ = ("node_id", "role", "derived_from", "mastery", "attempts", "is_stub")

    def __init__(self, node_id: str, fm: str, body: str) -> None:
        self.node_id = node_id
        rel_target = first_relationship_target(fm)
        derived_raw = rel_target or fm_scalar(fm, "derived-from") or fm_scalar(fm, "derived_from")
        self.role = (
            "derived"
            if (derived_raw or re.search(r"^relationships:", fm, re.M) or fm_scalar(fm, "created_from") == "ai_linked_doc")
            else "seed"
        )
        self.derived_from = basename(derived_raw) if derived_raw else None
        self.mastery = self._mastery(fm)
        attempts = fm_num(fm, "attempt_count")
        self.attempts = int(attempts) if attempts is not None else 0
        self.is_stub = PLACEHOLDER in body

    @staticmethod
    def _mastery(fm: str) -> float | None:
        """掌握度点估计 — 与 backend board_manifest _normalize_mastery **逐字同语义**。

        beta 档显式 mastery_score 优先于 μ (两把锁的口径必须一致, 否则
        --check 与 dual_source_gap 会各说各话)。

        ⚠️ 用 μ 而非 pick_score: μ 在闲置折旧下**严格不变** (effective 同比
        缩放 a,b), 所以行内掌握度不会因为「久没考」而过期 —— 唯一会改动它的
        是 quiz-answer 写分, 而写分后会立即触发一次本同步 (在唯一会变的时刻同步)。
        """
        a, b = fm_num(fm, "mastery_a"), fm_num(fm, "mastery_b")
        explicit = fm_num(fm, "mastery_score")
        if a is not None and b is not None and a > 0 and b > 0:
            return explicit if explicit is not None else _beta_mu(a, b)
        for key in ("mastery_score", "mastery", "mastery_level"):
            v = fm_num(fm, key)
            if v is not None:
                return v
        return None

    def render(self) -> str:
        role_part = "种子" if self.role == "seed" else (f"派生自 {self.derived_from}" if self.derived_from else "派生")
        if self.is_stub:
            status = "待剖析占位"
        else:
            grade = f"掌握度 {self.mastery:.2f}" if self.mastery is not None else "掌握度 —"
            status = f"{grade} · {'已考 %d 次' % self.attempts if self.attempts else '未考'}"
        return f"- [[{NODE_DIR}/{self.node_id}]] — {role_part} · {status}"


def scan_members(vault: Path) -> dict[str, list[Member]]:
    """节点池 → {board_id: [Member]}，board_id 大小写不敏感归一到白板文件名。"""
    boards_ci = {p.stem.casefold(): p.stem for p in sorted((vault / BOARD_DIR).glob("*.md"))}
    grouped: dict[str, list[Member]] = {stem: [] for stem in boards_ci.values()}
    for path in sorted((vault / NODE_DIR).glob("*.md")):
        try:
            fm, body = split_frontmatter(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError) as e:
            print(f"  ⚠ 跳过无法读取的节点 {path.name}: {type(e).__name__}", file=sys.stderr)
            continue
        board = boards_ci.get(basename(fm_scalar(fm, "source_board")).casefold())
        if board:
            grouped[board].append(Member(path.stem, fm, body))
    for members in grouped.values():
        members.sort(key=lambda m: m.node_id)  # 与 manifest nodes[] 同序 (文件名序)
    return grouped


# ── Concepts 段定位与重写 ──


def locate_section(lines: list[str]) -> tuple[int, int] | None:
    """`## Concepts` 段 → (首行索引, 结束索引 exclusive)，不含标题行本身。"""
    start = next((i for i, ln in enumerate(lines) if _CONCEPTS_HEADING.match(ln)), None)
    if start is None:
        return None
    end = next((j for j in range(start + 1, len(lines)) if _NEXT_HEADING.match(lines[j])), len(lines))
    return start + 1, end


def managed_region(lines: list[str], lo: int, hi: int) -> tuple[int, int]:
    """段内**被托管**的行区间 (start, end_exclusive)；空区间 = 纯插入点。

    两种情形:
      已有 sentinel → {sentinel 块} ∪ {段内全部概念行} 的包络
      首次迁移      → {HTML 注释块} ∪ {概念行} 的包络

    ⛔ 必须取包络而不是「删注释后重建」: 实测 6 块白板有两种历史形态 ——
    4 板是「注释在前列表在后」, CS 61B / 递归与分治 是「列表在前注释在后」。
    包络外的空行 / `---` 分隔线 / 散文一律不动。

    ⛔ sentinel 存在时也必须并进段内游离概念行: plugin 的 appendBoardLines
    (main.ts) 插在**整段边界**前 (下一个 `## ` / `---` / ```dataviewjs 三者
    最靠前者), 也就是落在 `<!-- /AUTO-GENERATED -->` **之外** —— 只取
    BEGIN..END 会让 plugin 写的行永远留在块外形成重复。
    """
    begin = next((i for i in range(lo, hi) if _BEGIN_RE.match(lines[i].strip())), None)
    if begin is not None:
        end = next((i for i in range(begin, hi) if _END_RE.match(lines[i].strip())), None)
        if end is not None:
            strays = [i for i in range(lo, hi) if _CONCEPT_LINE.match(lines[i])]
            return min([begin, *strays]), max([end + 1, *[i + 1 for i in strays]])

    marks: list[tuple[int, int]] = []
    i = lo
    while i < hi:
        if lines[i].strip().startswith("<!--"):
            j = i
            while j < hi and "-->" not in lines[j]:
                j += 1
            marks.append((i, min(j, hi - 1) + 1))
            i = j + 1
            continue
        if _CONCEPT_LINE.match(lines[i]):
            marks.append((i, i + 1))
        i += 1
    if marks:
        return marks[0][0], marks[-1][1]

    k = lo  # 段内无任何托管内容 → 插在首个非空行处
    while k < hi and not lines[k].strip():
        k += 1
    return k, k


#: 空板占位行 — 非 `- [[...]]` 形状, 不会被 manifest 的 Concepts 窄解析当成成员
_EMPTY_HINT = "_（暂无节点 — 在源笔记选中文本按 `Cmd+Shift+D` 派生第一个）_"


def render_block(members: list[Member], synced: str) -> list[str]:
    body = [m.render() for m in members] if members else [_EMPTY_HINT]
    return [
        _SENTINEL_BEGIN,
        _SENTINEL_NOTE,
        *body,
        f"<!-- /AUTO-GENERATED n={len(members)} · synced {synced} -->",
    ]


def _content_of(block: list[str]) -> list[str]:
    """比对用内容 = 除尾行 sentinel 外的全部行。

    ⛔ 尾行含 synced 时间戳, 参与比对会让 --check 永远报漂移 (幂等锁失效)。
    内容没变就整个不写盘 → 时间戳自然保持不动, 「有变更才刷戳」。
    """
    return block[:-1]


def sync_board(path: Path, members: list[Member], synced: str) -> tuple[str, str]:
    """→ (原文, 新文)。无变更时两者相等。"""
    original = path.read_text(encoding="utf-8")
    fm, _ = split_frontmatter(original)
    lines = original.splitlines()

    span = locate_section(lines)
    if span is None:
        print(f"  ⚠ {path.name}: 无 `## Concepts` 段, 跳过", file=sys.stderr)
        return original, original
    lo, hi = span
    start, end = managed_region(lines, lo, hi)
    new_block = render_block(members, synced)
    if _content_of(lines[start:end]) == _content_of(new_block):
        new_lines = lines  # 内容等价 → 保留旧时间戳
    else:
        new_lines = lines[:start] + new_block + lines[end:]

    updated = "\n".join(new_lines) + ("\n" if original.endswith("\n") else "")

    # doc_count 归一到实际成员数 (根除声明/实际漂移); 缺字段不擅自新增
    if re.search(r"^doc_count:[ \t]*", fm, re.M):
        head, sep, tail = updated.partition("\n---")
        head = re.sub(r"^doc_count:[ \t]*.*$", f"doc_count: {len(members)}", head, count=1, flags=re.M)
        updated = head + sep + tail
    return original, updated


# ── CLI ──


def _diff(name: str, old: str, new: str) -> str:
    return "".join(
        difflib.unified_diff(old.splitlines(True), new.splitlines(True), f"a/{name}", f"b/{name}", n=2)
    )


def atomic_write(path: Path, text: str) -> None:
    fd, tmp_name = tempfile.mkstemp(dir=path.parent, prefix=path.name + ".", suffix=".tmp")
    tmp = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
        os.replace(tmp, path)
    finally:
        tmp.unlink(missing_ok=True)


def main() -> int:
    ap = argparse.ArgumentParser(description="原白板 ## Concepts 自动重算 (RAG-S2.6)")
    ap.add_argument("--vault", help="vault 根目录 (缺省 = 本脚本所在 vault)")
    ap.add_argument("--board", help="只同步这一块白板 (文件名 stem)")
    ap.add_argument("--all", action="store_true", help="同步全部白板")
    ap.add_argument("--check", action="store_true", help="只校验不写盘; 有待同步变更 exit 1")
    ap.add_argument("--backup", action="store_true", help="写盘前落 <file>.bak (迁移用)")
    args = ap.parse_args()

    if not (args.board or args.all or args.check):
        ap.error("需要 --board <id> / --all / --check 之一")

    vault = Path(args.vault) if args.vault else Path(__file__).resolve().parents[2]
    if not (vault / NODE_DIR).is_dir() or not (vault / BOARD_DIR).is_dir():
        print(f"✗ vault 结构缺失 (需 {NODE_DIR}/ 与 {BOARD_DIR}/): {vault}", file=sys.stderr)
        return 2

    grouped = scan_members(vault)
    targets = [args.board] if args.board else sorted(grouped)
    missing = [b for b in targets if b not in grouped]
    if missing:
        print(f"✗ 白板不存在: {missing} (可选: {sorted(grouped)})", file=sys.stderr)
        return 2

    synced = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    changed = 0
    for board_id in targets:
        path = vault / BOARD_DIR / f"{board_id}.md"
        members = grouped[board_id]
        try:
            old, new = sync_board(path, members, synced)
        except (OSError, UnicodeDecodeError) as e:
            print(f"✗ {board_id}: 读写失败 {type(e).__name__}", file=sys.stderr)
            return 2
        if old == new:
            print(f"  = {board_id}  ({len(members)} 成员, 已同步)")
            continue
        changed += 1
        print(f"  ~ {board_id}  ({len(members)} 成员, 需更新)")
        if args.check:
            print(_diff(f"{BOARD_DIR}/{board_id}.md", old, new))
            continue
        if args.backup:
            path.with_suffix(".md.bak").write_text(old, encoding="utf-8")
        atomic_write(path, new)

    if args.check:
        if changed:
            print(f"\n✗ {changed} 块白板的 ## Concepts 与真相源不一致 (跑 --all 同步)")
            return 1
        print(f"\n✓ 全部 {len(targets)} 块白板已同步 (幂等)")
        return 0
    print(f"\n✓ 完成: {changed} 块已更新 / {len(targets) - changed} 块无变更")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
