"""RAG-S2.6 T2 — 原白板 `## Concepts` 自动重算 (只读派生物, 非第二真相源)。

背景 (用户 2026-08-11 裁定「方案 B: 自动重算成文本」, 而非 Dataview 实时视图):
  - 保 Graph View 正向边: 生成的仍是明文 `- [[节点/x]]` wikilink 行
  - 保离线可读: 关掉 Dataview 插件后 Concepts 仍是人可读清单
  - 保 doc_count 有源: plugin 的 recountBoardConcepts 从 Concepts 段反查计数,
    纯视图化会让它全部归零 (这是选方案 B 而非视图化的硬理由)
  - 「废除第二真相源」以「Concepts 降级为只读派生物」达成

真相源 = `节点/*.md` frontmatter 的 `source_board` (与 backend board_manifest
同款归一逻辑)。本脚本与服务端 dual_source_gap 是**两把独立实现的锁**:
脚本 --check 幂等 + 服务端差集告警全空, 双绿才算迁移成功。

⛔ 只重写 sentinel 之间的行, 段外 (空行 / `---` / 散文) 原样保留;
⛔ tmp + os.replace 原子写, 半成品永不可见;
⛔ 零外部依赖 (stdlib + 同目录 decay_beta), 零动态拼接, 路径只从 argv 来 ——
   与 vault 现有静态 python 范式一致 (skill 里 `python3` 落到哪个解释器
   取决于 PATH, 依赖 PyYAML 会让脚本在系统 python 下直接炸)。

用法:
    python3 sync_board_concepts.py --check              # 全板校验 (有漂移 exit 1)
    python3 sync_board_concepts.py --board 特征值与特征向量
    python3 sync_board_concepts.py --all --backup       # 迁移用 (先落 .bak)
"""

from __future__ import annotations

import argparse
import difflib
import os
import re
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from decay_beta import mu as _beta_mu  # noqa: E402  掌握度点估计单一真相源

NODE_DIR = "节点"
BOARD_DIR = "原白板"

#: 与 backend board_manifest_service.PLACEHOLDER / start-exam-board 同一条占位规则
PLACEHOLDER = "你的 1-2 句精准定义"

_CONCEPTS_HEADING = re.compile(r"^##\s+Concepts\s*$")
_NEXT_HEADING = re.compile(r"^##[^#]")
_CONCEPT_LINE = re.compile(r"^\s*-\s*\[\[([^\]]+)\]\]")
_WIKILINK = re.compile(r"\[\[([^\]]+)\]\]")
_FRONTMATTER = re.compile(r"^﻿?---\r?\n(.*?)\r?\n---[ \t]*\r?\n?(.*)$", re.S)

_SENTINEL_BEGIN = "<!-- AUTO-GENERATED by .claude/scripts/sync_board_concepts.py · 真相源 = 节点 frontmatter source_board"
_SENTINEL_NOTE = "     ⛔ 请勿手改：手改会在下次同步时被覆盖。增删成员请改节点的 source_board（或 Cmd+Shift+D 派生） -->"
_BEGIN_RE = re.compile(r"^<!--\s*AUTO-GENERATED by \.claude/scripts/sync_board_concepts\.py")
_END_RE = re.compile(r"^<!--\s*/AUTO-GENERATED")


# ── frontmatter 窄解析 (只取本脚本需要的字段, 不做通用 YAML) ──


def split_frontmatter(text: str) -> tuple[str, str]:
    m = _FRONTMATTER.match(text)
    return (m.group(1), m.group(2)) if m else ("", text)


def fm_scalar(fm: str, key: str) -> str | None:
    """顶层标量取值。`^key:` 不容前导空白 → 天然排除嵌套同名键。

    ⛔ 取**最后一个**同名 key (与 YAML / 后端一致): 重复 key 时 YAML 后者胜,
    取第一个会让脚本与后端读到不同值 (RAG-S2.6 审查 M10 同族)。
    ⛔ 剥行内注释: `mastery_score: 0.75  # 手动校准` 在真 YAML 里是 0.75,
    不剥就 float() 失败 → 掌握度显示成「—」而后端显示 0.75 (审查 H4)。
    """
    matches = re.findall(rf"^{re.escape(key)}:[ \t]*(.*)$", fm, re.M)
    if not matches:
        return None
    v = matches[-1].strip()
    if not (v.startswith(('"', "'")) and v.endswith(('"', "'"))):
        v = re.sub(r"\s+#.*$", "", v)  # 行内注释 (引号包裹的值里 # 不算注释)
    v = v.strip().strip('"').strip("'")
    return v or None


def fm_num(fm: str, key: str) -> float | None:
    raw = fm_scalar(fm, key)
    if raw is None:
        return None
    try:
        return float(raw)
    except ValueError:
        return None


def first_relationship_target(fm: str) -> str | None:
    """relationships[] 首项的 target (只认第一项, 与 manifest _node_relation 同规则)。"""
    lines = fm.splitlines()
    start = next((i for i, ln in enumerate(lines) if re.match(r"^relationships:\s*$", ln)), None)
    if start is None:
        return None
    seen_item = False
    for ln in lines[start + 1 :]:
        if ln.strip() and not ln[0].isspace():
            break  # 回到顶层缩进 → relationships 块结束
        if re.match(r"^\s*-\s", ln):
            if seen_item:
                break  # 第二项开始 → 只认首项
            seen_item = True
        # ⛔ 必须锚在 key 位置 (行首缩进后 / `- ` 之后), 不能裸 `(?:^|\s)target:`:
        # 审查 H3 实测 —— 批注文本 `description: 我不懂 target: 到底指什么…`
        # 会被当成 key, 把用户私密批注切片当成 target 抠出来写进白板。
        m = re.match(r"^\s*(?:-\s+)?target:\s*(.+)$", ln)
        if m:
            return m.group(1).strip()
    return None


def basename(raw: str | None) -> str:
    """'[[节点/x|别名]]' / '[[x#小节]]' / 'x.md' → basename (对齐 resolve_node_id)。"""
    text = str(raw or "")
    m = _WIKILINK.search(text)
    inner = m.group(1) if m else text
    return inner.split("|", 1)[0].split("#", 1)[0].split("/")[-1].strip().removesuffix(".md")


def wikilink_basename(raw: str | None) -> str | None:
    """**只认真正的 wikilink**, 否则返回 None (审查 H3 泄漏面封堵)。

    `basename()` 对非 wikilink 输入会退化成「整串 strip」—— 于是
    `derived-from: 老师说我这块基础差，要重学第三章` 会被整句写进白板 md,
    而白板正是 start-exam-board 读的那张面 (信息隔离铁律的直接对手)。
    派生来源只有形如 `[[...]]` 才可信, 拿不到就显示成中性的「派生」。
    """
    m = _WIKILINK.search(str(raw or ""))
    if not m:
        return None
    return m.group(1).split("|", 1)[0].split("#", 1)[0].split("/")[-1].strip().removesuffix(".md") or None


# ── 成员建模 ──


class Member:
    __slots__ = ("node_id", "role", "derived_from", "mastery", "attempts", "is_stub")

    def __init__(self, node_id: str, fm: str, body: str) -> None:
        self.node_id = node_id
        rel_target = first_relationship_target(fm)
        derived_raw = rel_target or fm_scalar(fm, "derived-from") or fm_scalar(fm, "derived_from")
        # ⛔ `relationships:` 判**真值**不判存在 (审查 H4): `relationships: []` 与
        # `relationships:`(null) 在后端 _node_role 里是 falsy → seed, 脚本靠
        # `re.search(r"^relationships:")` 判存在会说成 derived, 两把锁口径分叉。
        has_rel = bool(rel_target) or bool(re.search(r"^relationships:\s*\n\s+\S", fm, re.M))
        self.role = (
            "derived"
            if (derived_raw or has_rel or fm_scalar(fm, "created_from") == "ai_linked_doc")
            else "seed"
        )
        # ⛔ 只认真正的 wikilink (审查 H3): 非 wikilink 一律显示中性的「派生」,
        # 绝不把 frontmatter 自由文本原样写进白板 md。
        self.derived_from = wikilink_basename(derived_raw)
        self.mastery = self._mastery(fm)
        attempts = fm_num(fm, "attempt_count")
        self.attempts = int(attempts) if attempts is not None else 0
        self.is_stub = PLACEHOLDER in body

    @staticmethod
    def _mastery(fm: str) -> float | None:
        """掌握度点估计 — 与 backend board_manifest _normalize_mastery **逐字同语义**。

        beta 档显式 mastery_score 优先于 μ (两把锁的口径必须一致, 否则
        --check 与 dual_source_gap 会各说各话)。

        ⚠️ 用 μ 而非 pick_score: μ 在闲置折旧下**严格不变** (effective 同比
        缩放 a,b), 所以行内掌握度不会因为「久没考」而过期 —— 唯一会改动它的
        是 quiz-answer 写分, 而写分后会立即触发一次本同步 (在唯一会变的时刻同步)。
        """
        a, b = fm_num(fm, "mastery_a"), fm_num(fm, "mastery_b")
        explicit = fm_num(fm, "mastery_score")
        if a is not None and b is not None:
            # ⛔ a/b 齐即 beta 档, 非正**不再回落 legacy** (审查 H4): 后端把
            # `mastery_a: 0` 判成「数据损坏」→ score=None + parse_errors, 脚本
            # 若悄悄改用 mastery_level 就会显示一个后端根本不认的数字。
            if a <= 0 or b <= 0:
                return None
            return explicit if explicit is not None else _beta_mu(a, b)
        for key in ("mastery_score", "mastery", "mastery_level"):
            v = fm_num(fm, key)
            if v is not None:
                return v
        return None

    def render(self) -> str:
        role_part = "种子" if self.role == "seed" else (f"派生自 {self.derived_from}" if self.derived_from else "派生")
        if self.is_stub:
            status = "待剖析占位"
        else:
            grade = f"掌握度 {self.mastery:.2f}" if self.mastery is not None else "掌握度 —"
            status = f"{grade} · {'已考 %d 次' % self.attempts if self.attempts else '未考'}"
        return f"- [[{NODE_DIR}/{self.node_id}]] — {role_part} · {status}"


#: wikilink 里没有转义语法, 这些字符会让 `[[节点/x]]` 断链或被当成别名/锚点
_WIKILINK_HOSTILE = "[]|#^"


def scan_members(vault: Path) -> tuple[dict[str, list[Member]], list[str]]:
    """节点池 → ({board_id: [Member]}, 告警行)。board_id 大小写不敏感归一。

    ⛔ 返回告警而不是静默 (审查 M11/M12): 孤儿节点 (source_board 拼错 / 指向
    不存在的板 / NFC-NFD 不一致) 原来零输出就被剔出白板、doc_count 同步下调;
    节点名含 `[]|#^` 则会生成断链 wikilink —— 那正好打脸选方案 B 的头号理由
    「保 Graph View 正向边」。两者都必须让 --check 红。
    """
    boards_ci: dict[str, str] = {}
    warnings: list[str] = []
    for p in sorted((vault / BOARD_DIR).glob("*.md")):
        key = p.stem.casefold()
        if key in boards_ci:  # 审查 L15: casefold 碰撞会让后写者吞掉前一块板
            warnings.append(f"白板名 casefold 碰撞: {boards_ci[key]!r} vs {p.stem!r} — 后者的节点会被误归")
        boards_ci[key] = p.stem
    grouped: dict[str, list[Member]] = {stem: [] for stem in boards_ci.values()}

    for path in sorted((vault / NODE_DIR).glob("*.md")):
        try:
            fm, body = split_frontmatter(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError) as e:
            warnings.append(f"节点读取失败, 已跳过: {path.name} ({type(e).__name__})")
            continue
        raw_board = fm_scalar(fm, "source_board")
        board = boards_ci.get(basename(raw_board).casefold()) if raw_board else None
        if board is None:
            warnings.append(
                f"孤儿节点 {path.stem!r}: "
                + ("无 source_board" if not raw_board else "source_board 指向不存在的白板")
            )
            continue
        if any(c in path.stem for c in _WIKILINK_HOSTILE):
            warnings.append(f"节点名含 wikilink 敏感字符 {_WIKILINK_HOSTILE!r}, 生成的双链会断: {path.stem!r}")
        # ⛔ 状态量必须伴随显式分 (节点关系图审查后加的防线): 唯一写分路径
        # quiz-answer 的原子替换保证 mastery_a/b 与 mastery_score 同时写入,
        # 只有手工编辑才会造出「有状态量没显式分」的节点 — 那会让部分只读
        # mastery_score 的旧消费者显示「—」而权威口径显示 μ, 同屏打架。
        a, b = fm_num(fm, "mastery_a"), fm_num(fm, "mastery_b")
        if a is not None and b is not None and a > 0 and b > 0 and fm_num(fm, "mastery_score") is None:
            warnings.append(f"{path.stem!r}: 有 mastery_a/b 状态量但缺 mastery_score 显式分 (疑似手工编辑)")
        grouped[board].append(Member(path.stem, fm, body))

    for members in grouped.values():
        members.sort(key=lambda m: m.node_id)  # 与 manifest nodes[] 同序 (文件名序)
    return grouped, warnings


# ── Concepts 段定位与重写 ──


def locate_section(lines: list[str]) -> tuple[int, int] | None:
    """`## Concepts` 段 → (首行索引, 结束索引 exclusive)，不含标题行本身。"""
    start = next((i for i, ln in enumerate(lines) if _CONCEPTS_HEADING.match(ln)), None)
    if start is None:
        return None
    end = next((j for j in range(start + 1, len(lines)) if _NEXT_HEADING.match(lines[j])), len(lines))
    return start + 1, end


#: 迁移时要删掉的**遗留**注释块特征串 (2.6 之前那份「本 section 由三处维护」)。
#: ⛔ 只删这一种注释, 用户自己写的 HTML 注释一律保留。
_LEGACY_COMMENT_MARK = "本 section 由三处维护"

#: 本脚本 render() 的输出形状 —— 「我能从真相源逐字重建它, 所以我敢删」
_SCRIPT_LINE = re.compile(
    r"^- \[\[节点/([^\]|#^]+)\]\] — (?:种子|派生(?:自 .+?)?) · "
    r"(?:待剖析占位|掌握度 (?:\d\.\d{2}|—) · (?:未考|已考 \d+ 次))$"
)
#: plugin 两个构造器的输出形状 (node-derivation.ts buildBoardConceptsLine /
#: configure-whiteboard.ts buildSeedConceptsLine) —— 同样是可重建的机器产物
_PLUGIN_LINE = re.compile(r"^- \[\[节点/([^\]|#^]+)\]\] — (?:.+?, weak \(0\.30\)|seed note \(mastery: 0\.30\))$")

_FENCE_RE = re.compile(r"^\s{0,3}(`{3,}|~{3,})")
_LIST_ITEM_RE = re.compile(r"^\s*(?:[-*+]|\d+[.)])\s")


def code_spans(lines: list[str], lo: int, hi: int) -> set[int]:
    """段内属于代码块 (``` / ~~~ 围栏、4 空格或 tab 缩进块) 的行号。

    ⛔ 第 3 轮审查根因 B: 全程只看单行正则 ⇒ 围栏里的 `- [[x]]` 被当概念行删掉,
    只剩空壳栅栏; 更糟的是迁移态 `insert_at` 会落进围栏, **整个 AUTO-GENERATED
    块被永久种进代码块里** —— Obsidian 不解析围栏内 wikilink, 该板 Graph View
    正向边归零, 而文本层看起来一切正常、`--check` 全绿。
    「保 Graph View 正向边」恰恰是选方案 B 而非 Dataview 视图化的头号理由。
    """
    spans: set[int] = set()
    fence: str | None = None
    for i in range(lo, hi):
        line = lines[i]
        m = _FENCE_RE.match(line)
        if fence is None and m:
            fence = m.group(1)[0]
            spans.add(i)
            continue
        if fence is not None:
            spans.add(i)
            if m and m.group(1)[0] == fence:
                fence = None
            continue
        # ⛔ 缩进代码块判定必须排除**嵌套列表项**: 在 `## Concepts` 这种整段都是
        # 清单的地方, `\t- [[x]]` 几乎一定是嵌套列表而不是代码块。误判成代码块
        # 会让它整行豁免出保护逻辑, 连告警都不发 (本条自测抓到)。
        if line.startswith(("    ", "\t")) and line.strip() and not _LIST_ITEM_RE.match(line):
            spans.add(i)
    return spans


def split_sentinel_tails(lines: list[str]) -> tuple[list[str], set[int]]:
    """把**追加在 sentinel 行尾**的用户文字拆成独立行 —— 保命前置。

    ⛔ 2026-08-11 UAT 首次真实使用即踩中 (审查 C-H1 的同族漏网):
    用户在 Obsidian Live Preview 里 sentinel 渲染成一段可见文本, 想「在它下面写」
    很容易落到**行尾**, 于是那行变成
        `<!-- /AUTO-GENERATED n=2 · synced ... -->我的备注：先补 asymptotics`
    而 `_END_RE` 是**前缀匹配** ⇒ 整行(连同用户文字)进 doomed ⇒ 下次同步直接删掉。

    修法不是「拒绝这种写法」而是**拆行保留**: sentinel 部分照常受管, 尾巴变成
    紧跟其后的独立行, 用户怎么写都不丢。

    → (拆完的行列表, **受保护**行号集合)。受保护行必须排除在 doomed 之外 ——
    BEGIN 注释块收尾行的尾巴拆出来后正好落在 BEGIN..END 区间内, 不保护就会被
    当成「块内容」二次删除 (本条实现首版的自测即抓到)。
    """
    out: list[str] = []
    protected: set[int] = set()
    in_begin_comment = False
    for ln in lines:
        stripped = ln.strip()
        is_sentinel = _BEGIN_RE.match(stripped) or _END_RE.match(stripped) or in_begin_comment
        if _BEGIN_RE.match(stripped):
            in_begin_comment = True
        if is_sentinel:
            idx = ln.find("-->")
            if idx != -1:
                in_begin_comment = False
                head, tail = ln[: idx + 3], ln[idx + 3 :]
                if tail.strip():
                    out.append(head)
                    protected.add(len(out))
                    out.append(tail.lstrip())
                    continue
        out.append(ln)
    return out, protected


def managed_lines(
    lines: list[str], lo: int, hi: int, members: list[Member], protected: set[int] | None = None
) -> tuple[set[int], int, list[str], list[str]]:
    """段内**逐行**标记受管行 → (待删行号集合, 新块插入位置)。

    ⛔⛔ 逐行删, **绝不取包络** (RAG-S2.6 独立审查 H1 —— 真实数据损坏):
    包络取 min..max 会把区间内一切非概念行连坐删除。已复现的丢失链路:
    用户在 Concepts 段手写 `> [!note]+ 我的分组备忘` → 下次 `Cmd+Shift+D`
    时 plugin 在**段尾**追加一行裸 wikilink (落在备忘之后) → 同步时备忘正好
    夹在 sentinel 与游离行之间 → **被静默删除, 无告警无备份**。
    同族受害者: 段内 fenced code block (只剩孤儿闭合栅栏)、`---` 水平线、
    用户手写 callout。

    受管行 = ① sentinel 块 BEGIN..END 之间(含) ② **可重建的**机器产物概念行
             ③ 迁移时的遗留「三处维护」注释块。其余一律原样保留。

    ⛔⛔ 第 3 轮审查根因 A —— 判据必须是**白名单**不是黑名单:
    「它长得像清单所以我删」会杀掉模仿得最好的用户。实测永久丢失(不会重生):
      `- [[教材第三章]] 这本书要重看`  → 整行消失, 双链一起没
      `- [[原白板/线性代数]]`          → 同上
      `- [[节点/成员甲]] 我卡在第 3 步` → 链接在块内重生, **批注文字蒸发**
    新判据 = 「我能从真相源逐字重建这一行, 所以我敢删」:
      节点非本板成员            → **永远保留** + 告警 (让 --check 红)
      稳态(有 sentinel)         → 只收编匹配 _SCRIPT_LINE / _PLUGIN_LINE 的行
      迁移态(无 sentinel)       → 收编成员行(那是一次性转换), 但逐行 echo 原文

    → (待删行号, 插入位置, 告警列表, 被删行原文列表)
    """
    doomed: set[int] = set()
    insert_at: int | None = None
    warns: list[str] = []
    deleted: list[str] = []
    fenced = code_spans(lines, lo, hi)  # ⛔ 围栏内一行不碰 (根因 B)
    member_ids = {m.node_id for m in members}

    # ⛔ 段内**所有** sentinel 标记与其区间一并收编 (审查 FIX-5 第 5 点):
    # 原来只找第一对 ⇒ 重复块 / 孤儿 END 永久残留, `--check` 恒红且修不好。
    # 全收编后重建成唯一一块 = **自愈**, 比「拒绝写盘让用户手工清」友好得多。
    marks = [
        (i, "B" if _BEGIN_RE.match(lines[i].strip()) else "E")
        for i in range(lo, hi)
        if i not in fenced and (_BEGIN_RE.match(lines[i].strip()) or _END_RE.match(lines[i].strip()))
    ]
    steady = False
    open_at: int | None = None
    for idx, kind in marks:
        doomed.add(idx)
        if insert_at is None:
            insert_at = idx
        if kind == "B":
            open_at = idx
        elif open_at is not None:
            doomed.update(range(open_at, idx + 1))
            open_at, steady = None, True
    if len(marks) > 2:
        warns.append(f"段内有 {len(marks)} 个 sentinel 标记(正常应为 2), 已全部收编重建成唯一一块")

    i = lo
    while i < hi:
        if i in doomed or i in fenced:
            i += 1
            continue
        stripped = lines[i].strip()
        if stripped.startswith("<!--"):
            # ⛔ sentinel 行上的 `-->` **不算**用户注释的收尾: 同步一次后自动块
            # 就紧跟在未闭合注释之后, 扫描会被它「假性闭合」→ 告警消失, 而
            # Obsidian 的真解析器会把块首行吞进用户注释, 渲染直接坏掉。
            j = i
            while j < hi and ("-->" not in lines[j] or j in doomed):
                j += 1
            if j >= hi:
                # ⛔ 未闭合注释不得吞掉半个段 (根因 B/审查 M3): 原来 i=j+1=hi
                # 直接跳出循环, 段内其余行全部脱管 → 旧行不清、新块又生成一份
                warns.append("段内有未闭合 HTML 注释, 其后内容未纳入托管")
                i += 1
                continue
            if any(_LEGACY_COMMENT_MARK in lines[k] for k in range(i, j + 1)):
                doomed.update(range(i, j + 1))
                if insert_at is None:
                    insert_at = i
            i = j + 1
            continue

        m = _CONCEPT_LINE.match(lines[i])
        if m:
            node_id = basename(m.group(1))
            machine = bool(_SCRIPT_LINE.match(lines[i]) or _PLUGIN_LINE.match(lines[i]))
            if node_id not in member_ids:
                warns.append(f"段内非成员 wikilink 已保留: [[{m.group(1)}]] — 要入目录请改该节点的 source_board")
            elif steady and not machine:
                warns.append(f"段内 [[{m.group(1)}]] 那行带了自定义文字, 已保留未收编 — 目录另有一份自动行")
            else:
                doomed.add(i)
                deleted.append(lines[i])
                if insert_at is None:
                    insert_at = i
        i += 1

    if insert_at is None:  # 段内无任何托管内容 → 插在首个非空、非围栏行处
        k = lo
        while k < hi and (not lines[k].strip() or k in fenced):
            k += 1
        insert_at = k
    # ⛔ 从 sentinel 行尾拆出来的用户文字恒不受管 (它落在 BEGIN..END 区间内,
    # 不豁免就会被当「块内容」二次删除)
    return doomed - (protected or set()), insert_at, warns, deleted


#: 空板占位行 — 非 `- [[...]]` 形状, 不会被 manifest 的 Concepts 窄解析当成成员
_EMPTY_HINT = "_（暂无节点 — 在源笔记选中文本按 `Cmd+Shift+D` 派生第一个）_"


def render_block(members: list[Member], synced: str) -> list[str]:
    body = [m.render() for m in members] if members else [_EMPTY_HINT]
    return [
        _SENTINEL_BEGIN,
        _SENTINEL_NOTE,
        *body,
        f"<!-- /AUTO-GENERATED n={len(members)} · synced {synced} -->",
    ]


def _strip_stamp(lines: list[str]) -> list[str]:
    """比对用视图: 把 `<!-- /AUTO-GENERATED ... -->` 尾行归一掉时间戳。

    ⛔ 尾行含 synced 时间戳, 参与比对会让 --check 永远报漂移 (幂等锁失效)。
    内容没变就整个不写盘 → 时间戳自然保持不动, 「有变更才刷戳」。
    """
    return [re.sub(r"·\s*synced\s+\S+\s*-->$", "· synced -->", ln) if _END_RE.match(ln.strip()) else ln for ln in lines]


class NoConceptsSection(Exception):
    """白板缺 `## Concepts` 段 —— 无处安放目录, 必须显式失败。

    ⛔ 绝不能静默返回「无变更」(RAG-S2.6 审查 MEDIUM-4): 三处 skill 的降级判据都是
    「脚本缺失 / 非零退出 / 报无 Concepts 段」, 若这里 exit 0 且 stdout 打印
    「= 已同步 / ✓ 完成」, 调用方会把**根本没同步**判成成功, 新节点从此隐形。
    """


class MalformedResult(Exception):
    """重建结果结构不合法 —— **写盘前**拒绝, 不是事后告警。

    ⛔ 审查根因 D: 结构配平原来在同步循环之前读原文判定, 首跑必然看不到自己
    即将造出的双 sentinel 块; 而三处 skill 只跑一次, 首跑的静默就是全部。
    """


def sync_board(path: Path, members: list[Member], synced: str) -> tuple[str, str, list[str], list[str]]:
    """→ (原文, 新文, 告警, 被删行原文)。无变更时前两者相等；缺段抛 NoConceptsSection。

    ⛔ 行尾用 `split("\\n")` 不用 `splitlines()` (审查 M9): splitlines 会在
    U+000B/U+000C/U+0085/U+2028/U+2029 上额外切分, join 回来时全被归一成 \\n,
    于是「段外原样保留」的承诺在含这些字符的文件上不成立 (CRLF 同理: 下面
    显式记录并还原原行尾)。
    """
    original = path.read_text(encoding="utf-8", newline="")
    fm, _ = split_frontmatter(original)
    crlf = "\r\n" in original
    lines = original.replace("\r\n", "\n").split("\n")
    trailing_nl = lines and lines[-1] == ""
    if trailing_nl:
        lines = lines[:-1]
    # ⛔ 先定位再拆行, 且**只在段内切片上**拆 (第 3 轮审查根因 C):
    # split_sentinel_tails 原来遍历整个文件, `in_begin_comment` 会泄漏出
    # `## Concepts` 段, 一路开到下一个含 `-->` 的行 —— 真板 CS 61B.md 的
    # dataviewjs 里 `chart += \`  ${src} -->|派生| ${dst}\\n\`;` 正是受害行,
    # 被劈成两行, 正面违反 docstring「段外原样保留」的承诺。
    span = locate_section(lines)
    if span is None:
        raise NoConceptsSection(path.name)
    lo, hi = span
    seg, prot_rel = split_sentinel_tails(lines[lo:hi])
    lines = lines[:lo] + seg + lines[hi:]
    hi = lo + len(seg)
    protected = {lo + i for i in prot_rel}

    doomed, insert_at, warns, deleted = managed_lines(lines, lo, hi, members, protected)
    new_block = render_block(members, synced)

    # ⛔ 落在块内的 protected 行要保持「抬头」语义 (审查 FORM-06): 否则用户写在
    # BEGIN 收尾行行尾的文字会从「清单上方」跳到「END 下方」
    head_idx = {i for i in protected if insert_at <= i < hi}
    rebuilt: list[str] = []
    for i, ln in enumerate(lines):
        if i == insert_at:
            rebuilt.extend(lines[j] for j in sorted(head_idx))
            rebuilt.extend(new_block)
        if i in doomed or i in head_idx:
            continue
        rebuilt.append(ln)
    if insert_at >= len(lines):  # 插入点在段尾之外 (段内全空)
        rebuilt.extend(new_block)

    # doc_count 归一到实际成员数 (根除声明/实际漂移); 缺字段不擅自新增。
    # ⛔ 在**行列表**上改, 不在 join 后的串上改 (审查 M9 的连带): 串上做
    # `partition("\n---")` 会切在 CRLF 的中间, `.*$` 再把 `\r` 吃掉, 于是
    # 文件里混出一个裸 LF。
    # ⛔ 全量替换而非只改首处 (审查 M10): 重复 key 时 YAML/后端取最后一个。
    if re.search(r"^doc_count:[ \t]*", fm, re.M):
        fm_end = next((i for i in range(1, len(rebuilt)) if rebuilt[i].strip() == "---"), None)
        if fm_end is not None:
            for i in range(1, fm_end):
                if re.match(r"^doc_count:[ \t]*", rebuilt[i]):
                    rebuilt[i] = f"doc_count: {len(members)}"

    # 内容等价 (忽略 synced 时间戳) → 整个不写盘, 保留旧时间戳
    if _strip_stamp(rebuilt) == _strip_stamp(lines):
        rebuilt = lines

    # ⛔ 结构配平对**即将写入的 rebuilt** 判定, 不对读到的原文 (审查根因 D):
    # 原来检查跑在同步循环之前, 首跑必然看不到自己即将造出的双块 —— 而三处
    # skill 只跑一次, 首跑的静默就是全部。写坏之前拒绝, 不是事后告警。
    nb = sum(1 for ln in rebuilt if _BEGIN_RE.match(ln.strip()))
    ne = sum(1 for ln in rebuilt if _END_RE.match(ln.strip()))
    if nb != 1 or ne != 1:
        raise MalformedResult(f"{path.name}: 将写出 BEGIN×{nb}/END×{ne}, 拒绝写盘")

    eol = "\r\n" if crlf else "\n"
    return original, eol.join(rebuilt) + (eol if trailing_nl else ""), warns, deleted


# ── CLI ──


def _diff(name: str, old: str, new: str) -> str:
    return "".join(
        difflib.unified_diff(old.splitlines(True), new.splitlines(True), f"a/{name}", f"b/{name}", n=2)
    )


def atomic_write(path: Path, text: str) -> None:
    """tmp + fsync + os.replace 原子写，并**保留原文件权限**。

    三条都是 RAG-S2.6 独立审查抓出来的 (前两条已在真 vault 生效过):
      M6 `mkstemp` 恒建 0600, `os.replace` 让目标继承 tmp 的 mode ——
         真 vault 6 块白板已被从 0644 静默改成 0600 (未申报的元数据改写)
      M7 无 fsync: rename 元数据可先于数据落盘, 掉电留 0 长度白板 ——
         docstring 却声称「半成品永不可见」(那只对并发 reader 成立)
      M8 symlink 白板会被替换成实体文件, 链接目标静默分叉
    """
    if path.is_symlink():
        raise OSError(f"{path.name} 是符号链接, 拒绝就地替换 (会把链接换成实体文件)")
    mode = path.stat().st_mode if path.exists() else None
    fd, tmp_name = tempfile.mkstemp(dir=path.parent, prefix=path.name + ".", suffix=".tmp")
    tmp = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as f:
            f.write(text)
            f.flush()
            os.fsync(f.fileno())
        if mode is not None:
            os.chmod(tmp, mode)
        os.replace(tmp, path)
        dir_fd = os.open(path.parent, os.O_RDONLY)  # 目录项也要落盘
        try:
            os.fsync(dir_fd)
        finally:
            os.close(dir_fd)
    finally:
        tmp.unlink(missing_ok=True)


def main() -> int:
    ap = argparse.ArgumentParser(description="原白板 ## Concepts 自动重算 (RAG-S2.6)")
    ap.add_argument("--vault", help="vault 根目录 (缺省 = 本脚本所在 vault)")
    ap.add_argument("--board", help="只同步这一块白板 (文件名 stem)")
    ap.add_argument("--all", action="store_true", help="同步全部白板")
    ap.add_argument("--check", action="store_true", help="只校验不写盘; 有待同步变更 exit 1")
    ap.add_argument("--backup", action="store_true", help="写盘前落 <file>.bak (迁移用)")
    args = ap.parse_args()

    if not (args.board or args.all or args.check):
        ap.error("需要 --board <id> / --all / --check 之一")

    vault = Path(args.vault) if args.vault else Path(__file__).resolve().parents[2]
    if not (vault / NODE_DIR).is_dir() or not (vault / BOARD_DIR).is_dir():
        print(f"✗ vault 结构缺失 (需 {NODE_DIR}/ 与 {BOARD_DIR}/): {vault}", file=sys.stderr)
        return 2

    grouped, warnings = scan_members(vault)
    targets = [args.board] if args.board else sorted(grouped)
    missing = [b for b in targets if b not in grouped]
    if missing:
        print(f"✗ 白板不存在: {missing} (可选: {sorted(grouped)})", file=sys.stderr)
        return 2

    # 结构性告警必须可见且让 --check 红 (审查 M11/M12/L15)
    for w in warnings:
        print(f"  ⚠ {w}")

    # 多 sentinel / END 早于 BEGIN 会留孤儿注释且之后恒绿 (审查 M13)
    for board_id in targets:
        try:
            text = (vault / BOARD_DIR / f"{board_id}.md").read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        # ⛔ _BEGIN_RE/_END_RE 编译时没带 re.M, findall 的 `^` 只匹配串首 —— 必须逐行数
        board_lines = text.replace("\r\n", "\n").split("\n")
        nb = sum(1 for ln in board_lines if _BEGIN_RE.match(ln.strip()))
        ne = sum(1 for ln in board_lines if _END_RE.match(ln.strip()))
        nh = sum(1 for ln in board_lines if _CONCEPTS_HEADING.match(ln))
        if nb > 1 or ne > 1 or (nb != ne and nb + ne > 0) or nh > 1:
            warnings.append(f"{board_id}: sentinel BEGIN×{nb}/END×{ne}、`## Concepts` 标题×{nh} — 结构异常, 会留孤儿注释")
            print(f"  ⚠ {warnings[-1]}")

    synced = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    changed, broken, failed = 0, 0, 0
    for board_id in targets:
        path = vault / BOARD_DIR / f"{board_id}.md"
        members = grouped[board_id]
        try:
            old, new, board_warns, deleted = sync_board(path, members, synced)
        except NoConceptsSection:
            # ⛔ 非零退出 + stdout 明说没同步 (审查 MEDIUM-4): 调用方按退出码判降级
            broken += 1
            print(f"  ✗ {board_id}  ({len(members)} 成员, **无 `## Concepts` 段, 未同步**)")
            continue
        except MalformedResult as e:
            failed += 1
            print(f"  ✗ {board_id}: {e} (文件零改动)", file=sys.stderr)
            continue
        except (OSError, UnicodeDecodeError) as e:
            failed += 1
            print(f"  ✗ {board_id}: 读取失败 {type(e).__name__}: {e}", file=sys.stderr)
            continue

        for w in board_warns:
            warnings.append(f"{board_id}: {w}")
            print(f"  ⚠ {board_id}: {w}")
        # ⛔ 删除动作必须留痕 (审查 FIX-3): 三处生产调用方都不带 --backup、
        # 不跑 --check, 6 块真板只有 1 块被 git 跟踪 —— 静默删除 = 不可发现
        # 且不可恢复。凡删必逐行 echo 原文。
        for line in deleted:
            print(f"    − 收编(删除)段内行: {line!r}")

        if old == new:
            print(f"  = {board_id}  ({len(members)} 成员, 已同步)")
            continue
        changed += 1
        print(f"  ~ {board_id}  ({len(members)} 成员, 需更新)")
        if args.check:
            print(_diff(f"{BOARD_DIR}/{board_id}.md", old, new))
            continue
        try:
            if args.backup:
                # ⛔ 不覆盖已有 .bak (审查 M14): 第二次跑 --backup 会把「备份」
                # 覆盖成上一次同步后的内容, 真正的原件永久丢失
                bak = path.with_suffix(".md.bak")
                if bak.exists():
                    print(f"    ℹ {bak.name} 已存在, 保留最早那份原件不覆盖")
                else:
                    bak.write_text(old, encoding="utf-8")
            atomic_write(path, new)
        except OSError as e:
            # ⛔ 写盘纳入 per-board 隔离 (审查 H5): 原来它在 try 之外, 一块失败
            # 直接冒泡未捕获异常, 已写的不回滚、未处理的不再处理, 且 rc=1 与
            # 「--check 有漂移」同码, 调用方分不清「崩了」和「有漂移」
            failed += 1
            print(f"  ✗ {board_id}: 写入失败 {type(e).__name__}: {e}", file=sys.stderr)
            continue

    # ⛔ 退出码分层 (审查 H5): 2 = 环境/IO 出错, 1 = 有待同步漂移, 0 = 全绿。
    # 调用方 (三处 skill 的降级判据) 才分得清「崩了」和「有漂移」。
    if failed or broken:
        if broken:
            print(f"\n✗ {broken} 块白板缺 `## Concepts` 段, 目录**未写入** (加回该段或用模板重建白板)")
        if failed:
            print(f"\n✗ {failed} 块白板读写失败, 目录**未写入**")
        return 2
    if args.check:
        if changed or warnings:
            if changed:
                print(f"\n✗ {changed} 块白板的 ## Concepts 与真相源不一致 (跑 --all 同步)")
            if warnings:
                print(f"✗ {len(warnings)} 条结构性告警 (孤儿节点 / 断链节点名 / sentinel 异常), 见上方 ⚠")
            return 1
        print(f"\n✓ 全部 {len(targets)} 块白板已同步 (幂等), 无结构性告警")
        return 0
    print(f"\n✓ 完成: {changed} 块已更新 / {len(targets) - changed} 块无变更")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
