"""G5-2 — 拆分建议 preview 引擎裁判 (BATCH-2026-08-27-第四批 / CARD-G5-2)。

被测物: canvas-vault/.claude/skills/board-split/scripts/split_preview.py
(scripts-only 只读 preview 引擎, 无 SKILL.md, 不触 EXPECTED_SKILLS)。

裁判覆盖 (卡片 (d) 钦定六类 + slug 金样本):
  1. slug 金样本双向断言 — 现网截断名 Eigenvalues-are-special-vectors-that-sat
     (P4 修复前硬砍 40 字符) ↔ 现行词边界回退规则终值, 两个值都钉死
  2. 重名 — 候选名撞 节点/ 扁平池 → _2.._9 规则 (同 resolveUniqueNodeName), 9+ 诚实标不可解
  3. 派生重叠 — 小节内「已派生为 [[节点/X]]」callout → derived_overlap 命中
  4. 中文 NFC/NFD — 池内 NFD 文件名 vs NFC 候选名 → 仍判重名
  5. 生成段剥离 — 只按确定性标记 (AUTO-GENERATED 对 / 代码 fence / Recent Activity);
     纯脚手架板 0 单元 + 诚实自陈; fence 内标题不算小节
  6. 同输入二跑 diff 空 — JSON 与 MD 逐字节相等 (零时间戳零随机)
  7. 规模门截断 — 超过 --max-units 按文档序保留并声明截断
  8. 零写侧 — --out-dir 指到 vault 外时, vault 全树 (含 mtime) 前后一致

fixtures 全部在 tmp_path 程序化构造 (NFD 文件名进 git 会被平台归一化搅浑,
程序化构造保证跨平台确定性), 构造逻辑即 fixture 定义。
"""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
import unicodedata
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
SCRIPT = REPO_ROOT / "canvas-vault" / ".claude" / "skills" / "board-split" / "scripts" / "split_preview.py"

# ── 金样本 (真相源: frontend/obsidian-plugin/src/node-derivation.ts:32 deriveConceptStub
#    + 现网节点 canvas-vault/节点/Eigenvalues-are-special-vectors-that-sat.md 的派生起点原文) ──
GOLDEN_SELECTED = (
    "Eigenvalues are special vectors that satisfy Av = λv, where A is a square matrix, "
    "v is the eigenvector, and λ is the eigenvalue"
)
GOLDEN_LIVE_NAME = "Eigenvalues-are-special-vectors-that-sat"  # P4 修复前硬砍 40 字符的现网名
GOLDEN_CURRENT_RULE = "Eigenvalues-are-special-vectors-that"  # 现行规则: 硬砍后回退最近 - 词边界


def load_module():
    if not SCRIPT.exists():
        pytest.fail(f"被测脚本不存在: {SCRIPT}")
    spec = importlib.util.spec_from_file_location("split_preview", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def run_cli(vault: Path, board: str, out_dir: Path, *extra: str) -> subprocess.CompletedProcess:
    if not SCRIPT.exists():  # ⛔ 防「脚本不存在 → returncode≠0 → 拒绝类断言假绿」
        pytest.fail(f"被测脚本不存在: {SCRIPT}")
    return subprocess.run(
        [sys.executable, str(SCRIPT), "--vault", str(vault), "--board", board, "--out-dir", str(out_dir), *extra],
        capture_output=True,
        text=True,
        timeout=60,
    )


# ────────────────────────── fixture 构造器 ──────────────────────────

BOARD_SCAFFOLD = """---
type: whiteboard
board_name: {board}
---

# {board}

> [!info]+ 原白板说明（扁平架构 · round-11）
> 这是学习主题"**{board}**"的原白板。本文档即白板本身。

## Concepts

<!-- AUTO-GENERATED by .claude/scripts/sync_board_concepts.py · 真相源 = 节点 frontmatter source_board
     ⛔ 请勿手改 -->
{concepts}
<!-- /AUTO-GENERATED n={n} · synced 2026-08-10T23:45:15Z -->

🧠 **思维导图**：[[outputs/思维导图-{board}.excalidraw|在 Excalidraw 里看派生关系]]

## 🔗 节点关系图（v2.8）

```dataviewjs
const nodes = dv.pages('"节点"');
## 这行在 fence 内，绝不能被当成小节标题
```

> **白板 = 节点关系**（社区共识）。

## Recent Activity

- 2026-05-09T08:54:18.093Z: Whiteboard created

### Recent Activity 里的伪标题也不能算小节

- 2026-05-09T08:55:49.789Z: Extracted [[节点/X]] via canvas:ai-linked-doc
"""


def make_vault(
    tmp_path: Path, board: str, concepts: list[str], seed_files: dict[str, str], extra_nodes: list[str] = ()
) -> Path:
    vault = tmp_path / "vault"
    for d in ("原白板", "节点", "检验白板", "outputs"):
        (vault / d).mkdir(parents=True, exist_ok=True)
    lines = "\n".join(f"- {c}" for c in concepts)
    (vault / "原白板" / f"{board}.md").write_text(
        BOARD_SCAFFOLD.format(board=board, concepts=lines, n=len(concepts)), encoding="utf-8"
    )
    for name, body in seed_files.items():
        (vault / "节点" / f"{name}.md").write_text(body, encoding="utf-8")
    for name in extra_nodes:
        (vault / "节点" / f"{name}.md").write_text(f"# {name}\n", encoding="utf-8")
    return vault


SEED_RICH = """---
type: concept
source_board: "[[原白板/{board}]]"
created_from: configure_whiteboard_seed
---

# 种子讲义

## 一、代理与环境

### 1.1 代理 (Agent) 的定义 [05:50]()

一个代理是能够感知环境并采取行动的实体，这里要展开讲清楚感知与行动两个面。
第二段：代理函数把感知历史映射到行动，这个映射是我们分析一切代理的数学起点。

> [!relation/refines]+ 已派生为 [[节点/已派生的旧节点]] · 细化

### 1.2 理性代理 (Rational Agents) [08:54]()

理性代理追求预期效用最大化，这句话里每个词都有讲究，先说预期再说效用最大化。
第二段：理性不等于全知，理性是在可得信息下做当前最优选择的能力，考试常考这个区分。

## 二、搜索问题

### 2.1 Eigenvalues intro [21:06]()

Eigenvalues are special vectors that satisfy Av = λv, where A is a square matrix, v is the eigenvector, and λ is the eigenvalue
第二段：这里塞一个金样本句子做重名与截断的双向断言，正文凑够两行门槛。

```python
### fence 内伪标题（生成段剥离测试）
print("not a heading")
```
"""


# ────────────────────────── 1 · slug 金样本双向断言 ──────────────────────────


class TestGoldenSlug:
    def test_hard_cut_reproduces_live_truncated_name(self):
        """方向一: 40 字符硬砍中间值 == 现网节点名 (证明 Unicode-aware 截断与现网逐字符等价)。"""
        mod = load_module()
        cleaned = mod._clean_for_slug(GOLDEN_SELECTED)
        assert mod._hard_cut(cleaned, 40) == GOLDEN_LIVE_NAME

    def test_current_rule_backs_off_to_word_boundary(self):
        """方向二: 现行规则 (P4 词边界回退) 终值 == deriveConceptStub 今日输出。"""
        mod = load_module()
        assert mod.derive_concept_stub(GOLDEN_SELECTED) == GOLDEN_CURRENT_RULE

    def test_ts_parity_cases(self):
        """与 node-derivation.ts 逐条对齐的行为样例。"""
        mod = load_module()
        # 句读截断: 第一个句号前
        assert mod.derive_concept_stub("状态空间。后面不要") == "状态空间"
        # 非法字符移除 + 空白→-
        assert mod.derive_concept_stub("搜索树 (Search  Trees) #核心") == "搜索树-(Search-Trees)-核心"
        # 中文超 40 字无连字符 → 保留硬砍 (边界 < maxLen/2)
        long_cn = "这是一段没有任何连字符的很长很长的中文标题" * 3
        assert len(mod.derive_concept_stub(long_cn)) == 40
        # 空输入 → 确定性 fallback (⛔ TS 用时间戳, 本引擎为确定性改用锚点哈希, 显式偏差)
        fb1, fb2 = mod.derive_concept_stub("", anchor="a/b:1"), mod.derive_concept_stub("", anchor="a/b:1")
        assert fb1 == fb2 and fb1.startswith("derived-")


# ────────────────────────── 2 · 重名 ──────────────────────────


class TestNameConflict:
    def _vault(self, tmp_path, extra_nodes):
        return make_vault(
            tmp_path,
            "板A",
            concepts=["[[节点/种子]] — 种子 · 掌握度 — · 未考"],
            seed_files={"种子": SEED_RICH.format(board="板A")},
            extra_nodes=extra_nodes,
        )

    def test_conflict_resolves_with_suffix(self, tmp_path):
        vault = self._vault(tmp_path, extra_nodes=["代理-(Agent)-的定义"])
        out = tmp_path / "out"
        assert run_cli(vault, "板A", out).returncode == 0
        data = json.loads((out / "split-preview-板A.json").read_text(encoding="utf-8"))
        hit = [c for c in data["candidates"] if c["suggested_name"] == "代理-(Agent)-的定义"]
        assert hit and hit[0]["name_conflict"] is True
        assert hit[0]["resolved_name"] == "代理-(Agent)-的定义_2"
        assert hit[0]["conflict_with"] == "节点/代理-(Agent)-的定义.md"

    def test_nine_plus_conflicts_marked_unresolvable(self, tmp_path):
        base = "代理-(Agent)-的定义"
        vault = self._vault(tmp_path, extra_nodes=[base] + [f"{base}_{i}" for i in range(2, 10)])
        out = tmp_path / "out"
        assert run_cli(vault, "板A", out).returncode == 0
        data = json.loads((out / "split-preview-板A.json").read_text(encoding="utf-8"))
        hit = [c for c in data["candidates"] if c["suggested_name"] == base]
        assert hit and hit[0]["conflict_unresolvable"] is True


# ────────────────────────── 3 · 派生重叠 ──────────────────────────


class TestDerivedOverlap:
    def test_callout_marks_overlap(self, tmp_path):
        vault = make_vault(
            tmp_path,
            "板A",
            concepts=["[[节点/种子]] — 种子 · 掌握度 — · 未考"],
            seed_files={"种子": SEED_RICH.format(board="板A")},
        )
        out = tmp_path / "out"
        assert run_cli(vault, "板A", out).returncode == 0
        data = json.loads((out / "split-preview-板A.json").read_text(encoding="utf-8"))
        by_heading = {tuple(c["source_anchor"]["heading_path"]): c for c in data["candidates"]}
        overlapped = [c for c in data["candidates"] if c["derived_overlap"]["overlapping"]]
        assert overlapped, f"应有小节命中派生重叠: {sorted(by_heading)}"
        assert "已派生的旧节点" in overlapped[0]["derived_overlap"]["existing_nodes"]
        # 未被 callout 覆盖的小节不许连坐
        clean = [c for c in data["candidates"] if not c["derived_overlap"]["overlapping"]]
        assert clean


# ────────────────────────── 4 · 中文 NFC/NFD ──────────────────────────


class TestUnicodeNormalization:
    def test_nfd_pool_file_still_conflicts_with_nfc_candidate(self, tmp_path):
        # 纯汉字无 NFD 分解 (NFC==NFD)——macOS NFD 真正咬人的是中文笔记里混排的
        # 带调拼音/变音拉丁字母 (文件名落盘被分解)。用带调拼音构造分解面。
        heading_word = "误差反向传播-tèzhēngzhí"  # NFC 构造小节标题 → 候选名 NFC
        seed = SEED_RICH.format(board="板A") + (
            f"\n### {heading_word}\n\n第一段正文足够长足够长足够长，凑到确定性门槛之上再多写一点。\n"
            "第二段正文也一样长，两行门槛与字符门槛都要过，不然小节不成立。\n"
        )
        nfd_name = unicodedata.normalize("NFD", heading_word)
        assert nfd_name != heading_word  # 构造前提: 两种编码字节不同
        vault = make_vault(
            tmp_path,
            "板A",
            concepts=["[[节点/种子]] — 种子 · 掌握度 — · 未考"],
            seed_files={"种子": seed},
            extra_nodes=[nfd_name],
        )
        out = tmp_path / "out"
        assert run_cli(vault, "板A", out).returncode == 0
        data = json.loads((out / "split-preview-板A.json").read_text(encoding="utf-8"))
        hit = [c for c in data["candidates"] if c["suggested_name"] == heading_word]
        assert hit and hit[0]["name_conflict"] is True, "NFD 池文件必须与 NFC 候选判重名"


# ────────────────────────── 5 · 生成段剥离 / 纯脚手架板 ──────────────────────────


class TestGeneratedStripping:
    def test_pure_scaffold_board_yields_zero_and_honest_note(self, tmp_path):
        vault = make_vault(tmp_path, "空板", concepts=[], seed_files={})
        out = tmp_path / "out"
        assert run_cli(vault, "空板", out).returncode == 0
        data = json.loads((out / "split-preview-空板.json").read_text(encoding="utf-8"))
        assert data["candidates"] == []
        assert data["scaffold_only"] is True
        assert data["scaffold_note"]
        md = (out / "split-preview-空板.md").read_text(encoding="utf-8")
        assert "0" in md and "脚手架" in md  # 诚实自陈出现在人读版

    def test_link_line_hr_and_multiline_comment_not_content(self, tmp_path):
        """真实板反例 (特征值板实测踩坑): 小节里只有 wikilink 行 + 水平线 + 多行
        HTML 注释的续行 → 不得凑成候选 (注释续行与 hr 不算正文)。"""
        board = BOARD_SCAFFOLD.format(board="板B", concepts="", n=0) + (
            "\n## 只有链接和注释的段\n\n"
            "🧠 **思维导图**：[[outputs/思维导图-板B.excalidraw|在 Excalidraw 里看派生关系]]\n\n"
            "---\n\n"
            "<!-- v2.7 (2026-04-30): 删除两个段\n"
            "     理由：这是注释的续行，字数很多很多很多，绝不能被当成小节正文计数。\n"
            "     现状是死代码占位，删除反映现实。未来 Dashboard v2 想加再加。 -->\n"
        )
        vault = make_vault(tmp_path, "板B", concepts=[], seed_files={})
        (vault / "原白板" / "板B.md").write_text(board, encoding="utf-8")
        out = tmp_path / "out"
        assert run_cli(vault, "板B", out).returncode == 0
        data = json.loads((out / "split-preview-板B.json").read_text(encoding="utf-8"))
        assert data["candidates"] == [], f"垃圾候选混入: {[c['suggested_name'] for c in data['candidates']]}"
        assert data["scaffold_only"] is True

    def test_seed_without_subsections_falls_back_to_whole_doc(self, tmp_path):
        """真实板反例 (Fundamentals 实况): 种子只有 # 一级标题、无 ##+ 小节 →
        回退「整篇 = 1 候选」, 且 # 节内的已派生 callout 照常标重叠。"""
        seed = (
            "---\ntype: concept\n---\n\n"
            "# Linear Algebra Fundamentals\n\n"
            "Eigenvalues are special vectors that satisfy the equation and this paragraph is long enough.\n"
            "Second paragraph keeps the deterministic gate satisfied with more than enough characters.\n\n"
            "> [!relation/extends]+ 已派生为 [[节点/Eigenvalues-are-special-vectors-that-sat]] · 扩展\n"
        )
        vault = make_vault(
            tmp_path,
            "板C",
            concepts=["[[节点/种子]] — 种子 · 掌握度 0.01 · 已考 2 次"],
            seed_files={"种子": seed},
        )
        out = tmp_path / "out"
        assert run_cli(vault, "板C", out).returncode == 0
        data = json.loads((out / "split-preview-板C.json").read_text(encoding="utf-8"))
        whole = [c for c in data["candidates"] if c["basis"] == "seed-note-whole"]
        assert whole, "无 ##+ 小节的种子应回退整篇候选"
        assert whole[0]["suggested_name"] == "Linear-Algebra-Fundamentals"
        assert "Eigenvalues-are-special-vectors-that-sat" in whole[0]["derived_overlap"]["existing_nodes"]

    def test_fence_and_recent_activity_headings_not_candidates(self, tmp_path):
        vault = make_vault(
            tmp_path,
            "板A",
            concepts=["[[节点/种子]] — 种子 · 掌握度 — · 未考"],
            seed_files={"种子": SEED_RICH.format(board="板A")},
        )
        out = tmp_path / "out"
        assert run_cli(vault, "板A", out).returncode == 0
        data = json.loads((out / "split-preview-板A.json").read_text(encoding="utf-8"))
        headings = {c["source_anchor"]["heading_path"][-1] for c in data["candidates"]}
        assert not any("fence 内" in h or "Recent Activity" in h for h in headings)


# ────────────────────────── 6 · 同输入二跑 diff 空 ──────────────────────────


class TestDeterminism:
    def test_two_runs_byte_identical(self, tmp_path):
        vault = make_vault(
            tmp_path,
            "板A",
            concepts=["[[节点/种子]] — 种子 · 掌握度 — · 未考"],
            seed_files={"种子": SEED_RICH.format(board="板A")},
        )
        out1, out2 = tmp_path / "out1", tmp_path / "out2"
        assert run_cli(vault, "板A", out1).returncode == 0
        assert run_cli(vault, "板A", out2).returncode == 0
        for suffix in (".json", ".md"):
            b1 = (out1 / f"split-preview-板A{suffix}").read_bytes()
            b2 = (out2 / f"split-preview-板A{suffix}").read_bytes()
            assert b1 == b2, f"二跑 {suffix} 不相等 (混入时间戳/随机性?)"


# ────────────────────────── 7 · 规模门截断 ──────────────────────────


class TestScaleGate:
    def test_over_threshold_truncates_in_document_order(self, tmp_path):
        sections = "\n".join(
            f"### 小节{i:02d}\n\n第一段正文足够长足够长足够长，凑到确定性门槛之上再多写一点点。\n"
            f"第二段正文也一样长，两行门槛与字符门槛都要过，序号 {i:02d} 用于顺序断言。\n"
            for i in range(1, 13)
        )
        seed = SEED_RICH.format(board="板A") + "\n## 规模门段\n\n" + sections
        vault = make_vault(
            tmp_path,
            "板A",
            concepts=["[[节点/种子]] — 种子 · 掌握度 — · 未考"],
            seed_files={"种子": seed},
        )
        out = tmp_path / "out"
        assert run_cli(vault, "板A", out, "--max-units", "5").returncode == 0
        data = json.loads((out / "split-preview-板A.json").read_text(encoding="utf-8"))
        assert data["scale_gate"]["over_threshold"] is True
        assert data["scale_gate"]["kept"] == 5 == len(data["candidates"])
        assert data["scale_gate"]["total_candidates"] > 5
        # 文档序: 保留的必须**恰为**最先出现的 5 个 (行号递增还不够 —
        # candidates[1:6] 这类实现也满足递增, Codex 二轮 LOW 指出必须钉名单)
        assert [c["suggested_name"] for c in data["candidates"]] == [
            "代理-(Agent)-的定义",
            "理性代理-(Rational-Agents)",
            "Eigenvalues-intro",
            "小节01",
            "小节02",
        ]
        md = (out / "split-preview-板A.md").read_text(encoding="utf-8")
        assert "截断" in md


# ────────────────────────── 8 · 零写侧 ──────────────────────────


class TestReadOnly:
    def test_vault_untouched_when_outdir_external(self, tmp_path):
        vault = make_vault(
            tmp_path,
            "板A",
            concepts=["[[节点/种子]] — 种子 · 掌握度 — · 未考"],
            seed_files={"种子": SEED_RICH.format(board="板A")},
        )

        def snapshot(root: Path) -> dict:
            # v3 (Codex 三轮): 文件 bytes+mtime+mode + 目录集合含 mtime_ns+mode + vault 根本体
            entries = {"<root>": ("d", root.lstat().st_mtime_ns, root.lstat().st_mode)}
            for p in sorted(root.rglob("*")):
                st = p.lstat()
                if p.is_file() and not p.is_symlink():
                    entries[str(p.relative_to(root))] = ("f", st.st_mtime_ns, st.st_mode, p.read_bytes())
                else:
                    entries[str(p.relative_to(root))] = ("d/l", st.st_mtime_ns, st.st_mode)
            return entries

        before = snapshot(vault)
        out = tmp_path / "external-out"
        assert run_cli(vault, "板A", out).returncode == 0
        assert snapshot(vault) == before, "vault 内任何文件/目录 (含 mtime/mode) 不得被触碰"
        produced = sorted(p.name for p in out.iterdir())
        assert produced == ["split-preview-板A.json", "split-preview-板A.md"]

    def test_board_name_containment_rejects_specifically(self, tmp_path):
        """v2 (Codex 二轮 H5): 拒绝必须钉到具体诊断——非法字符走校验器消息且零产物,
        与「板不存在」的消息可区分, 防 validate_board_name 被删后测试仍空洞绿。"""
        vault = make_vault(tmp_path, "板A", concepts=[], seed_files={})
        out = tmp_path / "out"
        for evil in ("../板A", "板A/..", "板`A", "板$A", '板"A'):
            r = run_cli(vault, evil, out)
            assert r.returncode != 0, f"非法板名应拒绝: {evil!r}"
            assert "非法字符" in (r.stderr + r.stdout), f"{evil!r} 未走校验器诊断: {r.stderr[:120]}"
            assert not out.exists() or not list(out.iterdir()), "拒绝路径不得留任何产物"
        # 合法名但板不存在 → 走另一条诊断 (证明两个失败路径没有被混为一谈)
        r2 = run_cli(vault, "不存在的板", out)
        assert r2.returncode != 0 and "不存在" in (r2.stderr + r2.stdout)

    def test_evil_seed_member_skipped_not_read(self, tmp_path):
        """v2 (Codex 二轮 H2): Concepts 成员名带路径逃逸 → 不拼路径不读文件,
        跳过并留痕; vault 外的目标文件保持未读状态 (以其内容不出现在任何产物为证)。"""
        secret = tmp_path / "outside-secret.md"
        secret.write_text(
            "## 外部机密小节\n\n这段内容绝不能出现在任何 preview 产物里第一行。\n这段内容绝不能出现在任何 preview 产物里第二行。\n",
            encoding="utf-8",
        )
        vault = make_vault(
            tmp_path,
            "板A",
            concepts=["[[节点/../../outside-secret]] — 种子 · 掌握度 — · 未考"],
            seed_files={},
        )
        out = tmp_path / "out"
        r = run_cli(vault, "板A", out)
        assert r.returncode == 0
        data = json.loads((out / "split-preview-板A.json").read_text(encoding="utf-8"))
        skipped = [s for s in data["sources"] if s.get("skipped")]
        assert skipped and "越界" in skipped[0]["skipped"]
        blob = (out / "split-preview-板A.json").read_text(encoding="utf-8") + (out / "split-preview-板A.md").read_text(
            encoding="utf-8"
        )
        assert "外部机密" not in blob

    def test_symlink_seed_skipped(self, tmp_path):
        outside = tmp_path / "outside-note.md"
        outside.write_text(
            "# 链接外部\n\n外部正文一外部正文一外部正文一外部正文一外部正文一。\n外部正文二外部正文二外部正文二外部正文二外部正文二。\n",
            encoding="utf-8",
        )
        vault = make_vault(tmp_path, "板A", concepts=["[[节点/链接种子]] — 种子 · 掌握度 — · 未考"], seed_files={})
        (vault / "节点" / "链接种子.md").symlink_to(outside)
        out = tmp_path / "out"
        r = run_cli(vault, "板A", out)
        assert r.returncode == 0
        data = json.loads((out / "split-preview-板A.json").read_text(encoding="utf-8"))
        skipped = [s for s in data["sources"] if s.get("skipped")]
        assert skipped and "symlink" in skipped[0]["skipped"]

    def test_outdir_ancestor_symlink_rejected_with_zero_write(self, tmp_path):
        """v3 (Codex 三轮 H1): out-dir 祖先是 symlink → 拒绝, 且**物理目标处零写**
        (v2 曾 mkdir 先于检查, 在 real-dir 下留下目录 = 「拒绝但已写」假绿)。"""
        vault = make_vault(tmp_path, "板A", concepts=[], seed_files={})
        real = tmp_path / "real-dir"
        real.mkdir()
        link = tmp_path / "link-dir"
        link.symlink_to(real)
        r = run_cli(vault, "板A", link / "out")
        assert r.returncode != 0 and "symlink" in (r.stderr + r.stdout)
        assert not (real / "out").exists(), "拒绝路径在物理目标处留下了目录 (拒绝但已写)"
        assert list(real.iterdir()) == [], "物理目标目录必须保持空"

    def test_vault_content_dir_symlink_rejected(self, tmp_path):
        """v3 (Codex 三轮 H2): 节点/ 目录本身是 symlink → 整体拒绝 (叶子
        is_symlink()==False 的外部文件会借目录链接越界)。"""
        outside = tmp_path / "outside-nodes"
        outside.mkdir()
        (outside / "外部种子.md").write_text(
            "# 外部\n\n正文正文正文正文正文正文正文正文正文正文。\n再来一行正文正文正文正文正文正文正文正文。\n",
            encoding="utf-8",
        )
        vault = make_vault(tmp_path, "板A", concepts=["[[节点/外部种子]] — 种子 · 掌握度 — · 未考"], seed_files={})
        import shutil as _sh

        real_nodes = tmp_path / "moved-nodes"
        _sh.move(str(vault / "节点"), str(real_nodes))
        (vault / "节点").symlink_to(outside)
        r = run_cli(vault, "板A", tmp_path / "out")
        assert r.returncode != 0 and "symlink" in (r.stderr + r.stdout)

    def test_hardlinked_target_rejected(self, tmp_path):
        """v2 (Codex 二轮 H1): 既存目标文件 nlink>1 → 拒绝 (防 hardlink 引流)。"""
        import os as _os

        vault = make_vault(tmp_path, "板A", concepts=[], seed_files={})
        out = tmp_path / "out"
        out.mkdir()
        target = out / "split-preview-板A.json"
        target.write_text("x", encoding="utf-8")
        _os.link(target, tmp_path / "elsewhere.json")
        r = run_cli(vault, "板A", out)
        assert r.returncode != 0 and "硬链接" in (r.stderr + r.stdout)

    def test_symlink_target_file_rejected(self, tmp_path):
        vault = make_vault(tmp_path, "板A", concepts=[], seed_files={})
        out = tmp_path / "out"
        out.mkdir()
        victim = tmp_path / "victim.json"
        victim.write_text("v", encoding="utf-8")
        (out / "split-preview-板A.json").symlink_to(victim)
        r = run_cli(vault, "板A", out)
        assert r.returncode != 0 and "拒绝写入" in (r.stderr + r.stdout)
        assert victim.read_text(encoding="utf-8") == "v"


RICH_FAKE_SECTION = (
    "### 生成段里的假小节\n\n"
    "这段正文足够长足够长足够长足够长，若剥离逻辑失效它必然成为候选第一行。\n"
    "这段正文同样足够长足够长足够长足够长，两行门槛与字符门槛都轻松越过第二行。\n"
)


class TestStrippingAdversarial:
    """v2 (Codex 二轮 H6): 每个 fixture 的假小节**只有对应剥离标记**能排除——
    strip_generated 整体失效 (全 False) 时这些测试必红, 剥离契约被真正锁住。"""

    def _run(self, tmp_path, board_body_extra: str):
        vault = make_vault(tmp_path, "板X", concepts=[], seed_files={})
        board = vault / "原白板" / "板X.md"
        board.write_text(board.read_text(encoding="utf-8") + "\n" + board_body_extra, encoding="utf-8")
        out = tmp_path / "out"
        assert run_cli(vault, "板X", out).returncode == 0
        return json.loads((out / "split-preview-板X.json").read_text(encoding="utf-8"))

    def test_rich_section_inside_auto_pair_not_candidate(self, tmp_path):
        extra = "<!-- AUTO-GENERATED by test -->\n" + RICH_FAKE_SECTION + "<!-- /AUTO-GENERATED n=0 -->\n"
        data = self._run(tmp_path, extra)
        assert data["candidates"] == [], [c["suggested_name"] for c in data["candidates"]]

    def test_rich_section_inside_fence_not_candidate(self, tmp_path):
        extra = "```text\n" + RICH_FAKE_SECTION + "```\n"
        data = self._run(tmp_path, extra)
        assert data["candidates"] == []

    def test_rich_section_under_recent_activity_not_candidate(self, tmp_path):
        extra = "## Recent Activity\n\n" + RICH_FAKE_SECTION
        data = self._run(tmp_path, extra)
        assert data["candidates"] == []

    def test_rich_section_inside_html_comment_not_candidate_and_no_truncation(self, tmp_path):
        """注释里的 # 不算标题: 既不产生假候选, 也不截断外层真实小节的行区间。"""
        extra = (
            "## 真实小节\n\n"
            "真实正文第一行真实正文第一行真实正文第一行真实正文第一行真实正文第一行。\n"
            "真实正文第二行真实正文第二行真实正文第二行真实正文第二行真实正文第二行。\n\n"
            "<!-- 注释开始\n" + RICH_FAKE_SECTION + "注释结束 -->\n\n"
            "真实小节的尾部正文，仍属于上面的真实小节。\n"
        )
        data = self._run(tmp_path, extra)
        names = [c["suggested_name"] for c in data["candidates"]]
        assert names == ["真实小节"], names
        c = data["candidates"][0]
        # 小节 span 必须越过注释块直到文件尾 (注释内假标题没有截断它)
        assert c["source_anchor"]["line_end"] >= c["source_anchor"]["line_start"] + 8

    def test_derived_callout_inside_fence_not_overlap_evidence(self, tmp_path):
        extra = (
            "## 含示例的小节\n\n"
            "正文第一行正文第一行正文第一行正文第一行正文第一行正文第一行正文第一行。\n"
            "正文第二行正文第二行正文第二行正文第二行正文第二行正文第二行正文第二行。\n\n"
            "```markdown\n> [!relation/refines]+ 已派生为 [[节点/fence里的假重叠]] · 细化\n```\n"
        )
        data = self._run(tmp_path, extra)
        assert len(data["candidates"]) == 1
        assert data["candidates"][0]["derived_overlap"]["overlapping"] is False

    def test_strip_generated_unit_mask(self):
        """直接单测掩码本体 (整体失效的最短红灯)。"""
        mod = load_module()
        lines = [
            "---",
            "type: x",
            "---",
            "# T",
            "```",
            "### fence 里",
            "```",
            "<!-- AUTO-GENERATED x -->",
            "- 目录行",
            "<!-- /AUTO-GENERATED -->",
            "## Recent Activity",
            "- 活动行",
            "正常正文",
        ]
        mask = mod.strip_generated(lines)
        assert mask == [True, True, True, False, True, True, True, True, True, True, True, True, True][: len(mask)] or (
            mask[:3] == [True] * 3 and mask[3] is False and all(mask[4:12]) and mask[12] is True
        ), mask


class TestUnresolvableRendering:
    def test_nine_plus_conflict_gets_no_executable_diff(self, tmp_path):
        """v2 (Codex 二轮 MEDIUM): 9+ 重名候选停用展示性 diff (TS 同场景 throw,
        preview 不得渲染可执行外观的 wikilink 行)。"""
        base = "代理-(Agent)-的定义"
        vault = make_vault(
            tmp_path,
            "板A",
            concepts=["[[节点/种子]] — 种子 · 掌握度 — · 未考"],
            seed_files={"种子": SEED_RICH.format(board="板A")},
            extra_nodes=[base] + [f"{base}_{i}" for i in range(2, 10)],
        )
        out = tmp_path / "out"
        assert run_cli(vault, "板A", out).returncode == 0
        md = (out / "split-preview-板A.md").read_text(encoding="utf-8")
        assert "不提供展示性 diff" in md
        assert f"+ > [!relation/related_to]+ 已派生为 [[节点/{base}]]" not in md


class TestSlugV2Parity:
    """v2 (Codex 二轮 H3): JS 空白集 + UTF-16 词边界阈值的精确移植锚。"""

    def test_hyphen_never_treated_as_whitespace(self):
        mod = load_module()
        assert mod.derive_concept_stub("a-b c") == "a-b-c"

    def test_js_whitespace_set_feff_and_emspace(self):
        mod = load_module()
        # U+FEFF: JS trim/\s 视为空白 (Python \s 不含) — 必须被清理
        assert mod.derive_concept_stub("﻿X Y") == "X-Y"
        # U+2003 em space: 两边都空白 — 折叠为 -
        assert mod.derive_concept_stub("A B") == "A-B"

    def test_utf16_boundary_backoff_matches_ts(self):
        mod = load_module()
        # Codex 反例: 😀(UTF-16 计 2) + 18a + '-' + 25b → 40 码点截断后
        # dash 的 UTF-16 下标 = 20 ≥ 20 → TS 回退到词边界; 码点口径会错判 19 < 20
        s = "\U0001f600" + "a" * 18 + "-" + "b" * 25
        assert mod.derive_concept_stub(s) == "\U0001f600" + "a" * 18

    def test_js_whitespace_negative_set(self):
        """负例锚: Python \\s 独有的 U+0085(NEL)/U+001C-001F 在 JS 口径**不是**空白,
        必须原样保留不折叠 (Codex 三轮 LOW)。"""
        mod = load_module()
        assert mod.derive_concept_stub("A\x85B") == "A\x85B"
        assert mod.derive_concept_stub("A\x1cB") == "A\x1cB"


class TestCounterfactualStripping:
    def test_disabling_strip_generated_turns_fixtures_red(self):
        """反事实固化 (回应 Codex 三轮 H6 的静态推断): strip_generated 整体失效时,
        三类对抗 fixture **全部**产出假候选——含 AUTO 对 (其开闭标记是单行注释,
        comment_mask 只吞标记行, 富假小节不在注释内, 不会被注释掩码兜住)。"""
        mod = load_module()
        auto_doc = "<!-- AUTO-GENERATED by test -->\n" + RICH_FAKE_SECTION + "<!-- /AUTO-GENERATED n=0 -->\n"
        fence_doc = "```text\n" + RICH_FAKE_SECTION + "```\n"
        ra_doc = "## Recent Activity\n\n" + RICH_FAKE_SECTION
        docs = {"auto": auto_doc, "fence": fence_doc, "ra": ra_doc}
        for name, doc in docs.items():
            assert mod.collect_candidates("x.md", doc, "board-body-section") == [], name
        mod.strip_generated = lambda lines: [False] * len(lines)
        for name, doc in docs.items():
            hits = mod.collect_candidates("x.md", doc, "board-body-section")
            assert len(hits) >= 1, f"剥离失效时 {name} fixture 未出假候选 — 剥离契约没锁住"


# ────────────────────────── MD 展示性 diff 诚实声明 ──────────────────────────


class TestPreviewHonesty:
    def test_md_contains_display_only_diff_with_disclaimer(self, tmp_path):
        vault = make_vault(
            tmp_path,
            "板A",
            concepts=["[[节点/种子]] — 种子 · 掌握度 — · 未考"],
            seed_files={"种子": SEED_RICH.format(board="板A")},
        )
        out = tmp_path / "out"
        assert run_cli(vault, "板A", out).returncode == 0
        md = (out / "split-preview-板A.md").read_text(encoding="utf-8")
        assert "未执行" in md and "G5-10" in md
        assert "已派生为 [[节点/" in md  # 展示性 wikilink 插入 diff
        data = json.loads((out / "split-preview-板A.json").read_text(encoding="utf-8"))
        assert data["schema_version"] == 1
        assert "未创建任何节点" in data["not_executed_disclaimer"]
