"""
LangGraph Agent Graph — Adaptive + Corrective RAG (Phase 3)

Unlike state_graph.py (pipeline-oriented: 6-way parallel → fusion → rerank),
this graph is agent-oriented: the LLM controls the entire retrieval + generation flow.

Architecture (based on LangGraph official Agentic RAG pattern):
```
START
  ↓
analyze_intent (LLM decides: search or answer directly?)
  ├──→ retrieve (LLM chose to search)
  │     ↓
  │   grade_documents (LLM evaluates relevance)
  │     ├──→ generate_answer (documents are relevant)
  │     └──→ rewrite_query → analyze_intent (documents irrelevant, retry)
  └──→ generate_answer (LLM has enough context, no search needed)
        ↓
       END
```

Key differences from state_graph.py:
1. LLM decides WHAT to search (not hardcoded 6-way parallel)
2. LLM evaluates document RELEVANCE (not cross-encoder score threshold)
3. LLM can ITERATE: search → evaluate → rewrite → search again
4. LLM controls GENERATION: produces answer with citations

[Source: Agent Architecture Upgrade Plan - Phase 3]
[Reference: LangGraph official Agentic RAG docs]
"""

import logging
from typing import Any, Dict, List, Literal, Optional

from langgraph.graph import END, START, StateGraph

from agentic_rag.state import AgentRAGState, SearchResult

logger = logging.getLogger(__name__)

# Maximum retrieval iterations to prevent infinite loops
MAX_RETRIEVAL_ITERATIONS = 3


# ═══════════════════════════════════════════════════════════════════════════════
# Node 1: Analyze User Intent
# ═══════════════════════════════════════════════════════════════════════════════

async def analyze_intent(state: AgentRAGState) -> dict:
    """
    LLM analyzes the user's intent and decides whether to search.

    This is the entry point of the agent graph. The LLM examines:
    - The user prompt
    - Any pre-fetched context
    - Whether the user has specific requests (e.g., "list notes")

    Returns state updates with intent analysis and search decision.
    """
    user_prompt = state.get("user_prompt", "")
    pre_context = state.get("pre_fetched_context", "")
    retry_count = state.get("retry_count", 0)

    logger.info(
        f"[Phase3] analyze_intent: prompt_len={len(user_prompt)}, "
        f"pre_context_len={len(pre_context)}, retry={retry_count}"
    )

    # Import here to avoid circular deps
    from app.clients.gemini_client import get_gemini_client

    client = get_gemini_client()
    if not client or not client.client:
        logger.warning("[Phase3] Gemini client unavailable, skipping intent analysis")
        return {
            "user_intent": "unknown",
            "has_specific_request": False,
            "search_queries": [],
        }

    # Ask LLM to analyze intent and generate search queries
    analysis_prompt = f"""分析以下用户请求，判断是否需要搜索笔记库获取更多信息。

用户请求:
{user_prompt}

{"已有上下文:" + pre_context[:500] + "..." if pre_context else "（无预加载上下文）"}

请以JSON格式回答:
{{
  "intent": "用户的核心意图（一句话）",
  "has_specific_request": true/false（用户是否有具体请求如"列出笔记"、"举例子"等）,
  "needs_search": true/false（是否需要搜索笔记库获取更多信息）,
  "search_queries": ["查询1", "查询2"]（如果needs_search=true，生成1-3个搜索查询）
}}

只返回JSON，不要其他文字。"""

    try:
        result = await client.call_raw(
            system_prompt="你是一个搜索意图分析器。只返回JSON格式的分析结果。",
            user_prompt=analysis_prompt,
            temperature=0.3,
        )

        import json
        import re
        response_text = result.get("response", "{}")
        # Extract JSON from possible markdown wrapper
        json_match = re.search(r'\{[^{}]*\}', response_text, re.DOTALL)
        if json_match:
            analysis = json.loads(json_match.group())
        else:
            analysis = {}

        intent = analysis.get("intent", "unknown")
        has_request = analysis.get("has_specific_request", False)
        needs_search = analysis.get("needs_search", False)
        queries = analysis.get("search_queries", [])

        logger.info(
            f"[Phase3] Intent: {intent}, needs_search={needs_search}, "
            f"has_request={has_request}, queries={queries}"
        )

        return {
            "user_intent": intent,
            "has_specific_request": bool(has_request),
            "search_queries": queries if needs_search else [],
        }

    except Exception as e:
        logger.warning(f"[Phase3] Intent analysis failed: {e}")
        return {
            "user_intent": "analysis_failed",
            "has_specific_request": False,
            "search_queries": [user_prompt[:200]] if user_prompt else [],
        }


# ═══════════════════════════════════════════════════════════════════════════════
# Node 2: Retrieve (execute search queries)
# ═══════════════════════════════════════════════════════════════════════════════

async def retrieve(state: AgentRAGState) -> dict:
    """
    Execute search queries generated by the LLM.

    Uses existing LanceDB and Graphiti clients for actual retrieval.
    Results are stored in state for the LLM to evaluate.
    """
    queries = state.get("search_queries", [])
    if not queries:
        return {"retrieved_documents": []}

    logger.info(f"[Phase3] retrieve: executing {len(queries)} search queries")

    all_results: List[SearchResult] = []

    try:
        from src.agentic_rag.clients.lancedb_client import LanceDBClient
        lancedb = LanceDBClient.get_instance()

        for query in queries[:3]:  # Max 3 queries
            try:
                results = await lancedb.search(
                    query=query,
                    table_name="vault_notes",
                    num_results=5,
                )
                all_results.extend(results)
                logger.debug(f"[Phase3] LanceDB search '{query[:50]}' → {len(results)} results")
            except Exception as e:
                logger.warning(f"[Phase3] LanceDB search failed for '{query[:50]}': {e}")
                # Try fallback table
                try:
                    results = await lancedb.search(
                        query=query,
                        table_name="canvas_explanations",
                        num_results=3,
                    )
                    all_results.extend(results)
                except Exception:
                    pass

    except ImportError:
        logger.warning("[Phase3] LanceDB client not available")
    except Exception as e:
        logger.warning(f"[Phase3] LanceDB client init failed: {e}")

    # Also search knowledge graph
    try:
        from src.agentic_rag.clients.graphiti_client import GraphitiClient
        graphiti = GraphitiClient.get_instance()

        for query in queries[:2]:  # Fewer queries for KG
            try:
                results = await graphiti.search_nodes(
                    query=query,
                    num_results=3,
                )
                all_results.extend(results)
                logger.debug(f"[Phase3] Graphiti search '{query[:50]}' → {len(results)} results")
            except Exception as e:
                logger.warning(f"[Phase3] Graphiti search failed: {e}")

    except (ImportError, Exception) as e:
        logger.debug(f"[Phase3] Graphiti client not available: {e}")

    # Deduplicate by doc_id
    seen_ids = set()
    unique_results = []
    for r in all_results:
        doc_id = r.get("doc_id", "")
        if doc_id not in seen_ids:
            seen_ids.add(doc_id)
            unique_results.append(r)

    logger.info(f"[Phase3] retrieve: {len(unique_results)} unique documents retrieved")

    return {"retrieved_documents": unique_results}


# ═══════════════════════════════════════════════════════════════════════════════
# Node 3: Grade Documents (LLM evaluates relevance)
# ═══════════════════════════════════════════════════════════════════════════════

async def grade_documents(state: AgentRAGState) -> dict:
    """
    LLM evaluates whether retrieved documents are relevant to the user's question.

    This replaces the hardcoded cross-encoder threshold (avg_score >= 0.7)
    with semantic relevance judgment by the LLM.
    """
    documents = state.get("retrieved_documents", [])
    user_prompt = state.get("user_prompt", "")
    user_intent = state.get("user_intent", "")

    if not documents:
        return {
            "document_grades": [],
            "relevant_documents": [],
        }

    logger.info(f"[Phase3] grade_documents: evaluating {len(documents)} documents")

    from app.clients.gemini_client import get_gemini_client
    client = get_gemini_client()

    if not client or not client.client:
        # Fallback: use score threshold
        relevant = [d for d in documents if d.get("score", 0) >= 0.5]
        return {
            "document_grades": ["relevant" if d.get("score", 0) >= 0.5 else "irrelevant" for d in documents],
            "relevant_documents": relevant,
        }

    # Build grading prompt with document summaries
    doc_summaries = []
    for i, doc in enumerate(documents[:10]):  # Max 10 docs to grade
        content = doc.get("content", "")[:300]
        source = doc.get("metadata", {}).get("source", "unknown")
        doc_summaries.append(f"[Doc {i+1}] (source: {source})\n{content}")

    grading_prompt = f"""用户意图: {user_intent}
用户请求: {user_prompt[:300]}

以下是检索到的文档，请判断每个文档是否与用户请求相关。
返回JSON数组，每个元素为 "relevant" 或 "irrelevant"。

文档列表:
{"---".join(doc_summaries)}

返回格式: ["relevant", "irrelevant", "relevant", ...]
只返回JSON数组，不要其他文字。"""

    try:
        result = await client.call_raw(
            system_prompt="你是一个文档相关性评估器。只返回JSON数组。",
            user_prompt=grading_prompt,
            temperature=0.1,
        )

        import json
        import re
        response_text = result.get("response", "[]")
        json_match = re.search(r'\[.*\]', response_text, re.DOTALL)
        if json_match:
            grades = json.loads(json_match.group())
        else:
            grades = ["relevant"] * len(documents)  # Default to relevant

        # Ensure grades length matches documents
        while len(grades) < len(documents):
            grades.append("irrelevant")
        grades = grades[:len(documents)]

        relevant_docs = [
            doc for doc, grade in zip(documents, grades)
            if grade == "relevant"
        ]

        logger.info(
            f"[Phase3] grade_documents: {len(relevant_docs)}/{len(documents)} relevant"
        )

        return {
            "document_grades": grades,
            "relevant_documents": relevant_docs,
        }

    except Exception as e:
        logger.warning(f"[Phase3] Document grading failed: {e}. Using score fallback.")
        relevant = [d for d in documents if d.get("score", 0) >= 0.5]
        return {
            "document_grades": ["fallback"] * len(documents),
            "relevant_documents": relevant,
        }


# ═══════════════════════════════════════════════════════════════════════════════
# Node 4: Rewrite Query (LLM improves search query)
# ═══════════════════════════════════════════════════════════════════════════════

async def rewrite_query(state: AgentRAGState) -> dict:
    """
    LLM rewrites the search query when retrieved documents are insufficient.

    Instead of the placeholder "请详细解释: {query}", the LLM generates
    semantically improved queries based on what was missing.
    """
    retry_count = state.get("retry_count", 0)
    original_queries = state.get("search_queries", [])
    user_prompt = state.get("user_prompt", "")
    user_intent = state.get("user_intent", "")

    logger.info(f"[Phase3] rewrite_query: retry={retry_count}, original_queries={original_queries}")

    from app.clients.gemini_client import get_gemini_client
    client = get_gemini_client()

    if not client or not client.client:
        # Simple fallback rewrite
        new_queries = [f"详细解释 {q}" for q in original_queries[:2]]
        return {
            "search_queries": new_queries,
            "retry_count": retry_count + 1,
        }

    rewrite_prompt = f"""之前的搜索查询没有找到足够相关的结果。

用户意图: {user_intent}
用户请求: {user_prompt[:300]}
之前的查询: {original_queries}

请生成2-3个改进的搜索查询，尝试不同的关键词和角度。
返回JSON数组: ["查询1", "查询2", "查询3"]
只返回JSON数组。"""

    try:
        result = await client.call_raw(
            system_prompt="你是一个搜索查询优化器。只返回JSON数组。",
            user_prompt=rewrite_prompt,
            temperature=0.5,
        )

        import json
        import re
        response_text = result.get("response", "[]")
        json_match = re.search(r'\[.*\]', response_text, re.DOTALL)
        if json_match:
            new_queries = json.loads(json_match.group())
        else:
            new_queries = [f"详细解释 {q}" for q in original_queries[:2]]

        logger.info(f"[Phase3] Rewritten queries: {new_queries}")

        return {
            "search_queries": new_queries[:3],
            "retry_count": retry_count + 1,
        }

    except Exception as e:
        logger.warning(f"[Phase3] Query rewrite failed: {e}")
        return {
            "search_queries": [f"详细解释 {q}" for q in original_queries[:2]],
            "retry_count": retry_count + 1,
        }


# ═══════════════════════════════════════════════════════════════════════════════
# Node 5: Generate Final Answer
# ═══════════════════════════════════════════════════════════════════════════════

async def generate_answer(state: AgentRAGState) -> dict:
    """
    LLM generates the final answer using the agent template + retrieved context.

    Combines:
    - Agent system prompt (from template)
    - Pre-fetched context (Phase 1 compatibility)
    - LLM-retrieved documents (Phase 3 enhancement)
    - User prompt
    """
    agent_type = state.get("agent_type", "oral-explanation")
    user_prompt = state.get("user_prompt", "")
    system_prompt = state.get("system_prompt", "")
    pre_context = state.get("pre_fetched_context", "")
    relevant_docs = state.get("relevant_documents", [])

    logger.info(
        f"[Phase3] generate_answer: agent={agent_type}, "
        f"docs={len(relevant_docs)}, pre_context_len={len(pre_context)}"
    )

    # Build enhanced context combining pre-fetched and LLM-retrieved
    context_parts = []
    if pre_context:
        context_parts.append(pre_context)

    if relevant_docs:
        doc_context = "\n\n### LLM检索的补充资料\n"
        for i, doc in enumerate(relevant_docs[:5], 1):
            content = doc.get("content", "")[:400]
            metadata = doc.get("metadata", {})
            source = metadata.get("source", "unknown")
            canvas_file = metadata.get("canvas_file", "")
            citation = f"[{source}: {canvas_file}]" if canvas_file else f"[{source}]"
            doc_context += f"\n**资料{i}** {citation}:\n{content}\n"
        context_parts.append(doc_context)

    full_context = "\n".join(context_parts) if context_parts else None

    # Use GeminiClient to generate with the agent template
    from app.clients.gemini_client import get_gemini_client
    client = get_gemini_client()

    if not client or not client.is_configured():
        return {
            "final_answer": "[Error] AI client not configured",
            "generation_complete": True,
            "citations": [],
        }

    try:
        result = await client.call_agent(
            agent_type=agent_type,
            user_prompt=user_prompt,
            context=full_context,
            temperature=0.7,
        )

        answer = result.get("response", "")

        # Extract citations from the answer (simple pattern matching)
        import re
        citation_pattern = r'\[([^\]]+\.md[^\]]*)\]'
        found_citations = re.findall(citation_pattern, answer)
        citations = [
            {"source": c, "type": "inline_reference"}
            for c in found_citations[:10]
        ]

        logger.info(
            f"[Phase3] Answer generated: len={len(answer)}, citations={len(citations)}"
        )

        return {
            "final_answer": answer,
            "generation_complete": True,
            "citations": citations,
        }

    except Exception as e:
        logger.error(f"[Phase3] Answer generation failed: {e}")
        return {
            "final_answer": f"[Error] Generation failed: {str(e)[:200]}",
            "generation_complete": True,
            "citations": [],
        }


# ═══════════════════════════════════════════════════════════════════════════════
# Conditional Edges (routing functions)
# ═══════════════════════════════════════════════════════════════════════════════

def route_after_intent(state: AgentRAGState) -> Literal["retrieve", "generate_answer"]:
    """Route based on intent analysis: search or answer directly."""
    queries = state.get("search_queries", [])
    pre_context = state.get("pre_fetched_context", "")

    if queries:
        logger.debug(f"[Phase3] route_after_intent → retrieve ({len(queries)} queries)")
        return "retrieve"

    # No search needed — answer directly with pre-fetched context
    logger.debug("[Phase3] route_after_intent → generate_answer (no search needed)")
    return "generate_answer"


def route_after_grading(state: AgentRAGState) -> Literal["generate_answer", "rewrite_query"]:
    """Route based on document grading: generate or retry."""
    relevant_docs = state.get("relevant_documents", [])
    retry_count = state.get("retry_count", 0)

    # Enough relevant docs or max retries reached
    if relevant_docs or retry_count >= MAX_RETRIEVAL_ITERATIONS:
        if retry_count >= MAX_RETRIEVAL_ITERATIONS and not relevant_docs:
            logger.warning(
                f"[Phase3] Max retries ({MAX_RETRIEVAL_ITERATIONS}) reached with "
                f"no relevant docs. Generating with available context."
            )
        logger.debug(
            f"[Phase3] route_after_grading → generate_answer "
            f"(relevant={len(relevant_docs)}, retry={retry_count})"
        )
        return "generate_answer"

    # Not enough relevant docs — rewrite query
    logger.debug(f"[Phase3] route_after_grading → rewrite_query (retry={retry_count})")
    return "rewrite_query"


# ═══════════════════════════════════════════════════════════════════════════════
# Build Agent Graph
# ═══════════════════════════════════════════════════════════════════════════════

def build_agent_rag_graph() -> StateGraph:
    """
    Build the Phase 3 Agentic RAG graph.

    Graph Structure (Adaptive + Corrective RAG):
    ```
    START → analyze_intent
              ├──→ retrieve → grade_documents
              │                  ├──→ generate_answer → END
              │                  └──→ rewrite_query → analyze_intent (loop)
              └──→ generate_answer → END
    ```

    Returns:
        Compiled StateGraph ready for invocation
    """
    builder = StateGraph(AgentRAGState)

    # Add nodes
    builder.add_node("analyze_intent", analyze_intent)
    builder.add_node("retrieve", retrieve)
    builder.add_node("grade_documents", grade_documents)
    builder.add_node("rewrite_query", rewrite_query)
    builder.add_node("generate_answer", generate_answer)

    # Add edges
    builder.add_edge(START, "analyze_intent")

    builder.add_conditional_edges(
        "analyze_intent",
        route_after_intent,
        {
            "retrieve": "retrieve",
            "generate_answer": "generate_answer",
        },
    )

    builder.add_edge("retrieve", "grade_documents")

    builder.add_conditional_edges(
        "grade_documents",
        route_after_grading,
        {
            "generate_answer": "generate_answer",
            "rewrite_query": "rewrite_query",
        },
    )

    # Rewrite loops back to analyze_intent (which will route to retrieve again)
    builder.add_edge("rewrite_query", "analyze_intent")

    builder.add_edge("generate_answer", END)

    graph = builder.compile()
    logger.info("[Phase3] Agent RAG graph compiled successfully")
    return graph


# Lazy singleton for the compiled graph
_agent_graph = None


def get_agent_rag_graph():
    """Get or create the singleton agent RAG graph."""
    global _agent_graph
    if _agent_graph is None:
        _agent_graph = build_agent_rag_graph()
    return _agent_graph
