/**
 * Association Types - Canvas Learning System Cross-Canvas Associations
 *
 * Type definitions for cross-Canvas association management.
 * Implements Story 16.1: Canvas关联UI
 *
 * @module AssociationTypes
 * @version 1.0.0
 *
 * Source: Story 16.1 Dev Notes - 数据模型定义
 * Schema: specs/data/canvas-association.schema.json
 *
 * ✅ Verified from @obsidian-canvas Skill (Canvas API)
 * ✅ Verified from canvas-association.schema.json
 */

/**
 * Association type enumeration
 * Defines the semantic relationship between two Canvas files
 *
 * ✅ Verified from canvas-association.schema.json (association_type enum)
 */
export type AssociationType = 'prerequisite' | 'related' | 'extends' | 'references';

/**
 * Sync status for Graphiti knowledge graph synchronization
 *
 * ✅ Verified from Story 16.7 Dev Notes (SyncStatus interface)
 */
export type SyncStatus = 'syncing' | 'synced' | 'error' | 'pending';

/**
 * Canvas Association - Core data structure
 * Represents a semantic relationship between two Canvas files
 *
 * ✅ Verified from canvas-association.schema.json
 */
export interface CanvasAssociation {
    /** Unique identifier (UUID v4) */
    association_id: string;

    /** Source Canvas file path (relative to vault root) */
    source_canvas: string;

    /** Target Canvas file path (relative to vault root) */
    target_canvas: string;

    /** Type of association */
    association_type: AssociationType;

    /** Shared concepts between the two Canvas files */
    shared_concepts?: string[];

    /** Relevance score (0.0 - 1.0, higher = more relevant) */
    relevance_score?: number;

    /** Whether the association is bidirectional */
    bidirectional?: boolean;

    /** Whether this association was auto-generated by the system */
    auto_generated?: boolean;

    /** ISO 8601 timestamp when the association was created */
    created_at?: string;

    /** ISO 8601 timestamp when the association was last updated */
    updated_at?: string;

    /** Optional user-provided description */
    description?: string;

    /** Node-level associations (optional, for fine-grained linking) */
    node_associations?: NodeAssociation[];
}

/**
 * Node-level association for fine-grained cross-Canvas linking
 *
 * ✅ Verified from Story 16.3 Dev Notes (node-to-node linking)
 */
export interface NodeAssociation {
    /** Source node ID within source Canvas */
    source_node_id: string;

    /** Target node ID within target Canvas */
    target_node_id: string;

    /** Confidence score for this node association */
    confidence?: number;
}

/**
 * Association status for display in status bar
 *
 * ✅ Verified from Story 16.7 Dev Notes (AssociationStatus interface)
 */
export interface AssociationStatus {
    /** Current Canvas path */
    canvas_path: string;

    /** Number of associations for current Canvas */
    association_count: number;

    /** Sync status with Graphiti */
    sync_status: SyncStatus;

    /** ISO 8601 timestamp of last sync */
    last_sync: string;

    /** Error message if sync_status is 'error' */
    error_message?: string;

    /** List of associated Canvas names (for tooltip) */
    associated_canvas_names?: string[];
}

/**
 * Textbook reference for educational context
 *
 * ✅ Verified from Story 16.6 Dev Notes (TextbookReference interface)
 */
export interface TextbookReference {
    /** Path to the textbook Canvas */
    textbook_canvas: string;

    /** Human-readable textbook name */
    textbook_name: string;

    /** Section or chapter name */
    section_name: string;

    /** Target node ID in the textbook Canvas */
    node_id: string;

    /** Optional page number */
    page_number?: number;
}

/**
 * Textbook context for Agent injection
 *
 * ✅ Verified from Story 16.5 Dev Notes (TextbookContext interface)
 */
export interface TextbookContext {
    /** Path to the textbook Canvas */
    textbook_canvas: string;

    /** Section name */
    section_name: string;

    /** Target node ID */
    node_id: string;

    /** Relevance score (0.0 - 1.0) */
    relevance_score: number;

    /** Content preview (first 100 chars) */
    content_preview: string;
}

/**
 * Prerequisite concept detected by Agent
 *
 * ✅ Verified from Story 16.5 Dev Notes (Prerequisite interface)
 */
export interface Prerequisite {
    /** Concept name */
    concept_name: string;

    /** Source Canvas path where the concept is explained */
    source_canvas: string;

    /** Node ID containing the concept */
    node_id: string;

    /** Confidence that this is a prerequisite */
    confidence: number;
}

/**
 * Association mode state for toggle control
 *
 * ✅ Verified from Story 16.4 Dev Notes (AssociationModeState interface)
 */
export interface AssociationModeState {
    /** Whether association mode is enabled */
    enabled: boolean;

    /** ISO 8601 timestamp of last toggle */
    lastToggled: string;
}

/**
 * Canvas links configuration file structure
 *
 * ✅ Verified from Story 16.2 Dev Notes (.canvas-links.json schema)
 */
export interface CanvasLinksConfig {
    /** Schema version for migration support */
    version: string;

    /** List of Canvas associations */
    associations: CanvasAssociation[];

    /** Global settings */
    settings?: CanvasLinksSettings;

    /** Metadata */
    metadata?: CanvasLinksMetadata;
}

/**
 * Settings within .canvas-links.json
 */
export interface CanvasLinksSettings {
    /** Auto-detect associations on Canvas save */
    auto_detect: boolean;

    /** Minimum confidence threshold for auto-detection */
    min_confidence: number;

    /** Sync to Graphiti automatically */
    auto_sync: boolean;
}

/**
 * Metadata within .canvas-links.json
 */
export interface CanvasLinksMetadata {
    /** ISO 8601 timestamp when file was created */
    created_at: string;

    /** ISO 8601 timestamp when file was last updated */
    updated_at: string;

    /** Number of times the file has been updated */
    update_count: number;
}

/**
 * Association type display configuration
 */
export const ASSOCIATION_TYPE_CONFIG: Record<AssociationType, {
    label: string;
    icon: string;
    description: string;
    color: string;
}> = {
    prerequisite: {
        label: '前置知识',
        icon: '📚',
        description: '需要先学习的基础知识',
        color: '#e74c3c'
    },
    related: {
        label: '相关内容',
        icon: '🔗',
        description: '相关联的知识点',
        color: '#3498db'
    },
    extends: {
        label: '扩展内容',
        icon: '📈',
        description: '深入或扩展的知识',
        color: '#2ecc71'
    },
    references: {
        label: '教材引用',
        icon: '📖',
        description: '引用的教材或参考资料',
        color: '#9b59b6'
    }
};

/**
 * Default values for new associations
 */
export const DEFAULT_ASSOCIATION: Partial<CanvasAssociation> = {
    association_type: 'related',
    bidirectional: false,
    auto_generated: false,
    relevance_score: 0.5,
    shared_concepts: []
};

/**
 * Default canvas links configuration
 */
export const DEFAULT_CANVAS_LINKS_CONFIG: CanvasLinksConfig = {
    version: '1.0.0',
    associations: [],
    settings: {
        auto_detect: false,
        min_confidence: 0.6,
        auto_sync: true
    },
    metadata: {
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        update_count: 0
    }
};
